package advent.aoc2016;

import java.util.ArrayList;
import java.util.HashMap;

import advent.utilities.general.DayRunner;
import advent.utilities.general.IDay;

public class Day06 implements IDay {

	String input = "edayownz\r\n"
			+ "qevxxipf\r\n"
			+ "oyfsuaok\r\n"
			+ "zfmvayzp\r\n"
			+ "gthxucti\r\n"
			+ "iqxyfvll\r\n"
			+ "prkedskq\r\n"
			+ "yqhhlxlf\r\n"
			+ "atpwtvcn\r\n"
			+ "nmkelcha\r\n"
			+ "kyduptlo\r\n"
			+ "xndlncrq\r\n"
			+ "tipblras\r\n"
			+ "yctuizxl\r\n"
			+ "lsgooprx\r\n"
			+ "dqxnjqqg\r\n"
			+ "ssocughj\r\n"
			+ "yaivjuxw\r\n"
			+ "zcsknpig\r\n"
			+ "fhzrgqrx\r\n"
			+ "chkhrruy\r\n"
			+ "icnkylam\r\n"
			+ "kbqlhbvu\r\n"
			+ "znjxbmph\r\n"
			+ "qmcoeozq\r\n"
			+ "jdhmdkwn\r\n"
			+ "eihlergj\r\n"
			+ "oxygpsiw\r\n"
			+ "eahthlnd\r\n"
			+ "ghclibzv\r\n"
			+ "mhuuyxyn\r\n"
			+ "vmdgtxbb\r\n"
			+ "liwbkvko\r\n"
			+ "bshezmju\r\n"
			+ "itispews\r\n"
			+ "gqapeypr\r\n"
			+ "rscjseri\r\n"
			+ "hjduhfhe\r\n"
			+ "kvcgjclk\r\n"
			+ "hosxlvmy\r\n"
			+ "tlclgvua\r\n"
			+ "riisgkkg\r\n"
			+ "zeuhprjp\r\n"
			+ "hvroersj\r\n"
			+ "bextpjjm\r\n"
			+ "nvnehksu\r\n"
			+ "xdizemfw\r\n"
			+ "rclldruz\r\n"
			+ "yqlmidvv\r\n"
			+ "unqprmbv\r\n"
			+ "bbzhhwck\r\n"
			+ "psneussu\r\n"
			+ "vwioupfs\r\n"
			+ "cqgxohsd\r\n"
			+ "kmxmpxpi\r\n"
			+ "ycgkyssk\r\n"
			+ "hmlpirmz\r\n"
			+ "gjwupihp\r\n"
			+ "erxmlqjf\r\n"
			+ "iywpocue\r\n"
			+ "guvqdahd\r\n"
			+ "xklbtvzq\r\n"
			+ "fmfezcwj\r\n"
			+ "wdttpdcl\r\n"
			+ "eoaljfnd\r\n"
			+ "tovgtunp\r\n"
			+ "hpttqedt\r\n"
			+ "vwozzoms\r\n"
			+ "xotvgahm\r\n"
			+ "abushckh\r\n"
			+ "msdnfnxz\r\n"
			+ "zdpibocq\r\n"
			+ "kzjiijni\r\n"
			+ "xigcngbb\r\n"
			+ "raeqmzbv\r\n"
			+ "yjabwdtc\r\n"
			+ "qnnjxiqs\r\n"
			+ "kffhcdbt\r\n"
			+ "oxwdnsyq\r\n"
			+ "jpkxkwgg\r\n"
			+ "lunyifxj\r\n"
			+ "zziecuwq\r\n"
			+ "ppxcppnf\r\n"
			+ "ezlghprw\r\n"
			+ "mbyoczdv\r\n"
			+ "ijhqlapc\r\n"
			+ "zskkzaax\r\n"
			+ "cavtwzww\r\n"
			+ "ywhqysqa\r\n"
			+ "gxixgaid\r\n"
			+ "rdplryfx\r\n"
			+ "vxzwidxk\r\n"
			+ "yfpnmhnn\r\n"
			+ "pbkyjzar\r\n"
			+ "dqzgtcso\r\n"
			+ "ilzvjgfc\r\n"
			+ "diftsigx\r\n"
			+ "zoeqphho\r\n"
			+ "yufniiec\r\n"
			+ "iiswsmrc\r\n"
			+ "fjkbnzlz\r\n"
			+ "jkoldwjd\r\n"
			+ "dcuwtgyr\r\n"
			+ "jvkubfei\r\n"
			+ "wgfpgmge\r\n"
			+ "cvslbjik\r\n"
			+ "jfmkqujl\r\n"
			+ "vunhzfdb\r\n"
			+ "mxsyvstd\r\n"
			+ "jneeyqte\r\n"
			+ "mzbaxtqt\r\n"
			+ "uhodcjil\r\n"
			+ "qqinvvoa\r\n"
			+ "hhjqwaog\r\n"
			+ "kbxrwlop\r\n"
			+ "xaifsdzd\r\n"
			+ "ojndbnxs\r\n"
			+ "cyvutfok\r\n"
			+ "mubxvkds\r\n"
			+ "wguoyxzh\r\n"
			+ "wcwaauif\r\n"
			+ "olgzrtab\r\n"
			+ "qvsxggvh\r\n"
			+ "ujvuwwzc\r\n"
			+ "nuvwxepc\r\n"
			+ "pydsjlgh\r\n"
			+ "zvqtajky\r\n"
			+ "dpmdjhnd\r\n"
			+ "rcuhhmif\r\n"
			+ "vfxzonrp\r\n"
			+ "okhiinzj\r\n"
			+ "mkcqcnnv\r\n"
			+ "ieygctny\r\n"
			+ "qyfjqlzm\r\n"
			+ "tajvptkv\r\n"
			+ "oltkvacv\r\n"
			+ "hqmecybl\r\n"
			+ "unpsmheo\r\n"
			+ "kxmamiib\r\n"
			+ "evggknyl\r\n"
			+ "mfrvrykw\r\n"
			+ "bqasfoun\r\n"
			+ "jopiyvnd\r\n"
			+ "nxamdqbn\r\n"
			+ "lskjwhqt\r\n"
			+ "rrmbyyte\r\n"
			+ "elsvrfej\r\n"
			+ "pudzkrcm\r\n"
			+ "ltpdxcrc\r\n"
			+ "rlqfxmfr\r\n"
			+ "sdnpdswd\r\n"
			+ "zhiyftpv\r\n"
			+ "ksbkhiab\r\n"
			+ "ogkezijn\r\n"
			+ "uctbhbpy\r\n"
			+ "jlkndedy\r\n"
			+ "ryrlgbrh\r\n"
			+ "zgqoacnp\r\n"
			+ "zzqkqbcn\r\n"
			+ "xholtory\r\n"
			+ "liynoaqx\r\n"
			+ "euwefqvm\r\n"
			+ "ekmdkqlg\r\n"
			+ "bmbfokxo\r\n"
			+ "blovckfl\r\n"
			+ "uxjjkoes\r\n"
			+ "ywzprxog\r\n"
			+ "uxvaegwv\r\n"
			+ "mzwnwnzg\r\n"
			+ "skenfyuq\r\n"
			+ "dgarqgnr\r\n"
			+ "qversoqf\r\n"
			+ "cgbehjht\r\n"
			+ "fqpzffoe\r\n"
			+ "asmauutz\r\n"
			+ "qegkxdas\r\n"
			+ "utvsgjxe\r\n"
			+ "eqtkqpjw\r\n"
			+ "wgscmuel\r\n"
			+ "sylgqbai\r\n"
			+ "meekpavr\r\n"
			+ "qawaeltl\r\n"
			+ "pmfmzday\r\n"
			+ "eacuapxf\r\n"
			+ "ujjjpztx\r\n"
			+ "jzdozhgv\r\n"
			+ "iwtjotig\r\n"
			+ "wyfvplbr\r\n"
			+ "mpnusncj\r\n"
			+ "jimlnzqr\r\n"
			+ "ewixftvu\r\n"
			+ "nchodvro\r\n"
			+ "iioutsdt\r\n"
			+ "emlphqzc\r\n"
			+ "frurxhki\r\n"
			+ "snpdeobb\r\n"
			+ "pjqfbikx\r\n"
			+ "ylwukgpi\r\n"
			+ "gogxroix\r\n"
			+ "wrwwcwij\r\n"
			+ "vtaqqpah\r\n"
			+ "blrbupmr\r\n"
			+ "mqaqmfhz\r\n"
			+ "gwuzsbmw\r\n"
			+ "bfmstsdt\r\n"
			+ "vfhbyfqb\r\n"
			+ "xvithmha\r\n"
			+ "krsruynd\r\n"
			+ "lvdvkmso\r\n"
			+ "iobpdwll\r\n"
			+ "ialoymtw\r\n"
			+ "zaokarah\r\n"
			+ "xckbjyyw\r\n"
			+ "ysqavfyg\r\n"
			+ "zxxzzhkc\r\n"
			+ "dhbplxba\r\n"
			+ "ikdndwsj\r\n"
			+ "dgrosyji\r\n"
			+ "stydweit\r\n"
			+ "rqithswc\r\n"
			+ "mprjkbcm\r\n"
			+ "tpefyiyd\r\n"
			+ "ugwanchp\r\n"
			+ "lfntfnvp\r\n"
			+ "ldffntfm\r\n"
			+ "kurlyldh\r\n"
			+ "pujosrgy\r\n"
			+ "okgdikeg\r\n"
			+ "zxbintiq\r\n"
			+ "awqffyyc\r\n"
			+ "kzjcgkgl\r\n"
			+ "dpstrbqq\r\n"
			+ "hznvceti\r\n"
			+ "grqvykxz\r\n"
			+ "hpgsjjpn\r\n"
			+ "yelqmlbz\r\n"
			+ "ydenklms\r\n"
			+ "fgtemjds\r\n"
			+ "hwlqvvig\r\n"
			+ "sncpgltw\r\n"
			+ "grkosjlo\r\n"
			+ "nbxjnfra\r\n"
			+ "fxvsemon\r\n"
			+ "souhaowz\r\n"
			+ "pkcnohff\r\n"
			+ "vhcreeba\r\n"
			+ "fynixcza\r\n"
			+ "inxtrakx\r\n"
			+ "farxvioo\r\n"
			+ "agsnldgu\r\n"
			+ "rvvgqkvf\r\n"
			+ "daabmava\r\n"
			+ "fewhpwqc\r\n"
			+ "dttqfpzj\r\n"
			+ "vrgqbglu\r\n"
			+ "ggsinjno\r\n"
			+ "ahwxqpvb\r\n"
			+ "ucxyogfk\r\n"
			+ "oyejznyl\r\n"
			+ "ojfgaztf\r\n"
			+ "xcykczts\r\n"
			+ "vuryincu\r\n"
			+ "ixqgbsdj\r\n"
			+ "acbanjtm\r\n"
			+ "tdyqtrmo\r\n"
			+ "nhnbzozm\r\n"
			+ "tqzoqesh\r\n"
			+ "cfcplowu\r\n"
			+ "arbixqul\r\n"
			+ "cnrplnfa\r\n"
			+ "xmigrqle\r\n"
			+ "rmjyyzeh\r\n"
			+ "hpjhnoxt\r\n"
			+ "lqzpfwlv\r\n"
			+ "qefdfezf\r\n"
			+ "yuypbdfq\r\n"
			+ "mneruzvm\r\n"
			+ "wxmydvis\r\n"
			+ "xsfvldhb\r\n"
			+ "vzxcaquj\r\n"
			+ "aaysnxex\r\n"
			+ "rkppoeey\r\n"
			+ "jdozzlnr\r\n"
			+ "bhwmkdiz\r\n"
			+ "crpaljad\r\n"
			+ "llqcfxwd\r\n"
			+ "loonmljh\r\n"
			+ "iwvywckw\r\n"
			+ "sxslcqoh\r\n"
			+ "ldcnmmwp\r\n"
			+ "zedceaeu\r\n"
			+ "deufsoyu\r\n"
			+ "oomrzukn\r\n"
			+ "kfasaxan\r\n"
			+ "vpnmdimg\r\n"
			+ "sotdxjpn\r\n"
			+ "nslotgct\r\n"
			+ "vblvivxh\r\n"
			+ "busfjvlz\r\n"
			+ "abcmroxw\r\n"
			+ "bslpzufv\r\n"
			+ "czvbqijh\r\n"
			+ "wsdpwryu\r\n"
			+ "ygtfjuyp\r\n"
			+ "tlphfumq\r\n"
			+ "rrdvvugh\r\n"
			+ "cxiivwmf\r\n"
			+ "majaarpb\r\n"
			+ "woekjbuw\r\n"
			+ "fappbyau\r\n"
			+ "sebfoflc\r\n"
			+ "mbfuexcc\r\n"
			+ "xansapct\r\n"
			+ "cduuxgyi\r\n"
			+ "jbjcsblt\r\n"
			+ "pntseavw\r\n"
			+ "kmkqmsqz\r\n"
			+ "rraranvr\r\n"
			+ "vlbqtwck\r\n"
			+ "xbhlqnqt\r\n"
			+ "lgsbuagd\r\n"
			+ "rbvtgaxj\r\n"
			+ "blyabybe\r\n"
			+ "henduein\r\n"
			+ "qjncjzah\r\n"
			+ "tqxhwqlw\r\n"
			+ "mhrqqspx\r\n"
			+ "bkydjpoq\r\n"
			+ "tywauuvf\r\n"
			+ "ouulbehj\r\n"
			+ "gmeaujhk\r\n"
			+ "wozdrlpz\r\n"
			+ "afzilmuc\r\n"
			+ "bqojkapy\r\n"
			+ "fhxrteew\r\n"
			+ "ulzwchev\r\n"
			+ "uisqbsff\r\n"
			+ "dyabtzax\r\n"
			+ "uqchomer\r\n"
			+ "zpumjhgy\r\n"
			+ "tyrnstet\r\n"
			+ "qidwkkgd\r\n"
			+ "ahxyarzu\r\n"
			+ "yeqiadpt\r\n"
			+ "arzcxnjb\r\n"
			+ "sedukbar\r\n"
			+ "vehseved\r\n"
			+ "mvrlcetm\r\n"
			+ "foyxewke\r\n"
			+ "wdceguqh\r\n"
			+ "psktwwrf\r\n"
			+ "qidupsru\r\n"
			+ "ngijgwtx\r\n"
			+ "ogcrudpu\r\n"
			+ "kwhlixob\r\n"
			+ "dzdtrvqa\r\n"
			+ "outiqhrg\r\n"
			+ "vpsuldwp\r\n"
			+ "gnodzyfg\r\n"
			+ "trrfkpoq\r\n"
			+ "ppunsbnx\r\n"
			+ "zcugptti\r\n"
			+ "fxhheqbf\r\n"
			+ "eddsaqgj\r\n"
			+ "cobpfrjl\r\n"
			+ "vwqfmlib\r\n"
			+ "kzcefymt\r\n"
			+ "njfyehdq\r\n"
			+ "dcocnsyp\r\n"
			+ "jdvkuxvr\r\n"
			+ "bkbdxpus\r\n"
			+ "umpilgyg\r\n"
			+ "yvjgghfr\r\n"
			+ "cqgujxms\r\n"
			+ "svtucbvi\r\n"
			+ "eghdzlve\r\n"
			+ "htzgeocp\r\n"
			+ "qyaqblby\r\n"
			+ "otxzspak\r\n"
			+ "nzvzuuzx\r\n"
			+ "khzhlkhq\r\n"
			+ "vnoalkux\r\n"
			+ "oawnycto\r\n"
			+ "ynlnxjka\r\n"
			+ "ouowyusf\r\n"
			+ "nfqzgjje\r\n"
			+ "renfsdtp\r\n"
			+ "jmlckpss\r\n"
			+ "xnucnvla\r\n"
			+ "wnphnmde\r\n"
			+ "eszjzuim\r\n"
			+ "cwxjbifm\r\n"
			+ "rofbizjy\r\n"
			+ "cwxeafvi\r\n"
			+ "guorrfss\r\n"
			+ "xsufaepj\r\n"
			+ "lbncoixc\r\n"
			+ "hpzziggn\r\n"
			+ "tyltjgpi\r\n"
			+ "ubegrqxz\r\n"
			+ "bhtaoiuk\r\n"
			+ "bkkjzrmu\r\n"
			+ "irfinrlk\r\n"
			+ "gmholyrx\r\n"
			+ "tcuwtwmn\r\n"
			+ "fxixgmeo\r\n"
			+ "ltvxyudy\r\n"
			+ "sxmmpdvc\r\n"
			+ "ewqldfhz\r\n"
			+ "tfafbwul\r\n"
			+ "ciijowfk\r\n"
			+ "mwemtqmv\r\n"
			+ "gwojqcsg\r\n"
			+ "hmfrvalw\r\n"
			+ "szqbemsq\r\n"
			+ "jkyaglii\r\n"
			+ "zetwsswt\r\n"
			+ "dujxheug\r\n"
			+ "nwmebpqt\r\n"
			+ "xzhdwgyy\r\n"
			+ "ucmzfjzr\r\n"
			+ "pdqsftob\r\n"
			+ "rtjmvbyi\r\n"
			+ "otnfglss\r\n"
			+ "nfvkhhru\r\n"
			+ "bxqcvvdo\r\n"
			+ "qljvnqbd\r\n"
			+ "wfjbwcgi\r\n"
			+ "gdwzhdkd\r\n"
			+ "sardfknc\r\n"
			+ "wvhuqxsa\r\n"
			+ "abgmwher\r\n"
			+ "tfqrdsgm\r\n"
			+ "flyjmfff\r\n"
			+ "lprmhgzz\r\n"
			+ "pjposbov\r\n"
			+ "jyvmzmlx\r\n"
			+ "zkacwauz\r\n"
			+ "kgyothce\r\n"
			+ "aytmcgnf\r\n"
			+ "atiwoznr\r\n"
			+ "jblykexy\r\n"
			+ "nziwkcsb\r\n"
			+ "bxejmnma\r\n"
			+ "cjhhdzoj\r\n"
			+ "ucgkmduk\r\n"
			+ "jszgrfhh\r\n"
			+ "gvcwuorc\r\n"
			+ "czopwrwg\r\n"
			+ "bilvjtju\r\n"
			+ "uqgfdusi\r\n"
			+ "mdjcqbyp\r\n"
			+ "nmtsrvge\r\n"
			+ "bpeaxibi\r\n"
			+ "posabkfe\r\n"
			+ "pfwhphds\r\n"
			+ "jpycuzlh\r\n"
			+ "qujmxewu\r\n"
			+ "ehdiecja\r\n"
			+ "xmyiuqmb\r\n"
			+ "qvwitlyg\r\n"
			+ "desikusy\r\n"
			+ "pvaxwbkc\r\n"
			+ "elkduxal\r\n"
			+ "igmmotmo\r\n"
			+ "qkkvmpqz\r\n"
			+ "tikgdieo\r\n"
			+ "tcevjbrq\r\n"
			+ "poyymxnm\r\n"
			+ "ortrilot\r\n"
			+ "xmyrypdk\r\n"
			+ "rtsqwswz\r\n"
			+ "timjqxta\r\n"
			+ "kgoybzuw\r\n"
			+ "nduwmjcl\r\n"
			+ "kybovset\r\n"
			+ "prcuubkn\r\n"
			+ "kzvwiybb\r\n"
			+ "yrgwdwya\r\n"
			+ "ibfhvdxt\r\n"
			+ "ojzjsnxm\r\n"
			+ "albohvtm\r\n"
			+ "htemxqeo\r\n"
			+ "wgkyrfrx\r\n"
			+ "wopxooda\r\n"
			+ "cbuxmavy\r\n"
			+ "qlwakvjl\r\n"
			+ "ftjfsgpb\r\n"
			+ "useelmgi\r\n"
			+ "sfwqxtcn\r\n"
			+ "hjgsbkjr\r\n"
			+ "laprvoum\r\n"
			+ "xnxzfqww\r\n"
			+ "ijginkgo\r\n"
			+ "qimkncqq\r\n"
			+ "svaectoj\r\n"
			+ "gflciuue\r\n"
			+ "dbrrxdan\r\n"
			+ "gjrwzybe\r\n"
			+ "fobzvyfv\r\n"
			+ "xuevixmp\r\n"
			+ "phxzveoo\r\n"
			+ "lkkwygmo\r\n"
			+ "vogtawhe\r\n"
			+ "dnswsnzx\r\n"
			+ "ayvdixkr\r\n"
			+ "jkyvtkgj\r\n"
			+ "gwcieicd\r\n"
			+ "qepbzhlu\r\n"
			+ "vibcltdk\r\n"
			+ "zpofapqk\r\n"
			+ "cjfsdthn\r\n"
			+ "etnipjxn\r\n"
			+ "qjcycocp\r\n"
			+ "dsrggicy\r\n"
			+ "snuzhjbm\r\n"
			+ "ivbrvmjp\r\n"
			+ "nczrvkkl\r\n"
			+ "utzbrcwh\r\n"
			+ "argkcywe\r\n"
			+ "wkaybnsw\r\n"
			+ "wndmwodp\r\n"
			+ "mpltkkop\r\n"
			+ "nkcadyyq\r\n"
			+ "lbmkqzql\r\n"
			+ "fzbnprqv\r\n"
			+ "tkozordv\r\n"
			+ "trmnahav\r\n"
			+ "yiqelzvk\r\n"
			+ "ljjwickh\r\n"
			+ "htbzyahb\r\n"
			+ "fmdomnzg\r\n"
			+ "ndatgras\r\n"
			+ "npplxesj\r\n"
			+ "hwtyhtrk\r\n"
			+ "jayhqwor\r\n"
			+ "hthbwbma\r\n"
			+ "sugktxhy\r\n"
			+ "azrtyvpm\r\n"
			+ "slzlctjb\r\n"
			+ "hhlejgxq\r\n"
			+ "ffmhvvdk\r\n"
			+ "difyrfie\r\n"
			+ "awifonbf\r\n"
			+ "waexckwz\r\n"
			+ "weatwffs";
	
	@Override
	public String part1() {
		int wordLength = input.split("\r\n")[0].length();
		//keep array of hashmaps - one for each character position
		ArrayList<HashMap<Character,Integer>> frequencies = new ArrayList<HashMap<Character,Integer>>();
		for(int i = 0; i < wordLength; i++) {
			frequencies.add(new HashMap<Character,Integer>());
		}
		//iterate over lines
		for(String s : input.split("\r\n")) {
			//tally each character
			for(int i = 0; i < s.length(); i++) {
				frequencies.get(i).put(s.charAt(i), frequencies.get(i).getOrDefault(s.charAt(i), 0) + 1);
			}
		}
		//find most common of each position, append to string
		String plaintext = "";
		for(HashMap<Character,Integer> m : frequencies) {
			int bestCount = 0;
			char best = 0;
			for(char c : m.keySet()) {
				if(m.get(c) > bestCount) {
					bestCount = m.get(c);
					best = c;
				}
			}
			//append most common character
			plaintext += best;
		}
		return plaintext;
	}

	@Override
	public String part2() {
		int wordLength = input.split("\r\n")[0].length();
		//keep array of hashmaps - one for each character position
		ArrayList<HashMap<Character,Integer>> frequencies = new ArrayList<HashMap<Character,Integer>>();
		for(int i = 0; i < wordLength; i++) {
			frequencies.add(new HashMap<Character,Integer>());
		}
		//iterate over lines
		for(String s : input.split("\r\n")) {
			//tally each character
			for(int i = 0; i < s.length(); i++) {
				frequencies.get(i).put(s.charAt(i), frequencies.get(i).getOrDefault(s.charAt(i), 0) + 1);
			}
		}
		//part 2 - find least common of each position, append to string
		String plaintext = "";
		for(HashMap<Character,Integer> m : frequencies) {
			int bestCount = Integer.MAX_VALUE;
			char best = 0;
			for(char c : m.keySet()) {
				if(m.get(c) < bestCount) {
					bestCount = m.get(c);
					best = c;
				}
			}
			//append least common character
			plaintext += best;
		}
		return plaintext;
	}

	public static void main(String[] args) {
		DayRunner.run(new Day06());
	}

}
