package advent.aoc2020;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;

import advent.utilities.general.DayRunner;
import advent.utilities.general.IDay;

public class Day08 implements IDay {

	String input = "jmp +149\r\n"
			+ "acc -11\r\n"
			+ "nop +95\r\n"
			+ "acc -6\r\n"
			+ "jmp +196\r\n"
			+ "acc +2\r\n"
			+ "acc -6\r\n"
			+ "acc +38\r\n"
			+ "acc +18\r\n"
			+ "jmp +246\r\n"
			+ "acc +43\r\n"
			+ "acc +37\r\n"
			+ "acc -1\r\n"
			+ "jmp +390\r\n"
			+ "acc +32\r\n"
			+ "acc -15\r\n"
			+ "jmp +487\r\n"
			+ "jmp +382\r\n"
			+ "jmp +71\r\n"
			+ "jmp +331\r\n"
			+ "acc -3\r\n"
			+ "acc -12\r\n"
			+ "acc +4\r\n"
			+ "jmp +417\r\n"
			+ "acc +30\r\n"
			+ "acc +20\r\n"
			+ "jmp +410\r\n"
			+ "acc +22\r\n"
			+ "acc +25\r\n"
			+ "acc +19\r\n"
			+ "acc +5\r\n"
			+ "jmp +405\r\n"
			+ "acc +15\r\n"
			+ "acc +33\r\n"
			+ "acc +7\r\n"
			+ "acc -18\r\n"
			+ "jmp +463\r\n"
			+ "acc +25\r\n"
			+ "acc +8\r\n"
			+ "acc +1\r\n"
			+ "jmp +64\r\n"
			+ "jmp +1\r\n"
			+ "jmp +562\r\n"
			+ "jmp +4\r\n"
			+ "acc +21\r\n"
			+ "acc +12\r\n"
			+ "jmp +467\r\n"
			+ "nop +197\r\n"
			+ "acc +32\r\n"
			+ "jmp +7\r\n"
			+ "acc +2\r\n"
			+ "jmp +352\r\n"
			+ "acc +15\r\n"
			+ "jmp +289\r\n"
			+ "acc +39\r\n"
			+ "jmp +448\r\n"
			+ "jmp +227\r\n"
			+ "acc +17\r\n"
			+ "acc +4\r\n"
			+ "jmp +326\r\n"
			+ "acc -1\r\n"
			+ "nop +167\r\n"
			+ "acc +30\r\n"
			+ "nop +471\r\n"
			+ "jmp +101\r\n"
			+ "acc +45\r\n"
			+ "nop +276\r\n"
			+ "acc +12\r\n"
			+ "jmp +215\r\n"
			+ "nop +80\r\n"
			+ "acc +23\r\n"
			+ "acc +31\r\n"
			+ "jmp +104\r\n"
			+ "acc +39\r\n"
			+ "acc +15\r\n"
			+ "jmp +40\r\n"
			+ "nop +433\r\n"
			+ "acc +21\r\n"
			+ "acc +22\r\n"
			+ "acc +37\r\n"
			+ "jmp +421\r\n"
			+ "acc +14\r\n"
			+ "jmp -30\r\n"
			+ "acc +42\r\n"
			+ "acc +38\r\n"
			+ "jmp +203\r\n"
			+ "acc -8\r\n"
			+ "acc +27\r\n"
			+ "jmp +102\r\n"
			+ "acc -5\r\n"
			+ "acc +0\r\n"
			+ "acc +18\r\n"
			+ "acc +26\r\n"
			+ "jmp +212\r\n"
			+ "acc +25\r\n"
			+ "acc +18\r\n"
			+ "jmp +209\r\n"
			+ "acc +18\r\n"
			+ "acc +44\r\n"
			+ "acc +47\r\n"
			+ "nop -40\r\n"
			+ "jmp +372\r\n"
			+ "acc +29\r\n"
			+ "jmp +384\r\n"
			+ "acc +39\r\n"
			+ "acc -11\r\n"
			+ "acc +43\r\n"
			+ "jmp +406\r\n"
			+ "acc +2\r\n"
			+ "nop +439\r\n"
			+ "jmp +343\r\n"
			+ "acc +29\r\n"
			+ "acc +18\r\n"
			+ "jmp +457\r\n"
			+ "jmp -31\r\n"
			+ "jmp +146\r\n"
			+ "acc +12\r\n"
			+ "acc +26\r\n"
			+ "nop +98\r\n"
			+ "jmp +125\r\n"
			+ "acc +6\r\n"
			+ "acc +35\r\n"
			+ "acc +48\r\n"
			+ "acc +44\r\n"
			+ "jmp +497\r\n"
			+ "acc +17\r\n"
			+ "acc -8\r\n"
			+ "jmp +223\r\n"
			+ "acc +47\r\n"
			+ "jmp +405\r\n"
			+ "jmp +212\r\n"
			+ "jmp +317\r\n"
			+ "acc -13\r\n"
			+ "acc -6\r\n"
			+ "jmp +94\r\n"
			+ "acc +47\r\n"
			+ "acc +50\r\n"
			+ "acc -16\r\n"
			+ "acc +38\r\n"
			+ "jmp +290\r\n"
			+ "jmp +383\r\n"
			+ "nop -44\r\n"
			+ "acc +38\r\n"
			+ "nop +418\r\n"
			+ "acc +42\r\n"
			+ "jmp +233\r\n"
			+ "nop -94\r\n"
			+ "acc +46\r\n"
			+ "jmp +413\r\n"
			+ "acc +10\r\n"
			+ "acc -6\r\n"
			+ "jmp +410\r\n"
			+ "acc +30\r\n"
			+ "jmp -93\r\n"
			+ "acc -13\r\n"
			+ "jmp +6\r\n"
			+ "acc -16\r\n"
			+ "acc +18\r\n"
			+ "nop +403\r\n"
			+ "acc +0\r\n"
			+ "jmp +68\r\n"
			+ "acc +45\r\n"
			+ "jmp +302\r\n"
			+ "acc +5\r\n"
			+ "jmp +26\r\n"
			+ "acc -5\r\n"
			+ "acc +49\r\n"
			+ "jmp +412\r\n"
			+ "acc +3\r\n"
			+ "acc +14\r\n"
			+ "jmp +278\r\n"
			+ "acc +6\r\n"
			+ "acc +4\r\n"
			+ "jmp -58\r\n"
			+ "acc +14\r\n"
			+ "jmp -60\r\n"
			+ "acc -12\r\n"
			+ "acc +23\r\n"
			+ "jmp +225\r\n"
			+ "acc +9\r\n"
			+ "acc +17\r\n"
			+ "acc -10\r\n"
			+ "acc -13\r\n"
			+ "jmp +216\r\n"
			+ "acc -8\r\n"
			+ "nop +363\r\n"
			+ "jmp +84\r\n"
			+ "nop +300\r\n"
			+ "acc -15\r\n"
			+ "jmp +415\r\n"
			+ "acc +17\r\n"
			+ "acc -11\r\n"
			+ "nop +96\r\n"
			+ "jmp +377\r\n"
			+ "nop +259\r\n"
			+ "acc +4\r\n"
			+ "jmp +327\r\n"
			+ "acc +0\r\n"
			+ "jmp +149\r\n"
			+ "jmp +12\r\n"
			+ "acc +23\r\n"
			+ "acc +43\r\n"
			+ "acc +2\r\n"
			+ "jmp +1\r\n"
			+ "jmp +400\r\n"
			+ "acc +24\r\n"
			+ "jmp +114\r\n"
			+ "acc +3\r\n"
			+ "acc -13\r\n"
			+ "jmp +149\r\n"
			+ "jmp +100\r\n"
			+ "jmp +1\r\n"
			+ "jmp +157\r\n"
			+ "acc +23\r\n"
			+ "acc -15\r\n"
			+ "jmp -139\r\n"
			+ "nop -85\r\n"
			+ "jmp +201\r\n"
			+ "acc -2\r\n"
			+ "acc +39\r\n"
			+ "acc +30\r\n"
			+ "nop -93\r\n"
			+ "jmp -11\r\n"
			+ "acc +46\r\n"
			+ "jmp +285\r\n"
			+ "jmp +1\r\n"
			+ "acc +41\r\n"
			+ "jmp +115\r\n"
			+ "acc +48\r\n"
			+ "acc -12\r\n"
			+ "acc -17\r\n"
			+ "jmp -15\r\n"
			+ "nop +82\r\n"
			+ "acc +25\r\n"
			+ "jmp -151\r\n"
			+ "acc +20\r\n"
			+ "acc -14\r\n"
			+ "acc +9\r\n"
			+ "acc -9\r\n"
			+ "jmp +284\r\n"
			+ "acc +27\r\n"
			+ "acc +38\r\n"
			+ "acc +50\r\n"
			+ "jmp +145\r\n"
			+ "nop +279\r\n"
			+ "jmp -55\r\n"
			+ "nop +245\r\n"
			+ "jmp +254\r\n"
			+ "acc +4\r\n"
			+ "jmp +368\r\n"
			+ "nop -119\r\n"
			+ "acc -11\r\n"
			+ "acc +16\r\n"
			+ "acc +19\r\n"
			+ "jmp -54\r\n"
			+ "nop -186\r\n"
			+ "nop -187\r\n"
			+ "acc +9\r\n"
			+ "acc +44\r\n"
			+ "jmp -222\r\n"
			+ "jmp +253\r\n"
			+ "nop -234\r\n"
			+ "acc +33\r\n"
			+ "acc +35\r\n"
			+ "acc -17\r\n"
			+ "jmp +11\r\n"
			+ "acc +2\r\n"
			+ "acc +41\r\n"
			+ "acc +47\r\n"
			+ "jmp +310\r\n"
			+ "acc +0\r\n"
			+ "acc -8\r\n"
			+ "acc +1\r\n"
			+ "jmp +55\r\n"
			+ "acc -1\r\n"
			+ "jmp -257\r\n"
			+ "acc +7\r\n"
			+ "acc +44\r\n"
			+ "nop +253\r\n"
			+ "acc +41\r\n"
			+ "jmp +302\r\n"
			+ "acc +16\r\n"
			+ "jmp -185\r\n"
			+ "jmp +140\r\n"
			+ "jmp +1\r\n"
			+ "nop +3\r\n"
			+ "acc +35\r\n"
			+ "jmp -267\r\n"
			+ "acc +6\r\n"
			+ "jmp -269\r\n"
			+ "jmp +211\r\n"
			+ "acc +30\r\n"
			+ "acc +14\r\n"
			+ "acc +16\r\n"
			+ "acc +41\r\n"
			+ "jmp -47\r\n"
			+ "jmp -192\r\n"
			+ "nop -21\r\n"
			+ "acc -1\r\n"
			+ "jmp +192\r\n"
			+ "acc -6\r\n"
			+ "acc +15\r\n"
			+ "acc +3\r\n"
			+ "nop -247\r\n"
			+ "jmp -88\r\n"
			+ "jmp +164\r\n"
			+ "acc +47\r\n"
			+ "nop +43\r\n"
			+ "acc +40\r\n"
			+ "jmp +151\r\n"
			+ "jmp +85\r\n"
			+ "jmp +1\r\n"
			+ "acc +40\r\n"
			+ "jmp -257\r\n"
			+ "acc +13\r\n"
			+ "acc +13\r\n"
			+ "jmp -256\r\n"
			+ "acc +25\r\n"
			+ "acc +39\r\n"
			+ "jmp +260\r\n"
			+ "acc +13\r\n"
			+ "acc -18\r\n"
			+ "acc -19\r\n"
			+ "acc -14\r\n"
			+ "jmp -10\r\n"
			+ "acc -16\r\n"
			+ "acc +9\r\n"
			+ "jmp -199\r\n"
			+ "nop +185\r\n"
			+ "acc +38\r\n"
			+ "jmp -261\r\n"
			+ "nop +200\r\n"
			+ "acc -18\r\n"
			+ "nop +115\r\n"
			+ "acc +36\r\n"
			+ "jmp -259\r\n"
			+ "acc +47\r\n"
			+ "acc -2\r\n"
			+ "acc +9\r\n"
			+ "jmp -139\r\n"
			+ "nop -117\r\n"
			+ "jmp -13\r\n"
			+ "jmp +1\r\n"
			+ "jmp +247\r\n"
			+ "acc +19\r\n"
			+ "acc +49\r\n"
			+ "jmp +177\r\n"
			+ "acc -1\r\n"
			+ "jmp +249\r\n"
			+ "jmp -218\r\n"
			+ "acc +12\r\n"
			+ "acc +33\r\n"
			+ "jmp +108\r\n"
			+ "jmp -48\r\n"
			+ "nop -205\r\n"
			+ "acc +32\r\n"
			+ "jmp -159\r\n"
			+ "jmp -129\r\n"
			+ "acc +32\r\n"
			+ "jmp +1\r\n"
			+ "jmp +249\r\n"
			+ "nop +75\r\n"
			+ "acc +17\r\n"
			+ "acc -16\r\n"
			+ "jmp +253\r\n"
			+ "acc -9\r\n"
			+ "jmp -12\r\n"
			+ "acc +15\r\n"
			+ "jmp -14\r\n"
			+ "acc +13\r\n"
			+ "acc -8\r\n"
			+ "nop -13\r\n"
			+ "jmp +27\r\n"
			+ "nop -336\r\n"
			+ "acc +33\r\n"
			+ "acc +10\r\n"
			+ "acc -1\r\n"
			+ "jmp -350\r\n"
			+ "nop -134\r\n"
			+ "acc -11\r\n"
			+ "jmp +5\r\n"
			+ "acc +10\r\n"
			+ "acc +13\r\n"
			+ "acc +13\r\n"
			+ "jmp -249\r\n"
			+ "acc +8\r\n"
			+ "jmp -215\r\n"
			+ "jmp +49\r\n"
			+ "acc +35\r\n"
			+ "acc +28\r\n"
			+ "jmp -54\r\n"
			+ "acc +14\r\n"
			+ "nop -264\r\n"
			+ "jmp +1\r\n"
			+ "jmp -166\r\n"
			+ "jmp -291\r\n"
			+ "acc +9\r\n"
			+ "acc +43\r\n"
			+ "jmp -301\r\n"
			+ "nop +149\r\n"
			+ "acc -9\r\n"
			+ "jmp -81\r\n"
			+ "jmp -287\r\n"
			+ "acc +9\r\n"
			+ "acc +35\r\n"
			+ "acc -12\r\n"
			+ "jmp -295\r\n"
			+ "acc +46\r\n"
			+ "jmp -394\r\n"
			+ "acc +29\r\n"
			+ "acc +19\r\n"
			+ "acc +9\r\n"
			+ "jmp -58\r\n"
			+ "acc +7\r\n"
			+ "acc +32\r\n"
			+ "nop -261\r\n"
			+ "acc +44\r\n"
			+ "jmp -365\r\n"
			+ "jmp +1\r\n"
			+ "jmp +120\r\n"
			+ "acc +37\r\n"
			+ "nop -177\r\n"
			+ "jmp +101\r\n"
			+ "acc +42\r\n"
			+ "acc +13\r\n"
			+ "acc +36\r\n"
			+ "jmp -343\r\n"
			+ "acc +45\r\n"
			+ "jmp -408\r\n"
			+ "acc +23\r\n"
			+ "acc +0\r\n"
			+ "jmp -66\r\n"
			+ "jmp +1\r\n"
			+ "acc +34\r\n"
			+ "acc +19\r\n"
			+ "jmp +104\r\n"
			+ "jmp +1\r\n"
			+ "acc +36\r\n"
			+ "jmp -141\r\n"
			+ "jmp -44\r\n"
			+ "acc +9\r\n"
			+ "acc +30\r\n"
			+ "acc +18\r\n"
			+ "acc +0\r\n"
			+ "jmp -303\r\n"
			+ "jmp +1\r\n"
			+ "acc +12\r\n"
			+ "jmp +66\r\n"
			+ "acc +0\r\n"
			+ "jmp +82\r\n"
			+ "acc +43\r\n"
			+ "acc +18\r\n"
			+ "jmp +49\r\n"
			+ "acc -16\r\n"
			+ "acc -3\r\n"
			+ "acc +0\r\n"
			+ "jmp -249\r\n"
			+ "acc -2\r\n"
			+ "nop +81\r\n"
			+ "jmp +40\r\n"
			+ "jmp +94\r\n"
			+ "acc -16\r\n"
			+ "acc +1\r\n"
			+ "jmp -445\r\n"
			+ "jmp +1\r\n"
			+ "acc +22\r\n"
			+ "jmp -130\r\n"
			+ "acc +44\r\n"
			+ "jmp -73\r\n"
			+ "acc +3\r\n"
			+ "acc +5\r\n"
			+ "jmp -121\r\n"
			+ "jmp -352\r\n"
			+ "jmp -163\r\n"
			+ "acc +15\r\n"
			+ "acc +47\r\n"
			+ "nop +141\r\n"
			+ "jmp +140\r\n"
			+ "acc -18\r\n"
			+ "nop -289\r\n"
			+ "acc +16\r\n"
			+ "jmp -476\r\n"
			+ "acc -19\r\n"
			+ "nop +134\r\n"
			+ "acc -10\r\n"
			+ "acc +37\r\n"
			+ "jmp -13\r\n"
			+ "jmp -359\r\n"
			+ "acc +32\r\n"
			+ "acc +14\r\n"
			+ "jmp -306\r\n"
			+ "acc +25\r\n"
			+ "acc +30\r\n"
			+ "jmp -441\r\n"
			+ "acc +44\r\n"
			+ "acc +14\r\n"
			+ "acc +12\r\n"
			+ "acc +19\r\n"
			+ "jmp -387\r\n"
			+ "jmp -12\r\n"
			+ "jmp -180\r\n"
			+ "jmp -113\r\n"
			+ "jmp -29\r\n"
			+ "acc +34\r\n"
			+ "acc -13\r\n"
			+ "acc -12\r\n"
			+ "nop +73\r\n"
			+ "jmp -263\r\n"
			+ "jmp -373\r\n"
			+ "jmp -360\r\n"
			+ "acc +38\r\n"
			+ "nop -123\r\n"
			+ "jmp -176\r\n"
			+ "nop -155\r\n"
			+ "acc -11\r\n"
			+ "acc +32\r\n"
			+ "nop +54\r\n"
			+ "jmp -461\r\n"
			+ "acc +31\r\n"
			+ "acc +10\r\n"
			+ "acc -7\r\n"
			+ "acc -19\r\n"
			+ "jmp -212\r\n"
			+ "acc +41\r\n"
			+ "acc +4\r\n"
			+ "nop -2\r\n"
			+ "jmp -483\r\n"
			+ "acc +16\r\n"
			+ "acc +42\r\n"
			+ "acc -15\r\n"
			+ "jmp -286\r\n"
			+ "jmp -122\r\n"
			+ "acc -4\r\n"
			+ "jmp -436\r\n"
			+ "acc +27\r\n"
			+ "jmp -508\r\n"
			+ "acc +38\r\n"
			+ "nop -309\r\n"
			+ "jmp +10\r\n"
			+ "acc +31\r\n"
			+ "acc +18\r\n"
			+ "acc +5\r\n"
			+ "jmp -119\r\n"
			+ "acc +8\r\n"
			+ "acc -7\r\n"
			+ "acc -16\r\n"
			+ "acc +18\r\n"
			+ "jmp -416\r\n"
			+ "acc -15\r\n"
			+ "acc +1\r\n"
			+ "acc +30\r\n"
			+ "acc +8\r\n"
			+ "jmp -476\r\n"
			+ "jmp -298\r\n"
			+ "acc +29\r\n"
			+ "acc +24\r\n"
			+ "acc -9\r\n"
			+ "acc +35\r\n"
			+ "jmp -438\r\n"
			+ "nop -5\r\n"
			+ "jmp -100\r\n"
			+ "acc +5\r\n"
			+ "acc +3\r\n"
			+ "acc +5\r\n"
			+ "acc -4\r\n"
			+ "jmp +14\r\n"
			+ "acc +43\r\n"
			+ "acc +3\r\n"
			+ "acc +40\r\n"
			+ "jmp -517\r\n"
			+ "acc +10\r\n"
			+ "acc +35\r\n"
			+ "acc +38\r\n"
			+ "jmp -120\r\n"
			+ "acc +1\r\n"
			+ "acc -18\r\n"
			+ "acc +0\r\n"
			+ "acc +42\r\n"
			+ "jmp -69\r\n"
			+ "jmp -101\r\n"
			+ "acc +1\r\n"
			+ "jmp -271\r\n"
			+ "acc +37\r\n"
			+ "acc +17\r\n"
			+ "jmp +1\r\n"
			+ "jmp -401\r\n"
			+ "acc +1\r\n"
			+ "acc +3\r\n"
			+ "acc -8\r\n"
			+ "jmp -392\r\n"
			+ "nop -99\r\n"
			+ "acc +2\r\n"
			+ "jmp -301\r\n"
			+ "acc +10\r\n"
			+ "acc +32\r\n"
			+ "acc +3\r\n"
			+ "jmp -286\r\n"
			+ "jmp +1\r\n"
			+ "jmp -444\r\n"
			+ "nop -364\r\n"
			+ "acc +46\r\n"
			+ "acc +30\r\n"
			+ "acc -2\r\n"
			+ "jmp -13\r\n"
			+ "nop -65\r\n"
			+ "acc +22\r\n"
			+ "jmp -292\r\n"
			+ "acc -13\r\n"
			+ "jmp -480\r\n"
			+ "acc +4\r\n"
			+ "acc -8\r\n"
			+ "nop -500\r\n"
			+ "jmp -113\r\n"
			+ "acc -16\r\n"
			+ "acc +40\r\n"
			+ "acc -18\r\n"
			+ "jmp -125\r\n"
			+ "jmp -482\r\n"
			+ "acc +28\r\n"
			+ "acc -5\r\n"
			+ "jmp -471\r\n"
			+ "acc +33\r\n"
			+ "acc +49\r\n"
			+ "acc +21\r\n"
			+ "acc +9\r\n"
			+ "jmp +1";
	
	@Override
	public String part1() {
		ArrayList<String> program = new ArrayList<String>(Arrays.asList(input.split("\r\n")));
		int pointer = 0;
		int acc = 0;
		HashSet<Integer> visited = new HashSet<Integer>();
		visited.add(0);
		do {
			String[] parts = program.get(pointer).split(" ");
			switch(parts[0]) {
			case "nop":
				pointer++;
				break;
			case "acc":
				acc += Integer.parseInt(parts[1]);
				pointer++;
				break;
			case "jmp":
				pointer += Integer.parseInt(parts[1]);
				break;
			}
		} while(visited.add(pointer));
		return Integer.toString(acc);
	}

	@Override
	public String part2() {
		ArrayList<String> program = new ArrayList<String>(Arrays.asList(input.split("\r\n")));
		swap:
		//iterate through every potential instruction index to see which one makes the program function properly
		for(int swap = 0; swap < program.size(); swap++) {
			int pointer = 0;
			int acc = 0;
			HashSet<Integer> visited = new HashSet<Integer>();
			visited.add(0);
			while(pointer < program.size()) {
				String[] parts = program.get(pointer).split(" ");
				if(pointer == swap) {
					if(parts[0].equals("nop")) {
						parts[0] = "jmp";
					} else if (parts[0].equals("jmp")) {
						parts[0] = "nop";
					}
				}
				switch(parts[0]) {
				case "nop":
					pointer++;
					break;
				case "acc":
					acc += Integer.parseInt(parts[1]);
					pointer++;
					break;
				case "jmp":
					pointer += Integer.parseInt(parts[1]);
					break;
				}
				if(!visited.add(pointer)) {
					continue swap;
				}
			}
			return Integer.toString(acc);
		}
		return null;
	}

	public static void main(String[] args) {
		DayRunner.run(new Day08());
	}

}
