package advent.aoc2020;

import java.util.HashMap;
import java.util.HashSet;

import advent.utilities.general.DayRunner;
import advent.utilities.general.IDay;

public class Day07 implements IDay {

	String input = "plaid fuchsia bags contain 5 light violet bags, 1 light yellow bag.\r\n"
			+ "striped aqua bags contain 2 striped teal bags.\r\n"
			+ "clear coral bags contain 2 plaid green bags, 5 mirrored gold bags.\r\n"
			+ "dull tan bags contain 4 faded blue bags, 3 faded olive bags, 5 dull salmon bags.\r\n"
			+ "plaid green bags contain 3 faded green bags.\r\n"
			+ "light tomato bags contain 1 drab chartreuse bag, 1 dotted tomato bag, 3 striped red bags, 2 vibrant violet bags.\r\n"
			+ "dim tomato bags contain 4 striped gold bags, 5 bright lavender bags, 1 pale beige bag, 4 pale tan bags.\r\n"
			+ "vibrant green bags contain 4 faded teal bags.\r\n"
			+ "shiny crimson bags contain 2 dull green bags.\r\n"
			+ "vibrant black bags contain 5 dark beige bags, 3 dark bronze bags.\r\n"
			+ "light tan bags contain 1 striped tomato bag.\r\n"
			+ "vibrant teal bags contain 1 shiny silver bag.\r\n"
			+ "pale chartreuse bags contain 2 dotted plum bags.\r\n"
			+ "plaid coral bags contain 2 pale green bags, 2 faded tomato bags, 2 dark salmon bags, 1 vibrant magenta bag.\r\n"
			+ "dull gray bags contain 1 dark tan bag, 3 dotted tan bags.\r\n"
			+ "muted gray bags contain 5 bright indigo bags, 5 dotted purple bags.\r\n"
			+ "vibrant red bags contain 4 bright tomato bags, 4 shiny orange bags.\r\n"
			+ "faded tan bags contain 1 dull crimson bag, 5 faded red bags.\r\n"
			+ "pale magenta bags contain 3 posh chartreuse bags, 4 vibrant purple bags.\r\n"
			+ "shiny gray bags contain 2 wavy purple bags.\r\n"
			+ "light crimson bags contain 5 clear teal bags.\r\n"
			+ "striped turquoise bags contain 3 pale tomato bags, 2 posh teal bags.\r\n"
			+ "striped purple bags contain 4 dark silver bags, 4 vibrant gray bags, 2 dim bronze bags, 2 clear aqua bags.\r\n"
			+ "muted magenta bags contain 4 striped tomato bags.\r\n"
			+ "light teal bags contain 2 faded brown bags, 2 posh purple bags, 1 faded olive bag.\r\n"
			+ "clear cyan bags contain 1 clear coral bag, 5 clear aqua bags.\r\n"
			+ "dull cyan bags contain 5 wavy crimson bags, 1 pale orange bag.\r\n"
			+ "shiny tan bags contain 2 bright red bags, 4 plaid cyan bags.\r\n"
			+ "light brown bags contain 3 dim yellow bags, 4 dull orange bags, 1 vibrant yellow bag.\r\n"
			+ "pale tan bags contain 2 striped orange bags, 5 dull plum bags.\r\n"
			+ "wavy salmon bags contain 2 dark blue bags, 5 dim plum bags.\r\n"
			+ "mirrored cyan bags contain 2 plaid turquoise bags, 5 dull plum bags, 3 muted indigo bags, 2 plaid white bags.\r\n"
			+ "dark aqua bags contain 3 bright red bags, 2 wavy purple bags, 2 plaid tan bags.\r\n"
			+ "wavy purple bags contain 5 wavy brown bags.\r\n"
			+ "clear magenta bags contain 4 muted green bags, 3 dull cyan bags, 4 striped teal bags, 2 faded blue bags.\r\n"
			+ "bright red bags contain 5 vibrant tomato bags, 2 dull orange bags.\r\n"
			+ "pale purple bags contain 3 plaid turquoise bags, 4 light tan bags, 1 faded black bag, 5 light yellow bags.\r\n"
			+ "bright orange bags contain 1 mirrored orange bag, 2 faded bronze bags, 1 wavy turquoise bag, 1 bright yellow bag.\r\n"
			+ "faded lavender bags contain 1 plaid brown bag.\r\n"
			+ "dark salmon bags contain 3 dotted crimson bags, 1 posh bronze bag.\r\n"
			+ "mirrored coral bags contain 3 dark red bags, 1 dull fuchsia bag, 2 drab magenta bags, 4 dull indigo bags.\r\n"
			+ "clear black bags contain 5 mirrored salmon bags, 3 drab gold bags, 3 muted fuchsia bags.\r\n"
			+ "faded fuchsia bags contain 1 shiny silver bag, 2 posh orange bags, 5 plaid bronze bags.\r\n"
			+ "dotted red bags contain 4 faded yellow bags, 5 dull brown bags, 3 clear red bags.\r\n"
			+ "light purple bags contain 2 plaid magenta bags, 3 vibrant coral bags, 2 wavy black bags.\r\n"
			+ "faded beige bags contain no other bags.\r\n"
			+ "dull fuchsia bags contain 3 dim lavender bags, 1 dull aqua bag, 2 pale fuchsia bags.\r\n"
			+ "wavy olive bags contain 5 dotted cyan bags, 1 dull lime bag.\r\n"
			+ "dim teal bags contain 1 dull green bag.\r\n"
			+ "dull orange bags contain 5 striped tomato bags, 5 drab blue bags, 5 faded blue bags, 2 pale brown bags.\r\n"
			+ "muted brown bags contain 3 dotted orange bags, 1 bright tan bag.\r\n"
			+ "vibrant coral bags contain 2 wavy turquoise bags.\r\n"
			+ "clear aqua bags contain 5 posh bronze bags, 5 dim orange bags, 5 posh chartreuse bags.\r\n"
			+ "dull plum bags contain 4 drab tan bags.\r\n"
			+ "wavy tomato bags contain 4 wavy cyan bags, 1 bright silver bag, 3 dotted gray bags, 1 dark tomato bag.\r\n"
			+ "shiny fuchsia bags contain 1 dotted silver bag, 5 dull lime bags, 3 drab teal bags.\r\n"
			+ "pale fuchsia bags contain 3 pale beige bags.\r\n"
			+ "plaid plum bags contain 4 dotted plum bags, 1 mirrored brown bag, 3 dim yellow bags, 2 vibrant bronze bags.\r\n"
			+ "posh green bags contain 5 plaid indigo bags, 1 wavy red bag, 5 dim indigo bags, 4 wavy indigo bags.\r\n"
			+ "muted aqua bags contain 3 bright tan bags, 3 dull yellow bags, 1 faded blue bag.\r\n"
			+ "mirrored white bags contain 5 dark coral bags, 1 plaid red bag, 4 dull violet bags, 5 clear gray bags.\r\n"
			+ "dotted aqua bags contain 4 drab aqua bags, 3 faded tomato bags.\r\n"
			+ "bright indigo bags contain 4 faded tan bags, 3 clear turquoise bags, 1 plaid indigo bag, 4 bright gray bags.\r\n"
			+ "posh silver bags contain 5 striped red bags, 3 faded blue bags, 3 dim plum bags, 3 vibrant beige bags.\r\n"
			+ "bright olive bags contain 3 dull silver bags, 5 drab tomato bags.\r\n"
			+ "muted beige bags contain 1 drab crimson bag.\r\n"
			+ "shiny beige bags contain 3 clear blue bags.\r\n"
			+ "wavy brown bags contain 2 striped coral bags, 2 light purple bags.\r\n"
			+ "wavy black bags contain 4 faded beige bags, 2 striped red bags, 2 pale brown bags, 3 dull yellow bags.\r\n"
			+ "faded salmon bags contain 1 light indigo bag, 5 plaid cyan bags, 2 pale salmon bags.\r\n"
			+ "dark gold bags contain 1 mirrored plum bag, 2 dark tomato bags, 5 dull green bags, 2 light lime bags.\r\n"
			+ "mirrored lavender bags contain 5 muted brown bags, 1 shiny blue bag, 5 dull blue bags, 3 wavy indigo bags.\r\n"
			+ "wavy beige bags contain 3 mirrored purple bags, 3 posh yellow bags, 4 plaid green bags.\r\n"
			+ "striped fuchsia bags contain 5 drab bronze bags, 4 posh tomato bags, 1 drab maroon bag, 1 dim beige bag.\r\n"
			+ "faded blue bags contain 1 striped tomato bag, 3 dark olive bags, 2 drab tan bags.\r\n"
			+ "drab gray bags contain 1 posh teal bag.\r\n"
			+ "dim cyan bags contain 4 dark fuchsia bags, 3 wavy maroon bags, 5 posh silver bags, 4 posh chartreuse bags.\r\n"
			+ "dotted purple bags contain 3 wavy white bags.\r\n"
			+ "shiny brown bags contain 5 light silver bags, 4 light turquoise bags, 4 posh bronze bags.\r\n"
			+ "vibrant tomato bags contain 3 dotted cyan bags, 3 posh teal bags, 1 clear magenta bag, 5 dull lime bags.\r\n"
			+ "dark bronze bags contain 2 vibrant maroon bags, 2 mirrored olive bags.\r\n"
			+ "wavy silver bags contain 4 striped magenta bags, 3 dim fuchsia bags.\r\n"
			+ "striped yellow bags contain 5 faded black bags, 5 light beige bags, 1 vibrant beige bag, 2 mirrored beige bags.\r\n"
			+ "faded chartreuse bags contain 4 clear gray bags, 5 dotted gray bags.\r\n"
			+ "faded tomato bags contain 5 faded gray bags, 4 faded fuchsia bags, 3 drab teal bags.\r\n"
			+ "dull gold bags contain 1 dark plum bag, 4 striped black bags.\r\n"
			+ "muted turquoise bags contain 1 mirrored bronze bag, 5 shiny aqua bags, 1 clear plum bag.\r\n"
			+ "dotted lime bags contain 1 dark black bag, 5 pale brown bags.\r\n"
			+ "vibrant violet bags contain 5 faded lime bags, 1 pale fuchsia bag, 5 dull plum bags.\r\n"
			+ "faded black bags contain 2 striped teal bags, 5 faded beige bags, 4 wavy black bags, 1 striped lavender bag.\r\n"
			+ "drab teal bags contain 1 clear gold bag, 4 muted crimson bags, 1 light teal bag.\r\n"
			+ "dull purple bags contain 1 posh crimson bag, 2 clear blue bags.\r\n"
			+ "dotted teal bags contain 2 dark tan bags.\r\n"
			+ "dark red bags contain 3 dotted cyan bags, 3 posh red bags, 2 bright red bags, 3 faded magenta bags.\r\n"
			+ "light black bags contain 5 dull yellow bags.\r\n"
			+ "light salmon bags contain 3 faded beige bags.\r\n"
			+ "dull brown bags contain 1 light indigo bag, 4 mirrored yellow bags, 5 faded silver bags.\r\n"
			+ "dark black bags contain 5 dull yellow bags, 3 dull lime bags, 5 posh aqua bags.\r\n"
			+ "faded crimson bags contain 3 light fuchsia bags, 5 muted chartreuse bags.\r\n"
			+ "drab yellow bags contain 5 drab indigo bags, 2 shiny brown bags, 4 muted lime bags.\r\n"
			+ "muted tomato bags contain 3 posh salmon bags, 2 plaid indigo bags, 5 striped aqua bags.\r\n"
			+ "pale teal bags contain 2 muted red bags, 5 mirrored brown bags, 4 mirrored tan bags.\r\n"
			+ "posh violet bags contain 4 posh tomato bags.\r\n"
			+ "dim plum bags contain 1 faded magenta bag, 5 drab silver bags, 1 pale brown bag.\r\n"
			+ "light fuchsia bags contain 2 dotted silver bags, 3 dotted lavender bags, 3 shiny gold bags, 5 clear magenta bags.\r\n"
			+ "vibrant orange bags contain 5 shiny blue bags, 5 dull maroon bags.\r\n"
			+ "shiny white bags contain 5 mirrored yellow bags, 2 pale fuchsia bags, 4 shiny turquoise bags.\r\n"
			+ "drab green bags contain 1 mirrored lavender bag, 3 posh tan bags.\r\n"
			+ "faded silver bags contain 5 vibrant coral bags, 3 striped lavender bags, 4 dotted cyan bags, 5 plaid turquoise bags.\r\n"
			+ "faded gold bags contain 4 faded magenta bags.\r\n"
			+ "dark coral bags contain 3 light maroon bags, 1 drab silver bag.\r\n"
			+ "striped olive bags contain 4 dotted maroon bags, 3 wavy brown bags, 1 wavy crimson bag, 5 shiny silver bags.\r\n"
			+ "wavy lavender bags contain 3 mirrored yellow bags, 5 shiny crimson bags, 4 dark indigo bags.\r\n"
			+ "bright fuchsia bags contain 2 vibrant green bags, 5 drab blue bags.\r\n"
			+ "dotted turquoise bags contain 3 striped red bags.\r\n"
			+ "drab black bags contain 1 faded tan bag.\r\n"
			+ "pale silver bags contain 1 faded yellow bag, 1 drab tan bag, 5 muted salmon bags, 3 shiny white bags.\r\n"
			+ "striped magenta bags contain 4 dark turquoise bags, 4 shiny blue bags, 3 shiny crimson bags.\r\n"
			+ "dotted beige bags contain 2 mirrored black bags, 2 faded brown bags, 1 bright red bag, 2 clear coral bags.\r\n"
			+ "clear maroon bags contain 5 bright bronze bags.\r\n"
			+ "shiny olive bags contain 2 dull blue bags.\r\n"
			+ "pale violet bags contain 1 light purple bag, 1 pale tomato bag, 4 plaid aqua bags, 4 light magenta bags.\r\n"
			+ "dotted white bags contain 3 bright purple bags, 4 dull orange bags, 2 plaid salmon bags.\r\n"
			+ "plaid blue bags contain 5 faded blue bags, 4 muted green bags, 4 bright bronze bags.\r\n"
			+ "mirrored lime bags contain 1 faded green bag, 4 striped black bags, 1 mirrored purple bag.\r\n"
			+ "wavy violet bags contain 1 muted bronze bag.\r\n"
			+ "light silver bags contain 2 dull cyan bags, 1 drab tan bag.\r\n"
			+ "dark tomato bags contain 1 vibrant tomato bag, 1 striped tomato bag.\r\n"
			+ "wavy teal bags contain 5 wavy red bags, 2 drab brown bags, 1 posh olive bag.\r\n"
			+ "dim green bags contain 2 striped teal bags, 1 drab blue bag.\r\n"
			+ "wavy crimson bags contain no other bags.\r\n"
			+ "mirrored aqua bags contain 3 posh tan bags, 5 muted teal bags, 3 light violet bags.\r\n"
			+ "light cyan bags contain 4 vibrant chartreuse bags, 1 faded lime bag, 2 drab purple bags, 2 shiny white bags.\r\n"
			+ "shiny gold bags contain 4 drab blue bags, 4 posh purple bags, 2 drab silver bags, 4 wavy turquoise bags.\r\n"
			+ "plaid chartreuse bags contain 5 mirrored olive bags, 2 vibrant orange bags, 2 shiny purple bags.\r\n"
			+ "dim yellow bags contain 1 faded green bag, 4 wavy fuchsia bags.\r\n"
			+ "pale turquoise bags contain 1 drab turquoise bag.\r\n"
			+ "clear red bags contain 1 pale bronze bag, 4 drab tan bags.\r\n"
			+ "shiny teal bags contain 3 bright aqua bags.\r\n"
			+ "dotted tomato bags contain 3 dotted orange bags, 5 light silver bags, 2 dull green bags, 5 wavy chartreuse bags.\r\n"
			+ "striped tan bags contain 1 light turquoise bag, 2 dotted salmon bags, 4 shiny orange bags, 2 clear red bags.\r\n"
			+ "dim bronze bags contain 1 wavy gold bag.\r\n"
			+ "posh crimson bags contain 4 posh aqua bags.\r\n"
			+ "plaid salmon bags contain 2 dull tan bags.\r\n"
			+ "mirrored salmon bags contain 2 muted aqua bags, 5 muted salmon bags.\r\n"
			+ "striped blue bags contain 3 wavy white bags, 4 drab blue bags, 1 drab chartreuse bag, 4 dull orange bags.\r\n"
			+ "pale red bags contain 1 striped red bag.\r\n"
			+ "muted black bags contain 4 faded gold bags.\r\n"
			+ "clear orange bags contain 2 faded red bags.\r\n"
			+ "mirrored maroon bags contain 2 plaid tan bags.\r\n"
			+ "dull aqua bags contain 4 pale gold bags.\r\n"
			+ "posh coral bags contain 3 striped gold bags.\r\n"
			+ "posh purple bags contain 4 pale orange bags, 5 dull salmon bags, 2 striped teal bags.\r\n"
			+ "muted tan bags contain 3 clear coral bags, 4 pale salmon bags.\r\n"
			+ "mirrored orange bags contain 5 pale bronze bags.\r\n"
			+ "striped teal bags contain no other bags.\r\n"
			+ "dark blue bags contain no other bags.\r\n"
			+ "clear bronze bags contain 4 vibrant gray bags.\r\n"
			+ "light magenta bags contain 4 dim green bags.\r\n"
			+ "drab coral bags contain 5 dotted chartreuse bags, 4 vibrant crimson bags, 2 muted green bags.\r\n"
			+ "drab brown bags contain 2 dull tomato bags, 5 vibrant bronze bags.\r\n"
			+ "bright coral bags contain 1 posh plum bag, 1 wavy gold bag, 2 drab lavender bags, 2 muted lavender bags.\r\n"
			+ "dim white bags contain 4 shiny aqua bags.\r\n"
			+ "plaid bronze bags contain 4 drab tan bags, 3 plaid salmon bags, 4 striped coral bags.\r\n"
			+ "faded teal bags contain 1 vibrant white bag, 5 wavy purple bags.\r\n"
			+ "drab turquoise bags contain 3 pale tomato bags, 1 bright indigo bag.\r\n"
			+ "muted white bags contain 3 striped brown bags, 1 light blue bag.\r\n"
			+ "clear crimson bags contain 1 dark magenta bag.\r\n"
			+ "shiny magenta bags contain 4 wavy tomato bags, 4 shiny bronze bags, 4 vibrant coral bags, 5 bright lime bags.\r\n"
			+ "bright magenta bags contain 3 wavy brown bags.\r\n"
			+ "bright tomato bags contain 4 vibrant fuchsia bags, 1 clear aqua bag.\r\n"
			+ "wavy coral bags contain 4 striped gold bags, 1 light purple bag, 4 vibrant purple bags.\r\n"
			+ "muted indigo bags contain 2 posh purple bags, 2 light gold bags, 3 striped lavender bags.\r\n"
			+ "clear violet bags contain 2 wavy cyan bags, 5 pale brown bags, 4 faded magenta bags, 2 bright purple bags.\r\n"
			+ "dull white bags contain 4 wavy olive bags, 3 mirrored olive bags, 3 faded magenta bags, 4 dull green bags.\r\n"
			+ "dull magenta bags contain 4 dim beige bags.\r\n"
			+ "dotted blue bags contain 4 posh beige bags, 1 pale purple bag, 4 shiny red bags.\r\n"
			+ "dotted lavender bags contain 3 posh purple bags.\r\n"
			+ "light white bags contain 4 striped lavender bags.\r\n"
			+ "dark turquoise bags contain 5 light teal bags.\r\n"
			+ "faded turquoise bags contain 5 striped violet bags, 4 dull crimson bags, 2 dim purple bags, 1 light silver bag.\r\n"
			+ "striped chartreuse bags contain 3 pale white bags, 3 dim fuchsia bags.\r\n"
			+ "pale gold bags contain 2 clear teal bags, 3 wavy turquoise bags, 5 light gold bags.\r\n"
			+ "posh blue bags contain 4 muted yellow bags, 1 dull crimson bag, 3 wavy violet bags, 5 mirrored fuchsia bags.\r\n"
			+ "dotted gray bags contain 3 wavy fuchsia bags.\r\n"
			+ "plaid magenta bags contain 3 plaid black bags.\r\n"
			+ "pale beige bags contain 1 pale white bag, 2 dim salmon bags, 5 mirrored gold bags.\r\n"
			+ "striped bronze bags contain 2 dull yellow bags, 2 dark blue bags.\r\n"
			+ "dark lime bags contain 2 pale magenta bags, 4 clear cyan bags.\r\n"
			+ "bright turquoise bags contain 2 light white bags, 3 plaid salmon bags, 2 clear aqua bags, 5 dull silver bags.\r\n"
			+ "posh salmon bags contain 1 drab turquoise bag.\r\n"
			+ "muted bronze bags contain 1 pale bronze bag, 3 clear maroon bags.\r\n"
			+ "faded coral bags contain 1 clear gray bag, 5 plaid gray bags, 3 bright silver bags, 4 posh yellow bags.\r\n"
			+ "mirrored gray bags contain 1 dark coral bag, 2 plaid blue bags, 4 mirrored coral bags, 1 mirrored olive bag.\r\n"
			+ "vibrant olive bags contain 5 pale chartreuse bags, 4 plaid green bags, 4 dark coral bags.\r\n"
			+ "dotted magenta bags contain 4 light chartreuse bags, 3 plaid indigo bags, 2 dull tan bags.\r\n"
			+ "light violet bags contain 2 muted green bags.\r\n"
			+ "dim fuchsia bags contain 5 dim tan bags, 5 faded black bags, 1 drab white bag.\r\n"
			+ "dotted black bags contain 3 bright gold bags, 2 faded gold bags.\r\n"
			+ "striped indigo bags contain 3 posh aqua bags.\r\n"
			+ "posh cyan bags contain 5 dull fuchsia bags.\r\n"
			+ "vibrant turquoise bags contain 2 muted chartreuse bags, 2 clear magenta bags, 5 drab chartreuse bags.\r\n"
			+ "mirrored magenta bags contain 1 dull lime bag.\r\n"
			+ "mirrored violet bags contain 2 posh magenta bags, 1 plaid white bag, 4 wavy turquoise bags, 5 dull salmon bags.\r\n"
			+ "pale tomato bags contain 4 wavy maroon bags, 3 clear aqua bags, 2 striped lavender bags.\r\n"
			+ "clear fuchsia bags contain 5 dark cyan bags, 1 plaid cyan bag.\r\n"
			+ "drab orange bags contain 3 mirrored purple bags, 1 striped orange bag.\r\n"
			+ "bright blue bags contain 1 bright cyan bag, 4 plaid green bags.\r\n"
			+ "muted chartreuse bags contain 4 faded beige bags, 3 faded green bags.\r\n"
			+ "plaid teal bags contain 2 mirrored orange bags, 5 plaid plum bags.\r\n"
			+ "light blue bags contain 4 faded silver bags, 3 light turquoise bags, 2 dim aqua bags, 5 posh silver bags.\r\n"
			+ "bright tan bags contain 4 striped coral bags, 1 dark fuchsia bag.\r\n"
			+ "shiny black bags contain 1 light green bag.\r\n"
			+ "plaid violet bags contain 1 faded magenta bag, 1 shiny bronze bag, 2 vibrant tomato bags.\r\n"
			+ "posh bronze bags contain 4 shiny gold bags, 1 bright yellow bag, 1 dull cyan bag.\r\n"
			+ "light red bags contain 3 dotted black bags, 5 pale coral bags.\r\n"
			+ "striped red bags contain no other bags.\r\n"
			+ "clear tan bags contain 2 faded brown bags, 1 bright brown bag, 2 bright gold bags.\r\n"
			+ "dull turquoise bags contain 5 mirrored yellow bags, 3 wavy red bags, 5 faded purple bags, 4 clear green bags.\r\n"
			+ "plaid yellow bags contain 4 dark red bags, 3 dull tomato bags, 5 faded violet bags.\r\n"
			+ "dotted gold bags contain 2 dotted lime bags, 2 faded gray bags, 3 clear coral bags.\r\n"
			+ "dull bronze bags contain 2 pale red bags, 3 dim indigo bags.\r\n"
			+ "shiny green bags contain 2 pale red bags, 1 mirrored silver bag, 4 bright lime bags, 5 pale indigo bags.\r\n"
			+ "bright black bags contain 2 striped plum bags, 1 clear black bag, 4 clear olive bags.\r\n"
			+ "bright gold bags contain 3 wavy cyan bags, 1 dotted magenta bag, 1 muted salmon bag, 4 light maroon bags.\r\n"
			+ "muted violet bags contain 5 wavy cyan bags, 4 dim tan bags, 1 posh gray bag, 5 vibrant brown bags.\r\n"
			+ "dim turquoise bags contain 1 pale tomato bag, 2 dotted silver bags, 5 mirrored coral bags.\r\n"
			+ "drab lime bags contain 5 shiny gold bags.\r\n"
			+ "wavy bronze bags contain 1 shiny red bag, 4 dotted cyan bags.\r\n"
			+ "vibrant purple bags contain 4 drab chartreuse bags, 4 dotted yellow bags.\r\n"
			+ "plaid purple bags contain 2 drab beige bags, 3 pale aqua bags, 3 muted magenta bags.\r\n"
			+ "faded brown bags contain 3 faded beige bags, 1 light chartreuse bag, 4 mirrored gold bags.\r\n"
			+ "pale lavender bags contain 1 mirrored tomato bag, 5 wavy maroon bags, 4 wavy lime bags.\r\n"
			+ "posh fuchsia bags contain 5 posh orange bags.\r\n"
			+ "drab fuchsia bags contain 1 dim plum bag, 1 dark coral bag, 3 dark red bags.\r\n"
			+ "striped crimson bags contain 5 pale orange bags, 5 faded beige bags, 5 faded brown bags.\r\n"
			+ "wavy lime bags contain 5 dull crimson bags.\r\n"
			+ "vibrant fuchsia bags contain 2 wavy white bags.\r\n"
			+ "vibrant plum bags contain 4 dim salmon bags, 2 plaid tan bags, 3 dull blue bags.\r\n"
			+ "muted cyan bags contain 3 striped beige bags.\r\n"
			+ "clear teal bags contain 2 wavy aqua bags, 3 dotted plum bags.\r\n"
			+ "dark maroon bags contain 1 light violet bag, 3 clear plum bags, 5 dotted fuchsia bags, 2 vibrant tomato bags.\r\n"
			+ "dull black bags contain 5 muted olive bags.\r\n"
			+ "light yellow bags contain 1 dull white bag, 5 dark aqua bags, 3 light purple bags, 4 dim green bags.\r\n"
			+ "pale bronze bags contain 1 wavy aqua bag.\r\n"
			+ "plaid red bags contain 5 pale plum bags, 2 muted brown bags, 2 dull bronze bags.\r\n"
			+ "dim gray bags contain 2 muted lavender bags.\r\n"
			+ "plaid gray bags contain 5 muted aqua bags.\r\n"
			+ "vibrant blue bags contain 4 light tomato bags, 1 plaid beige bag.\r\n"
			+ "clear blue bags contain 5 clear plum bags, 5 drab chartreuse bags.\r\n"
			+ "dotted green bags contain 5 plaid white bags, 5 vibrant turquoise bags, 1 drab silver bag.\r\n"
			+ "dull crimson bags contain 3 mirrored yellow bags, 3 posh red bags, 3 faded brown bags.\r\n"
			+ "striped maroon bags contain 1 shiny magenta bag, 2 light brown bags, 4 dull green bags.\r\n"
			+ "dark yellow bags contain 4 faded silver bags, 5 shiny lavender bags, 4 dim crimson bags, 2 plaid bronze bags.\r\n"
			+ "pale indigo bags contain 4 plaid salmon bags, 3 striped purple bags, 5 pale magenta bags, 1 dotted lime bag.\r\n"
			+ "faded maroon bags contain 5 light silver bags, 5 dim bronze bags, 4 faded tan bags, 5 striped crimson bags.\r\n"
			+ "pale green bags contain 4 vibrant white bags.\r\n"
			+ "muted maroon bags contain 2 light black bags, 2 mirrored fuchsia bags.\r\n"
			+ "pale yellow bags contain 2 dull bronze bags, 4 bright maroon bags, 5 wavy cyan bags, 4 dotted lavender bags.\r\n"
			+ "posh white bags contain 3 mirrored turquoise bags, 3 shiny aqua bags, 2 striped blue bags, 4 faded coral bags.\r\n"
			+ "wavy orange bags contain 4 wavy crimson bags, 2 bright brown bags, 3 bright magenta bags, 1 dotted gold bag.\r\n"
			+ "dark beige bags contain 3 muted white bags.\r\n"
			+ "dotted salmon bags contain 5 dim bronze bags, 5 striped orange bags.\r\n"
			+ "dotted fuchsia bags contain 1 striped red bag, 4 bright purple bags.\r\n"
			+ "pale cyan bags contain 1 dull blue bag.\r\n"
			+ "mirrored purple bags contain 5 light turquoise bags, 2 faded silver bags.\r\n"
			+ "drab violet bags contain 1 vibrant turquoise bag, 2 muted chartreuse bags, 5 pale bronze bags.\r\n"
			+ "wavy gray bags contain 1 dark purple bag, 4 muted green bags.\r\n"
			+ "wavy magenta bags contain 5 dark white bags, 4 vibrant black bags, 4 muted coral bags.\r\n"
			+ "pale plum bags contain 5 mirrored brown bags, 2 pale red bags.\r\n"
			+ "light plum bags contain 4 dark tomato bags, 4 wavy gold bags.\r\n"
			+ "pale aqua bags contain 1 striped red bag, 2 dim crimson bags, 3 mirrored orange bags.\r\n"
			+ "muted green bags contain 1 mirrored yellow bag.\r\n"
			+ "bright purple bags contain 5 light violet bags, 5 clear magenta bags, 1 faded lime bag.\r\n"
			+ "dark green bags contain 2 shiny aqua bags.\r\n"
			+ "dark orange bags contain 3 striped coral bags.\r\n"
			+ "dotted chartreuse bags contain 1 bright lime bag, 1 light olive bag, 4 muted red bags, 1 posh chartreuse bag.\r\n"
			+ "shiny chartreuse bags contain 1 bright salmon bag, 1 plaid indigo bag.\r\n"
			+ "clear gold bags contain 5 dull lime bags, 4 shiny brown bags, 1 dull plum bag, 4 dull salmon bags.\r\n"
			+ "shiny salmon bags contain 2 muted salmon bags, 2 dotted lavender bags.\r\n"
			+ "striped cyan bags contain 3 drab tan bags, 5 dotted cyan bags, 1 posh aqua bag, 1 plaid magenta bag.\r\n"
			+ "dark plum bags contain 1 clear orange bag, 2 striped black bags.\r\n"
			+ "vibrant magenta bags contain 1 plaid tan bag, 3 muted bronze bags, 3 bright chartreuse bags.\r\n"
			+ "clear beige bags contain 4 muted tan bags, 1 clear turquoise bag, 4 mirrored turquoise bags, 2 bright silver bags.\r\n"
			+ "drab lavender bags contain 1 dotted cyan bag, 4 clear plum bags.\r\n"
			+ "shiny coral bags contain 2 drab beige bags.\r\n"
			+ "light bronze bags contain 2 mirrored plum bags, 2 light black bags.\r\n"
			+ "vibrant yellow bags contain 4 vibrant coral bags, 5 mirrored olive bags, 1 light lime bag, 2 muted crimson bags.\r\n"
			+ "vibrant salmon bags contain 4 faded beige bags, 2 faded olive bags, 1 pale brown bag.\r\n"
			+ "dim tan bags contain 3 faded beige bags, 4 light tan bags.\r\n"
			+ "vibrant silver bags contain 1 dark tomato bag.\r\n"
			+ "striped salmon bags contain 5 faded brown bags.\r\n"
			+ "shiny purple bags contain 1 pale lavender bag, 3 plaid black bags, 1 drab indigo bag.\r\n"
			+ "light turquoise bags contain 4 dark silver bags.\r\n"
			+ "dark chartreuse bags contain 5 dark silver bags.\r\n"
			+ "mirrored indigo bags contain 5 mirrored gold bags, 1 dotted white bag.\r\n"
			+ "faded olive bags contain 1 pale brown bag, 3 faded beige bags, 2 light chartreuse bags.\r\n"
			+ "mirrored black bags contain 5 posh purple bags.\r\n"
			+ "clear green bags contain 2 dark magenta bags, 5 faded gold bags, 4 striped teal bags, 4 dark purple bags.\r\n"
			+ "bright beige bags contain 3 light olive bags, 3 wavy orange bags, 4 dotted lavender bags.\r\n"
			+ "plaid brown bags contain 4 dull lavender bags, 3 drab gold bags.\r\n"
			+ "vibrant chartreuse bags contain 1 bright bronze bag, 5 wavy crimson bags.\r\n"
			+ "posh aqua bags contain 5 muted green bags, 2 dim green bags, 1 dim crimson bag, 1 posh red bag.\r\n"
			+ "vibrant gold bags contain 5 wavy chartreuse bags, 3 drab gold bags, 2 striped blue bags, 3 posh yellow bags.\r\n"
			+ "posh tan bags contain 1 shiny chartreuse bag, 2 drab bronze bags.\r\n"
			+ "bright violet bags contain 1 pale lavender bag, 5 mirrored olive bags, 1 posh turquoise bag.\r\n"
			+ "faded lime bags contain 5 pale brown bags, 4 faded black bags, 1 faded beige bag.\r\n"
			+ "vibrant gray bags contain 3 vibrant chartreuse bags, 3 bright purple bags.\r\n"
			+ "dull silver bags contain 5 pale tomato bags, 5 shiny turquoise bags, 2 mirrored yellow bags.\r\n"
			+ "pale maroon bags contain 3 posh red bags, 1 plaid bronze bag, 5 striped red bags.\r\n"
			+ "dull lavender bags contain 4 vibrant violet bags, 1 bright yellow bag, 3 bright aqua bags.\r\n"
			+ "light aqua bags contain 5 vibrant turquoise bags.\r\n"
			+ "striped violet bags contain 4 drab silver bags, 3 posh magenta bags, 3 wavy turquoise bags.\r\n"
			+ "bright green bags contain 3 drab teal bags.\r\n"
			+ "light coral bags contain 5 dotted violet bags, 4 pale chartreuse bags.\r\n"
			+ "muted salmon bags contain 4 vibrant turquoise bags, 5 clear chartreuse bags, 1 dark fuchsia bag, 5 bright bronze bags.\r\n"
			+ "wavy cyan bags contain 4 dim orange bags, 1 dull orange bag, 4 plaid indigo bags, 4 dim salmon bags.\r\n"
			+ "shiny red bags contain 1 dim blue bag, 4 clear plum bags.\r\n"
			+ "vibrant beige bags contain 3 posh red bags.\r\n"
			+ "shiny maroon bags contain 3 striped tomato bags, 2 faded lime bags.\r\n"
			+ "shiny aqua bags contain 3 bright yellow bags.\r\n"
			+ "bright aqua bags contain 5 wavy lavender bags, 4 striped coral bags, 5 dotted cyan bags, 3 drab cyan bags.\r\n"
			+ "dim olive bags contain 2 posh blue bags, 5 vibrant violet bags, 3 drab brown bags, 1 dull purple bag.\r\n"
			+ "shiny silver bags contain 5 dim green bags, 4 dull cyan bags.\r\n"
			+ "dim brown bags contain 1 wavy brown bag, 3 drab black bags.\r\n"
			+ "dotted brown bags contain 3 drab crimson bags, 1 shiny red bag.\r\n"
			+ "striped coral bags contain 4 striped red bags, 1 dotted cyan bag.\r\n"
			+ "dotted plum bags contain 3 faded lime bags, 2 striped lavender bags, 2 wavy crimson bags, 2 faded brown bags.\r\n"
			+ "light gold bags contain 1 light silver bag, 3 posh teal bags, 3 dark orange bags, 4 bright bronze bags.\r\n"
			+ "dark tan bags contain 5 drab black bags, 2 plaid cyan bags, 3 faded yellow bags, 1 dim blue bag.\r\n"
			+ "posh olive bags contain 4 drab olive bags, 5 dull tan bags, 1 wavy chartreuse bag, 5 muted magenta bags.\r\n"
			+ "dull red bags contain 1 vibrant teal bag, 4 dim salmon bags, 1 bright violet bag, 1 dark lavender bag.\r\n"
			+ "plaid turquoise bags contain 3 faded green bags, 5 wavy crimson bags.\r\n"
			+ "plaid cyan bags contain 2 dull yellow bags, 2 dotted cyan bags, 1 light chartreuse bag, 2 faded green bags.\r\n"
			+ "dull indigo bags contain 2 faded silver bags.\r\n"
			+ "pale brown bags contain no other bags.\r\n"
			+ "striped plum bags contain 5 dull lime bags, 2 muted white bags, 3 striped teal bags.\r\n"
			+ "dotted coral bags contain 4 faded silver bags, 2 wavy aqua bags, 2 light chartreuse bags, 5 posh indigo bags.\r\n"
			+ "mirrored beige bags contain 1 plaid black bag, 2 plaid tan bags, 2 pale bronze bags.\r\n"
			+ "vibrant cyan bags contain 4 wavy beige bags, 1 shiny orange bag.\r\n"
			+ "wavy fuchsia bags contain 5 pale maroon bags, 3 drab violet bags, 2 shiny orange bags.\r\n"
			+ "drab silver bags contain 2 dark blue bags, 3 light chartreuse bags, 3 mirrored gold bags.\r\n"
			+ "wavy turquoise bags contain 5 posh red bags, 4 striped teal bags.\r\n"
			+ "bright cyan bags contain 4 bright silver bags, 1 muted gray bag, 5 faded aqua bags, 3 wavy aqua bags.\r\n"
			+ "wavy green bags contain 4 clear violet bags, 4 dark olive bags, 2 clear magenta bags, 1 mirrored black bag.\r\n"
			+ "mirrored gold bags contain 2 dark olive bags.\r\n"
			+ "wavy gold bags contain 4 plaid indigo bags.\r\n"
			+ "dotted yellow bags contain 3 dull orange bags, 2 faded green bags.\r\n"
			+ "light beige bags contain 4 dull cyan bags.\r\n"
			+ "bright crimson bags contain 1 faded tan bag, 1 faded chartreuse bag, 5 vibrant brown bags.\r\n"
			+ "dotted bronze bags contain 5 striped white bags.\r\n"
			+ "mirrored yellow bags contain 3 wavy crimson bags, 4 dark olive bags, 5 drab tan bags.\r\n"
			+ "plaid lavender bags contain 1 light tomato bag, 5 dull blue bags, 2 wavy indigo bags, 3 bright gray bags.\r\n"
			+ "drab purple bags contain 3 dotted plum bags, 5 drab olive bags, 1 drab tan bag, 3 dark black bags.\r\n"
			+ "shiny lime bags contain 2 plaid bronze bags, 1 shiny gold bag.\r\n"
			+ "drab chartreuse bags contain 2 bright bronze bags, 4 light teal bags, 1 mirrored yellow bag.\r\n"
			+ "bright plum bags contain 3 drab turquoise bags.\r\n"
			+ "light orange bags contain 1 shiny lavender bag, 2 dark fuchsia bags, 1 muted olive bag, 4 wavy olive bags.\r\n"
			+ "striped beige bags contain 4 dull crimson bags, 5 dotted fuchsia bags.\r\n"
			+ "wavy chartreuse bags contain 2 bright salmon bags, 5 faded green bags, 1 mirrored black bag.\r\n"
			+ "striped tomato bags contain no other bags.\r\n"
			+ "plaid aqua bags contain 1 light magenta bag, 3 pale white bags, 3 clear blue bags, 4 dull crimson bags.\r\n"
			+ "plaid tan bags contain 3 dull green bags, 1 light silver bag, 5 dim orange bags, 1 dark blue bag.\r\n"
			+ "dotted cyan bags contain 2 wavy black bags, 3 striped teal bags.\r\n"
			+ "dull green bags contain 1 plaid magenta bag, 3 dull plum bags, 4 dim green bags.\r\n"
			+ "faded purple bags contain 5 mirrored cyan bags, 1 dull beige bag, 4 vibrant purple bags.\r\n"
			+ "dotted maroon bags contain 1 vibrant beige bag, 3 plaid magenta bags.\r\n"
			+ "faded aqua bags contain 4 plaid gold bags, 1 plaid yellow bag, 2 bright lime bags.\r\n"
			+ "pale lime bags contain 1 light blue bag.\r\n"
			+ "dark indigo bags contain 1 light gold bag.\r\n"
			+ "shiny orange bags contain 2 plaid black bags, 2 faded brown bags, 4 plaid indigo bags.\r\n"
			+ "muted olive bags contain 1 wavy chartreuse bag.\r\n"
			+ "muted purple bags contain 4 dotted silver bags.\r\n"
			+ "plaid black bags contain 3 drab silver bags.\r\n"
			+ "striped lavender bags contain 5 wavy crimson bags.\r\n"
			+ "posh chartreuse bags contain 5 drab chartreuse bags.\r\n"
			+ "clear purple bags contain 3 faded green bags, 2 bright gold bags.\r\n"
			+ "dark crimson bags contain 4 plaid teal bags, 4 muted cyan bags.\r\n"
			+ "clear silver bags contain 3 pale beige bags, 2 mirrored tomato bags.\r\n"
			+ "dotted indigo bags contain 2 dark plum bags, 2 clear magenta bags, 3 light olive bags.\r\n"
			+ "dull chartreuse bags contain 2 light turquoise bags, 3 drab brown bags.\r\n"
			+ "bright brown bags contain 4 light purple bags, 1 vibrant coral bag.\r\n"
			+ "dim salmon bags contain 2 dull salmon bags.\r\n"
			+ "muted lime bags contain 4 muted violet bags, 5 shiny white bags.\r\n"
			+ "vibrant lime bags contain 2 mirrored bronze bags, 1 dotted crimson bag, 5 dim yellow bags, 2 mirrored gold bags.\r\n"
			+ "muted silver bags contain 1 striped orange bag, 3 drab purple bags.\r\n"
			+ "mirrored bronze bags contain 4 dull bronze bags.\r\n"
			+ "light olive bags contain 4 mirrored olive bags, 2 dim lime bags, 1 clear magenta bag.\r\n"
			+ "vibrant tan bags contain 2 shiny teal bags.\r\n"
			+ "posh red bags contain 2 bright bronze bags, 5 striped teal bags, 5 faded beige bags, 4 faded olive bags.\r\n"
			+ "faded red bags contain 4 striped lavender bags, 4 posh red bags.\r\n"
			+ "mirrored brown bags contain 3 dim salmon bags, 4 drab chartreuse bags, 1 wavy tomato bag.\r\n"
			+ "dark gray bags contain 1 muted tan bag, 4 faded blue bags, 2 dim chartreuse bags.\r\n"
			+ "dark white bags contain 4 vibrant lime bags, 4 pale olive bags.\r\n"
			+ "striped silver bags contain 4 dim cyan bags.\r\n"
			+ "clear salmon bags contain 5 pale magenta bags, 1 mirrored salmon bag.\r\n"
			+ "pale white bags contain 5 wavy crimson bags, 4 plaid indigo bags, 5 striped crimson bags, 3 drab violet bags.\r\n"
			+ "vibrant indigo bags contain 1 mirrored gold bag, 1 striped turquoise bag, 3 posh beige bags.\r\n"
			+ "drab aqua bags contain 5 faded crimson bags, 3 wavy gold bags, 3 striped tomato bags.\r\n"
			+ "clear brown bags contain 5 bright lavender bags.\r\n"
			+ "posh indigo bags contain 5 mirrored red bags, 5 clear coral bags.\r\n"
			+ "posh black bags contain 4 dim fuchsia bags, 5 muted olive bags, 3 mirrored red bags.\r\n"
			+ "shiny lavender bags contain 2 muted aqua bags, 3 striped black bags, 3 wavy salmon bags, 3 mirrored purple bags.\r\n"
			+ "vibrant bronze bags contain 1 bright tan bag, 5 faded beige bags, 5 pale red bags, 1 plaid cyan bag.\r\n"
			+ "clear chartreuse bags contain 2 shiny gold bags, 1 wavy turquoise bag, 2 muted crimson bags.\r\n"
			+ "drab tan bags contain no other bags.\r\n"
			+ "posh gold bags contain 5 dotted beige bags, 1 striped crimson bag, 5 drab purple bags, 1 bright gray bag.\r\n"
			+ "clear olive bags contain 3 dark tomato bags.\r\n"
			+ "dim aqua bags contain 4 wavy black bags, 5 clear chartreuse bags, 5 clear aqua bags.\r\n"
			+ "pale coral bags contain 2 shiny orange bags, 5 dark black bags, 3 vibrant coral bags.\r\n"
			+ "drab blue bags contain 5 dull salmon bags.\r\n"
			+ "vibrant white bags contain 2 mirrored yellow bags.\r\n"
			+ "faded indigo bags contain 5 clear aqua bags.\r\n"
			+ "posh turquoise bags contain 1 light purple bag, 4 mirrored salmon bags.\r\n"
			+ "dotted orange bags contain 5 dark blue bags, 1 shiny lavender bag, 2 dim plum bags, 3 clear violet bags.\r\n"
			+ "muted crimson bags contain 4 wavy crimson bags, 1 light magenta bag, 3 clear plum bags.\r\n"
			+ "dim coral bags contain 1 vibrant red bag, 2 vibrant magenta bags.\r\n"
			+ "mirrored plum bags contain 5 light olive bags.\r\n"
			+ "dull violet bags contain 2 dim aqua bags.\r\n"
			+ "faded violet bags contain 5 clear violet bags, 5 muted indigo bags, 3 clear red bags, 1 posh tan bag.\r\n"
			+ "vibrant crimson bags contain 1 shiny crimson bag.\r\n"
			+ "muted plum bags contain 3 drab beige bags, 4 posh maroon bags.\r\n"
			+ "dim orange bags contain 5 bright salmon bags.\r\n"
			+ "dim blue bags contain 1 mirrored black bag, 3 faded blue bags.\r\n"
			+ "mirrored tan bags contain 5 plaid plum bags.\r\n"
			+ "pale crimson bags contain 4 dim green bags, 2 pale fuchsia bags.\r\n"
			+ "bright white bags contain 2 drab gold bags, 2 shiny maroon bags, 5 mirrored lime bags.\r\n"
			+ "dim indigo bags contain 1 mirrored cyan bag, 1 wavy purple bag, 1 drab brown bag.\r\n"
			+ "dotted violet bags contain 4 bright teal bags, 2 vibrant plum bags.\r\n"
			+ "wavy indigo bags contain 2 drab silver bags, 1 muted chartreuse bag, 1 drab aqua bag, 3 mirrored teal bags.\r\n"
			+ "dark cyan bags contain 1 muted magenta bag, 3 vibrant violet bags, 4 mirrored aqua bags, 5 drab violet bags.\r\n"
			+ "posh maroon bags contain 5 muted chartreuse bags, 4 dark olive bags.\r\n"
			+ "drab tomato bags contain 2 plaid tan bags, 2 posh purple bags, 2 posh beige bags.\r\n"
			+ "wavy tan bags contain 5 light cyan bags, 5 muted brown bags, 5 mirrored coral bags, 5 light chartreuse bags.\r\n"
			+ "faded bronze bags contain 4 dotted magenta bags.\r\n"
			+ "pale blue bags contain 5 pale purple bags.\r\n"
			+ "dim magenta bags contain 5 posh aqua bags, 5 dim crimson bags, 4 wavy gold bags, 2 shiny orange bags.\r\n"
			+ "dark fuchsia bags contain 2 drab silver bags.\r\n"
			+ "wavy white bags contain 4 vibrant turquoise bags, 2 clear violet bags, 1 dull salmon bag.\r\n"
			+ "drab maroon bags contain 3 pale tomato bags, 2 dim chartreuse bags, 5 mirrored orange bags, 4 drab violet bags.\r\n"
			+ "muted fuchsia bags contain 4 muted bronze bags, 4 plaid brown bags, 1 faded white bag.\r\n"
			+ "plaid gold bags contain 3 vibrant bronze bags, 5 striped chartreuse bags.\r\n"
			+ "faded green bags contain 2 dull cyan bags, 5 posh purple bags.\r\n"
			+ "light indigo bags contain 5 mirrored tomato bags.\r\n"
			+ "striped white bags contain 5 clear plum bags.\r\n"
			+ "posh magenta bags contain 5 wavy crimson bags, 3 striped coral bags.\r\n"
			+ "drab olive bags contain 4 striped orange bags.\r\n"
			+ "plaid indigo bags contain 1 plaid turquoise bag.\r\n"
			+ "dark brown bags contain 2 faded tan bags, 5 wavy green bags.\r\n"
			+ "faded cyan bags contain 2 bright violet bags, 3 mirrored salmon bags.\r\n"
			+ "dim lavender bags contain 2 mirrored fuchsia bags, 3 pale magenta bags, 2 dotted tan bags, 4 posh bronze bags.\r\n"
			+ "dull maroon bags contain 3 dark silver bags, 5 dim plum bags.\r\n"
			+ "dull teal bags contain 3 pale green bags.\r\n"
			+ "shiny yellow bags contain 4 dotted fuchsia bags.\r\n"
			+ "mirrored crimson bags contain 5 dotted plum bags.\r\n"
			+ "drab beige bags contain 3 faded orange bags, 3 dark orange bags, 4 clear orange bags.\r\n"
			+ "dull olive bags contain 2 vibrant bronze bags, 4 shiny chartreuse bags.\r\n"
			+ "wavy red bags contain 2 wavy brown bags, 1 wavy olive bag, 3 striped cyan bags.\r\n"
			+ "light gray bags contain 1 pale salmon bag, 2 plaid bronze bags, 5 dull yellow bags.\r\n"
			+ "faded gray bags contain 4 muted green bags, 5 faded red bags, 3 muted magenta bags, 5 bright magenta bags.\r\n"
			+ "drab indigo bags contain 1 posh gold bag, 2 dull lime bags, 1 pale orange bag.\r\n"
			+ "bright yellow bags contain 4 posh red bags, 4 shiny gold bags.\r\n"
			+ "drab bronze bags contain 4 dark indigo bags.\r\n"
			+ "striped gold bags contain 3 faded yellow bags, 2 mirrored tomato bags, 1 bright lime bag.\r\n"
			+ "muted gold bags contain 4 dim violet bags.\r\n"
			+ "plaid olive bags contain 3 wavy fuchsia bags.\r\n"
			+ "bright gray bags contain 4 bright bronze bags, 1 plaid white bag, 1 pale bronze bag.\r\n"
			+ "clear turquoise bags contain 2 mirrored purple bags, 2 light gold bags, 4 dim cyan bags, 5 wavy olive bags.\r\n"
			+ "wavy plum bags contain 4 bright yellow bags.\r\n"
			+ "dull blue bags contain 4 dotted lavender bags.\r\n"
			+ "posh gray bags contain 4 faded blue bags, 2 dull brown bags, 1 clear cyan bag.\r\n"
			+ "pale black bags contain 5 dim cyan bags, 4 bright white bags.\r\n"
			+ "wavy blue bags contain 3 faded olive bags, 5 bright lavender bags, 1 wavy black bag, 2 posh magenta bags.\r\n"
			+ "posh beige bags contain 2 light cyan bags, 1 wavy violet bag, 1 muted olive bag.\r\n"
			+ "clear plum bags contain 3 dull cyan bags.\r\n"
			+ "drab cyan bags contain 5 plaid green bags.\r\n"
			+ "vibrant aqua bags contain 5 posh maroon bags.\r\n"
			+ "dim silver bags contain 5 shiny gold bags, 5 posh magenta bags, 1 light white bag.\r\n"
			+ "posh brown bags contain 4 plaid salmon bags, 2 vibrant blue bags, 2 posh olive bags.\r\n"
			+ "dark teal bags contain 1 faded brown bag.\r\n"
			+ "clear white bags contain 5 vibrant tan bags, 5 light purple bags, 3 posh tan bags, 4 faded beige bags.\r\n"
			+ "dim maroon bags contain 2 plaid chartreuse bags, 1 dim gray bag, 2 drab gold bags, 5 light white bags.\r\n"
			+ "dull salmon bags contain 5 striped teal bags, 3 dark blue bags, 3 drab tan bags, 5 wavy crimson bags.\r\n"
			+ "dull coral bags contain 1 faded red bag, 2 shiny teal bags, 3 bright gray bags, 1 pale brown bag.\r\n"
			+ "dark violet bags contain 1 clear cyan bag, 4 mirrored beige bags, 2 vibrant turquoise bags.\r\n"
			+ "vibrant maroon bags contain 1 muted magenta bag, 3 muted olive bags, 2 shiny turquoise bags.\r\n"
			+ "posh orange bags contain 5 dark black bags, 3 pale maroon bags, 5 dull plum bags.\r\n"
			+ "clear indigo bags contain 4 faded tan bags, 3 clear orange bags, 1 vibrant aqua bag.\r\n"
			+ "clear gray bags contain 4 dull salmon bags, 5 dark magenta bags.\r\n"
			+ "shiny turquoise bags contain 4 muted green bags, 4 vibrant beige bags, 5 mirrored cyan bags, 4 striped blue bags.\r\n"
			+ "pale salmon bags contain 1 dark silver bag, 4 dim green bags.\r\n"
			+ "striped gray bags contain 3 dark lavender bags.\r\n"
			+ "dull yellow bags contain 2 dark blue bags, 4 striped tomato bags, 2 striped red bags, 3 pale brown bags.\r\n"
			+ "posh yellow bags contain 1 dull green bag, 1 dull plum bag.\r\n"
			+ "plaid white bags contain 3 plaid turquoise bags, 4 dotted cyan bags, 3 shiny gold bags, 5 clear plum bags.\r\n"
			+ "faded orange bags contain 1 dull silver bag, 4 clear gray bags, 1 posh tomato bag, 2 wavy yellow bags.\r\n"
			+ "dim violet bags contain 4 drab silver bags, 1 dull yellow bag, 3 faded blue bags.\r\n"
			+ "light green bags contain 3 drab gold bags, 4 wavy purple bags.\r\n"
			+ "dark magenta bags contain 2 light gold bags, 5 drab violet bags.\r\n"
			+ "dark purple bags contain 5 plaid beige bags.\r\n"
			+ "mirrored blue bags contain 2 plaid tan bags.\r\n"
			+ "dim lime bags contain 1 dotted beige bag, 2 striped white bags, 5 dim blue bags, 5 wavy blue bags.\r\n"
			+ "bright chartreuse bags contain 3 clear orange bags.\r\n"
			+ "vibrant brown bags contain 3 mirrored violet bags, 5 dull green bags, 2 pale magenta bags.\r\n"
			+ "drab salmon bags contain 4 muted magenta bags.\r\n"
			+ "muted teal bags contain 5 dark black bags, 5 light gold bags.\r\n"
			+ "striped lime bags contain 1 dim orange bag.\r\n"
			+ "plaid crimson bags contain 4 dim teal bags, 3 dull salmon bags.\r\n"
			+ "posh plum bags contain 5 pale gray bags.\r\n"
			+ "light maroon bags contain 4 drab violet bags, 2 faded brown bags, 2 striped black bags, 3 striped coral bags.\r\n"
			+ "pale gray bags contain 1 dark aqua bag, 3 mirrored tomato bags.\r\n"
			+ "light chartreuse bags contain no other bags.\r\n"
			+ "dim crimson bags contain 5 faded blue bags, 1 dark blue bag, 2 striped teal bags.\r\n"
			+ "dim beige bags contain 5 wavy silver bags, 1 wavy orange bag, 1 dim lime bag, 2 mirrored lime bags.\r\n"
			+ "bright teal bags contain 1 dull violet bag, 1 faded beige bag, 3 faded orange bags.\r\n"
			+ "striped green bags contain 2 drab gold bags, 5 posh olive bags, 4 light indigo bags, 1 clear yellow bag.\r\n"
			+ "striped black bags contain 4 striped crimson bags, 1 pale red bag.\r\n"
			+ "plaid beige bags contain 3 pale tomato bags.\r\n"
			+ "drab plum bags contain 4 striped coral bags, 3 dotted crimson bags.\r\n"
			+ "plaid orange bags contain 4 bright aqua bags.\r\n"
			+ "wavy maroon bags contain 1 dim orange bag, 1 dim violet bag, 4 posh chartreuse bags, 5 plaid tan bags.\r\n"
			+ "dim purple bags contain 1 mirrored black bag, 1 plaid plum bag, 4 striped teal bags, 1 posh aqua bag.\r\n"
			+ "mirrored red bags contain 2 shiny salmon bags, 3 bright salmon bags, 1 vibrant salmon bag.\r\n"
			+ "striped brown bags contain 3 light lime bags, 1 drab black bag, 2 dull white bags, 5 drab lavender bags.\r\n"
			+ "dim red bags contain 2 mirrored black bags.\r\n"
			+ "clear lavender bags contain 5 pale fuchsia bags.\r\n"
			+ "bright bronze bags contain 2 striped teal bags, 4 clear plum bags, 3 dim crimson bags, 5 faded black bags.\r\n"
			+ "shiny violet bags contain 2 dark gold bags, 3 posh maroon bags.\r\n"
			+ "bright lime bags contain 2 clear magenta bags, 3 dark blue bags, 4 striped lavender bags, 1 dull crimson bag.\r\n"
			+ "mirrored silver bags contain 1 vibrant tomato bag, 4 dull salmon bags, 5 plaid green bags, 4 wavy brown bags.\r\n"
			+ "dotted olive bags contain 5 faded beige bags.\r\n"
			+ "posh tomato bags contain 2 faded purple bags.\r\n"
			+ "posh teal bags contain 2 drab tan bags, 3 striped red bags, 3 dull salmon bags, 1 striped lavender bag.\r\n"
			+ "shiny tomato bags contain 3 posh indigo bags.\r\n"
			+ "dotted crimson bags contain 1 pale gray bag.\r\n"
			+ "shiny indigo bags contain 1 pale beige bag.\r\n"
			+ "plaid lime bags contain 1 light maroon bag.\r\n"
			+ "mirrored turquoise bags contain 5 faded bronze bags.\r\n"
			+ "drab crimson bags contain 1 vibrant plum bag.\r\n"
			+ "dim black bags contain 3 muted tan bags, 3 drab silver bags, 4 dull white bags.\r\n"
			+ "faded yellow bags contain 5 faded black bags.\r\n"
			+ "faded white bags contain 2 wavy lavender bags, 1 shiny orange bag.\r\n"
			+ "plaid tomato bags contain 2 shiny brown bags, 3 clear red bags.\r\n"
			+ "drab white bags contain 5 dark yellow bags.\r\n"
			+ "mirrored tomato bags contain 2 light gold bags, 1 mirrored gold bag, 4 dim plum bags.\r\n"
			+ "plaid maroon bags contain 2 mirrored lime bags, 3 plaid salmon bags, 2 shiny chartreuse bags.\r\n"
			+ "drab gold bags contain 1 dim plum bag, 2 mirrored violet bags.\r\n"
			+ "muted orange bags contain 3 mirrored lime bags, 1 muted maroon bag, 5 drab violet bags, 2 posh green bags.\r\n"
			+ "mirrored fuchsia bags contain 3 dim plum bags, 2 muted olive bags, 2 wavy white bags, 1 dotted cyan bag.\r\n"
			+ "plaid silver bags contain 3 pale violet bags, 5 striped purple bags, 5 dull purple bags.\r\n"
			+ "dotted silver bags contain 2 vibrant coral bags.\r\n"
			+ "shiny cyan bags contain 4 mirrored teal bags, 4 faded magenta bags, 4 bright lime bags, 1 vibrant teal bag.\r\n"
			+ "clear yellow bags contain 1 muted brown bag, 5 wavy lime bags.\r\n"
			+ "muted red bags contain 5 muted coral bags, 2 light violet bags, 2 muted indigo bags, 4 dotted tan bags.\r\n"
			+ "dull beige bags contain 5 plaid black bags, 2 pale white bags, 2 light violet bags, 1 pale crimson bag.\r\n"
			+ "vibrant lavender bags contain 3 dark chartreuse bags, 4 bright lavender bags.\r\n"
			+ "posh lime bags contain 1 shiny cyan bag, 4 dotted blue bags, 3 mirrored chartreuse bags.\r\n"
			+ "shiny blue bags contain 1 dotted magenta bag.\r\n"
			+ "muted yellow bags contain 4 plaid salmon bags, 4 dull tomato bags.\r\n"
			+ "muted blue bags contain 5 wavy magenta bags, 3 vibrant gray bags.\r\n"
			+ "dotted tan bags contain 1 wavy green bag, 1 dim plum bag.\r\n"
			+ "drab red bags contain 2 dark olive bags, 5 mirrored tan bags, 3 dull coral bags, 4 plaid yellow bags.\r\n"
			+ "dull tomato bags contain 2 clear aqua bags, 2 dark fuchsia bags, 2 light teal bags.\r\n"
			+ "bright salmon bags contain 5 dark blue bags.\r\n"
			+ "pale olive bags contain 1 light violet bag, 3 shiny bronze bags, 2 dotted magenta bags, 4 posh silver bags.\r\n"
			+ "mirrored teal bags contain 4 posh chartreuse bags, 5 vibrant bronze bags.\r\n"
			+ "mirrored chartreuse bags contain 3 striped olive bags, 3 mirrored maroon bags, 5 faded black bags, 3 pale plum bags.\r\n"
			+ "pale orange bags contain 4 mirrored gold bags, 3 faded brown bags, 2 dark olive bags.\r\n"
			+ "dark olive bags contain no other bags.\r\n"
			+ "faded plum bags contain 5 bright green bags, 5 shiny beige bags, 2 vibrant indigo bags, 1 mirrored orange bag.\r\n"
			+ "drab magenta bags contain 5 dark fuchsia bags, 5 striped salmon bags.\r\n"
			+ "dark lavender bags contain 5 mirrored red bags, 4 vibrant aqua bags, 2 dotted tan bags.\r\n"
			+ "shiny bronze bags contain 2 clear aqua bags, 2 dull salmon bags, 1 plaid turquoise bag, 3 plaid bronze bags.\r\n"
			+ "faded magenta bags contain 2 mirrored gold bags, 5 dim orange bags.\r\n"
			+ "light lavender bags contain 3 striped magenta bags, 5 light yellow bags.\r\n"
			+ "clear tomato bags contain 3 dark bronze bags, 5 plaid aqua bags, 2 faded lime bags, 2 bright salmon bags.\r\n"
			+ "clear lime bags contain 1 mirrored lavender bag, 3 bright silver bags, 3 pale teal bags.\r\n"
			+ "light lime bags contain 4 dim crimson bags, 2 vibrant tomato bags, 4 posh red bags.\r\n"
			+ "wavy yellow bags contain 3 muted chartreuse bags, 3 drab teal bags, 4 striped tomato bags.\r\n"
			+ "dark silver bags contain 5 posh magenta bags, 1 plaid black bag, 3 faded brown bags.\r\n"
			+ "bright maroon bags contain 5 dotted turquoise bags, 3 wavy silver bags, 2 dotted lime bags.\r\n"
			+ "striped orange bags contain 5 striped coral bags, 3 posh teal bags.\r\n"
			+ "bright silver bags contain 3 mirrored violet bags, 5 striped gold bags, 1 striped white bag, 4 clear chartreuse bags.\r\n"
			+ "mirrored olive bags contain 4 light silver bags, 1 muted crimson bag.\r\n"
			+ "dim gold bags contain 3 clear magenta bags.\r\n"
			+ "shiny plum bags contain 5 muted olive bags, 5 dark turquoise bags, 2 dull green bags, 1 plaid magenta bag.\r\n"
			+ "mirrored green bags contain 5 striped magenta bags, 1 light lime bag, 2 dim cyan bags.\r\n"
			+ "wavy aqua bags contain 4 dull tan bags, 5 vibrant beige bags.\r\n"
			+ "posh lavender bags contain 4 muted black bags.\r\n"
			+ "dull lime bags contain 2 plaid black bags.\r\n"
			+ "dim chartreuse bags contain 4 bright red bags.\r\n"
			+ "muted lavender bags contain 5 faded red bags, 5 drab brown bags, 5 clear bronze bags.\r\n"
			+ "muted coral bags contain 4 clear red bags, 3 vibrant maroon bags.\r\n"
			+ "bright lavender bags contain 4 striped blue bags.";
	
	@Override
	public String part1() {
		HashMap<String,HashSet<String>> bags = new HashMap<String,HashSet<String>>();
		for(String line : input.split("\r\n")) {
			String[] chunks = line.split(" contain ");
			String topBagColor = chunks[0].split(" ")[0] + chunks[0].split(" ")[1];
			HashSet<String> containedBags = new HashSet<String>();
			String[] containWords = chunks[1].split(" ");
			if(containWords[0].equals("no")) {
				bags.put(topBagColor, containedBags);
				continue;
			}
			for(int i = 1; i < containWords.length; i += 4) {
				containedBags.add(containWords[i] + containWords[i+1]);
			}
			bags.put(topBagColor,containedBags);
		}
		
		String desiredBag = "shinygold";
		
		int count = 0;
		for(String s : bags.keySet()) {
			if(containsTree(desiredBag,bags.get(s),bags)) {
				count++;
			}
		}
		return Integer.toString(count);
	}
	
	public boolean containsTree(String type, HashSet<String> container, HashMap<String,HashSet<String>> a) {
		if(container.contains(type))
			return true;
		for(String key : container) {
			if(containsTree(type,a.get(key),a))
				return true;
		}
		return false;
	}

	@Override
	public String part2() {
		//now, bags must be string -> hashmap<string,integer> map
		HashMap<String, HashMap<String,Integer>> bags = new HashMap<String, HashMap<String,Integer>>();
		for(String line : input.split("\r\n")) {
			String[] chunks = line.split(" contain ");
			String topBagColor = chunks[0].split(" ")[0] + chunks[0].split(" ")[1];
			HashMap<String,Integer> containedBags = new HashMap<String,Integer>();
			String[] containWords = chunks[1].split(" ");
			if(containWords[0].equals("no")) {
				bags.put(topBagColor, containedBags);
				continue;
			}
			for(int i = 1; i < containWords.length; i += 4) {
				containedBags.put(containWords[i] + containWords[i+1], Integer.parseInt(containWords[i-1]));
			}
			bags.put(topBagColor,containedBags);
		}
		//off-by-one because root gold bag is counted
		return Integer.toString(bagsWithin("shinygold",bags) - 1);
	}
	
	public int bagsWithin(String bag, HashMap<String,HashMap<String,Integer>> a) {
		int bags = 1;
		for(String s : a.get(bag).keySet()) {
			//for each child, bag total is count * number of total recursive bags
			bags += a.get(bag).get(s) * bagsWithin(s,a);
		}
		return bags;
	}

	public static void main(String[] args) {
		DayRunner.run(new Day07());
	}

}
