package advent.aoc2015;

import advent.utilities.general.DayRunner;
import advent.utilities.general.IDay;

public class Day08 implements IDay {

	//for this one, double-check that your IDE/editor pastes in escape characters correctly
	
	String input = "\"qxfcsmh\"\r\n"
			+ "\"ffsfyxbyuhqkpwatkjgudo\"\r\n"
			+ "\"byc\\x9dyxuafof\\\\\\xa6uf\\\\axfozomj\\\\olh\\x6a\"\r\n"
			+ "\"jtqvz\"\r\n"
			+ "\"uzezxa\\\"jgbmojtwyfbfguz\"\r\n"
			+ "\"vqsremfk\\x8fxiknektafj\"\r\n"
			+ "\"wzntebpxnnt\\\"vqndz\\\"i\\x47vvjqo\\\"\"\r\n"
			+ "\"higvez\\\"k\\\"riewqk\"\r\n"
			+ "\"dlkrbhbrlfrp\\\\damiauyucwhty\"\r\n"
			+ "\"d\\\"\"\r\n"
			+ "\"qlz\"\r\n"
			+ "\"ku\"\r\n"
			+ "\"yy\\\"\\\"uoao\\\"uripabop\"\r\n"
			+ "\"saduyrntuswlnlkuppdro\\\\sicxosted\"\r\n"
			+ "\"tj\"\r\n"
			+ "\"zzphopswlwdhebwkxeurvizdv\"\r\n"
			+ "\"xfoheirjoakrpofles\\\"nfu\"\r\n"
			+ "\"q\\xb7oh\\\"p\\xce\\\"n\"\r\n"
			+ "\"qeendp\\\"ercwgywdjeylxcv\"\r\n"
			+ "\"dcmem\"\r\n"
			+ "\"\\\"i\\x13r\\\"l\"\r\n"
			+ "\"ikso\\xdcbvqnbrjduh\\\"uqudzki\\xderwk\"\r\n"
			+ "\"wfdsn\"\r\n"
			+ "\"pwynglklryhtsqbno\"\r\n"
			+ "\"hcoj\\x63iccz\\\"v\\\"ttr\"\r\n"
			+ "\"zf\\x23\\\\hlj\\\\kkce\\\\d\\\\asy\\\"yyfestwcdxyfj\"\r\n"
			+ "\"xs\"\r\n"
			+ "\"m\\\"tvltapxdvtrxiy\"\r\n"
			+ "\"bmud\"\r\n"
			+ "\"k\\\"a\"\r\n"
			+ "\"b\\\"oas\"\r\n"
			+ "\"\\\"yexnjjupoqsxyqnquy\\\"uzfdvetqrc\"\r\n"
			+ "\"vdw\\xe3olxfgujaj\"\r\n"
			+ "\"qomcxdnd\\\"\\\\cfoe\\\"\"\r\n"
			+ "\"fpul\"\r\n"
			+ "\"m\\\"avamefphkpv\"\r\n"
			+ "\"vvdnb\\\\x\\\\uhnxfw\\\"dpubfkxfmeuhnxisd\"\r\n"
			+ "\"hey\\\\\"\r\n"
			+ "\"ldaeigghlfey\"\r\n"
			+ "\"eure\\\"hoy\\xa5iezjp\\\\tm\"\r\n"
			+ "\"yygb\\\"twbj\\\\r\\\"\\x10gmxuhmp\\\"\"\r\n"
			+ "\"weirebp\\x39mqonbtmfmd\"\r\n"
			+ "\"ltuz\\\\hs\\\"e\"\r\n"
			+ "\"ysvmpc\"\r\n"
			+ "\"g\\x8amjtt\\\"megl\\\"omsaihifwa\"\r\n"
			+ "\"yimmm\"\r\n"
			+ "\"iiyqfalh\"\r\n"
			+ "\"cwknlaaf\"\r\n"
			+ "\"q\\x37feg\\xc6s\\\"xx\"\r\n"
			+ "\"uayrgeurgyp\\\\oi\"\r\n"
			+ "\"xhug\\\"pt\\\"axugllbdiggzhvy\"\r\n"
			+ "\"kdaarqmsjfx\\xc3d\"\r\n"
			+ "\"\\\"vkwla\"\r\n"
			+ "\"d\\\"\"\r\n"
			+ "\"tmroz\\\"bvfinxoe\\\\mum\\\"wmm\"\r\n"
			+ "\"\\\"n\\\"bbswxne\\\\p\\\\yr\\\"qhwpdd\"\r\n"
			+ "\"skzlkietklkqovjhvj\\xfe\"\r\n"
			+ "\"pbg\\\\pab\\\"bubqaf\\\"obzcwxwywbs\\\\dhtq\"\r\n"
			+ "\"xxjidvqh\\\"lx\\\\wu\\\"ij\"\r\n"
			+ "\"daef\\x5fe\\x5b\\\\kbeeb\\x13qnydtboof\"\r\n"
			+ "\"ogvazaqy\\\"j\\x73\"\r\n"
			+ "\"y\"\r\n"
			+ "\"n\\\"tibetedldy\\\\gsamm\\\"nwu\"\r\n"
			+ "\"wldkvgdtqulwkad\"\r\n"
			+ "\"dpmxnj\"\r\n"
			+ "\"twybw\\\"cdvf\\\"mjdajurokbce\"\r\n"
			+ "\"ru\\\"\\\\lasij\\\"i\"\r\n"
			+ "\"roc\\\\vra\\\\lhrm\"\r\n"
			+ "\"pbkt\\x60booz\\\"fjlkc\"\r\n"
			+ "\"j\\x4dytvjwrzt\"\r\n"
			+ "\"\\\\uiwjkniumxcs\"\r\n"
			+ "\"cbhm\\\"nexccior\\\"v\\\"j\\\"nazxilmfp\\x47\"\r\n"
			+ "\"qdxngevzrlgoq\"\r\n"
			+ "\"\\\"lrzxftytpobsdfyrtdqpjbpuwmm\\x9e\"\r\n"
			+ "\"mdag\\x0asnck\\xc2ggj\\\"slb\\\"fjy\"\r\n"
			+ "\"wyqkhjuazdtcgkcxvjkpnjdae\"\r\n"
			+ "\"aixfk\\xc0iom\\x21vueob\"\r\n"
			+ "\"dkiiakyjpkffqlluhaetires\"\r\n"
			+ "\"ysspv\\\"lysgkvnmwbbsy\"\r\n"
			+ "\"gy\\\"ryexcjjxdm\\\"xswssgtr\"\r\n"
			+ "\"s\"\r\n"
			+ "\"ddxv\"\r\n"
			+ "\"qwt\\\"\\x27puilb\\\"pslmbrsxhrz\"\r\n"
			+ "\"qdg\\xc9e\\\\qwtknlvkol\\x54oqvmchn\\\\\"\r\n"
			+ "\"lvo\"\r\n"
			+ "\"b\"\r\n"
			+ "\"fk\\\"aa\\\"\\\"yenwch\\\\\\\\on\"\r\n"
			+ "\"srig\\x63hpwaavs\\\\\\x80qzk\\\"xa\\\"\\xe6u\\\\wr\"\r\n"
			+ "\"yxjxuj\\\"ghyhhxfj\\\"\\xa6qvatre\"\r\n"
			+ "\"yoktqxjxkzrklkoeroil\"\r\n"
			+ "\"\\\"jfmik\\\"\"\r\n"
			+ "\"smgseztzdwldikbqrh\\\"\"\r\n"
			+ "\"jftahgctf\\\"hoqy\"\r\n"
			+ "\"tcnhicr\\\"znpgckt\\\"ble\"\r\n"
			+ "\"vqktnkodh\\\"lo\\\"a\\\\bkmdjqqnsqr\"\r\n"
			+ "\"ztnirfzqq\"\r\n"
			+ "\"s\"\r\n"
			+ "\"xx\"\r\n"
			+ "\"iqj\\\"y\\\\hqgzflwrdsusasekyrxbp\\\\ad\"\r\n"
			+ "\"\\\\xzjhlaiynkioz\\\"\\\"bxepzimvgwt\"\r\n"
			+ "\"s\\x36rbw\"\r\n"
			+ "\"mniieztwrisvdx\"\r\n"
			+ "\"atyfxioy\\x2b\\\\\"\r\n"
			+ "\"irde\\x85\\x5cvbah\\\\jekw\\\"ia\"\r\n"
			+ "\"bdmftlhkwrprmpat\\\"prfaocvp\"\r\n"
			+ "\"w\\\\k\"\r\n"
			+ "\"umbpausy\"\r\n"
			+ "\"zfauhpsangy\"\r\n"
			+ "\"p\\\"zqyw\"\r\n"
			+ "\"wtztypyqvnnxzvlvipnq\\\"zu\"\r\n"
			+ "\"deicgwq\\\\oqvajpbov\\\\or\\\"kgplwu\"\r\n"
			+ "\"mbzlfgpi\\\\\\\\zqcidjpzqdzxityxa\"\r\n"
			+ "\"lfkxvhma\"\r\n"
			+ "\"\\xf2yduqzqr\\\"\\\\fak\\\"p\\\"n\"\r\n"
			+ "\"mpajacfuxotonpadvng\"\r\n"
			+ "\"anb\\\\telzvcdu\\\\a\\xf2flfq\"\r\n"
			+ "\"lrs\\\"ebethwpmuuc\\\"\\x86ygr\"\r\n"
			+ "\"qmvdbhtumzc\\\"ci\"\r\n"
			+ "\"meet\"\r\n"
			+ "\"yopg\\x0fdxdq\\\"h\\\\ugsu\\xffmolxjv\"\r\n"
			+ "\"uhy\"\r\n"
			+ "\"fzgidrtzycsireghazscvmwcfmw\\\\t\"\r\n"
			+ "\"cqohkhpgvpru\"\r\n"
			+ "\"bihyigtnvmevx\\\"xx\"\r\n"
			+ "\"xz\"\r\n"
			+ "\"zofomwotzuxsjk\\\"q\\\"mc\\\"js\\\"dnmalhxd\"\r\n"
			+ "\"\\\\ktnddux\\\\fqvt\\\"ibnjntjcbn\"\r\n"
			+ "\"ia\"\r\n"
			+ "\"htjadnefwetyp\\xd5kbrwfycbyy\"\r\n"
			+ "\"\\\"\\\\hkuxqddnao\"\r\n"
			+ "\"meqqsz\\x83luecpgaem\"\r\n"
			+ "\"cvks\\x87frvxo\\\"svqivqsdpgwhukmju\"\r\n"
			+ "\"sgmxiai\\\\o\\\"riufxwjfigr\\xdf\"\r\n"
			+ "\"fgywdfecqufccpcdn\"\r\n"
			+ "\"faghjoq\\x28abxnpxj\"\r\n"
			+ "\"zuppgzcfb\\\"dctvp\\\"elup\\\"zxkopx\"\r\n"
			+ "\"xqs\\x45xxdqcihbwghmzoa\"\r\n"
			+ "\"anbnlp\\\\cgcvm\\\"hc\"\r\n"
			+ "\"xf\\\"fgrngwzys\"\r\n"
			+ "\"nrxsjduedcy\\x24\"\r\n"
			+ "\"\\x71sxl\\\"gj\\\"sds\\\"ulcruguz\\\\t\\\\ssvjcwhi\"\r\n"
			+ "\"jhj\\\"msch\"\r\n"
			+ "\"qpovolktfwyiuyicbfeeju\\x01\"\r\n"
			+ "\"nkyxmb\\\"qyqultgt\\\"nmvzvvnxnb\"\r\n"
			+ "\"ycsrkbstgzqb\\\"uv\\\\cisn\"\r\n"
			+ "\"s\"\r\n"
			+ "\"ueptjnn\\\"\\\"sh\"\r\n"
			+ "\"lp\\\"z\\\"d\\\"mxtxiy\"\r\n"
			+ "\"yzjtvockdnvbubqabjourf\\\"k\\\"uoxwle\"\r\n"
			+ "\"\\x82\\\"wqm\\\"\"\r\n"
			+ "\"\\xb5cwtuks\\x5fpgh\"\r\n"
			+ "\"wd\"\r\n"
			+ "\"tbvf\"\r\n"
			+ "\"ttbmzdgn\"\r\n"
			+ "\"vfpiyfdejyrlbgcdtwzbnm\"\r\n"
			+ "\"uc\"\r\n"
			+ "\"otdcmhpjagqix\"\r\n"
			+ "\"\\\\\\xb1qso\\\"s\"\r\n"
			+ "\"scowax\"\r\n"
			+ "\"behpstjdh\\xccqlgnqjyz\\\"eesn\"\r\n"
			+ "\"r\\xe1cbnjwzveoomkzlo\\\\kxlfouhm\"\r\n"
			+ "\"jgrl\"\r\n"
			+ "\"kzqs\\\\r\"\r\n"
			+ "\"ctscb\\x7fthwkdyko\\\"\\x62pkf\\\"d\\xe6knmhurg\"\r\n"
			+ "\"tc\\\"kw\\x3ftt\"\r\n"
			+ "\"bxb\\x5ccl\"\r\n"
			+ "\"jyrmfbphsldwpq\"\r\n"
			+ "\"jylpvysl\\\"\\\"juducjg\"\r\n"
			+ "\"en\\\\m\\\"kxpq\\\"wpb\\\\\\\"\"\r\n"
			+ "\"madouht\\\"bmdwvnyqvpnawiphgac\\\"\"\r\n"
			+ "\"vuxpk\\\"ltucrw\"\r\n"
			+ "\"aae\\x60arr\"\r\n"
			+ "\"ttitnne\\\"kilkrgssnr\\xfdurzh\"\r\n"
			+ "\"oalw\"\r\n"
			+ "\"pc\\\"\\\"gktkdykzbdpkwigucqni\\\"nxiqx\"\r\n"
			+ "\"dbrsaj\"\r\n"
			+ "\"bgzsowyxcbrvhtvekhsh\\\"qgd\"\r\n"
			+ "\"kudfemvk\\\"\\\"\\\"hkbrbil\\\"chkqoa\"\r\n"
			+ "\"zjzgj\\\\ekbhyfzufy\"\r\n"
			+ "\"\\\\acos\\\"fqekuxqzxbmkbnn\\x1ejzwrm\"\r\n"
			+ "\"elxahvudn\\\"txtmomotgw\"\r\n"
			+ "\"\\x2eoxmwdhelpr\\\"cgi\\xf7pzvb\"\r\n"
			+ "\"eapheklx\"\r\n"
			+ "\"hfvma\\\"mietvc\\\"tszbbm\\\"czex\"\r\n"
			+ "\"h\\\"iiockj\\\\\\xc1et\"\r\n"
			+ "\"d\\\"rmjjftm\"\r\n"
			+ "\"qlvhdcbqtyrhlc\\\\\"\r\n"
			+ "\"yy\\\"rsucjtulm\\\"coryri\\\"eqjlbmk\"\r\n"
			+ "\"tv\"\r\n"
			+ "\"r\\\"bfuht\\\\jjgujp\\\"\"\r\n"
			+ "\"kukxvuauamtdosngdjlkauylttaokaj\"\r\n"
			+ "\"srgost\\\"\\\"rbkcqtlccu\\x65ohjptstrjkzy\"\r\n"
			+ "\"yxwxl\\\\yjilwwxffrjjuazmzjs\"\r\n"
			+ "\"dxlw\\\\fkstu\\\"hjrtiafhyuoh\\\"sewabne\"\r\n"
			+ "\"\\x88sj\\\"v\"\r\n"
			+ "\"rfzprz\\xec\\\"oxqclu\\\"krzefp\\\\q\"\r\n"
			+ "\"cfmhdbjuhrcymgxpylllyvpni\"\r\n"
			+ "\"ucrmjvmimmcq\\x88\\xd9\\\"lz\"\r\n"
			+ "\"lujtt\\\"\"\r\n"
			+ "\"gvbqoixn\\\"pmledpjmo\\\"flydnwkfxllf\"\r\n"
			+ "\"dvxqlbshhmelsk\\x8big\\\"l\"\r\n"
			+ "\"mx\\x54lma\\x8bbguxejg\"\r\n"
			+ "\"\\x66jdati\\xeceieo\"\r\n"
			+ "\"\\\"iyyupixei\\x54ff\"\r\n"
			+ "\"xohzf\\\"rbxsoksxamiu\"\r\n"
			+ "\"vlhthspeshzbppa\\x4drhqnohjop\\\"\\\"mfjd\"\r\n"
			+ "\"f\\\"tvxxla\\\"vurian\\\"\\\"idjq\\x3aptm\\xc3olep\"\r\n"
			+ "\"gzqz\"\r\n"
			+ "\"kbq\\\\wogye\\\\altvi\\\\hbvmodny\"\r\n"
			+ "\"j\\xd8\"\r\n"
			+ "\"ofjozdhkblvndl\"\r\n"
			+ "\"hbitoupimbawimxlxqze\"\r\n"
			+ "\"ypeleimnme\"\r\n"
			+ "\"xfwdrzsc\\\\oxqamawyizvi\\\\y\"\r\n"
			+ "\"enoikppx\\xa1ixe\\\"yo\\\"gumye\"\r\n"
			+ "\"fb\"\r\n"
			+ "\"vzf\"\r\n"
			+ "\"zxidr\"\r\n"
			+ "\"cu\\x31beirsywtskq\"\r\n"
			+ "\"lxpjbvqzztafwezd\"\r\n"
			+ "\"\\\\jyxeuo\\x18bv\"\r\n"
			+ "\"b\\\"vawc\\\"p\\\\\\\\giern\\\"b\"\r\n"
			+ "\"odizunx\\\"\\\"t\\\\yicdn\\\"x\\\"sdiz\"\r\n"
			+ "\"\\\"\\\"tebrtsi\"\r\n"
			+ "\"ctyzsxv\\xa6pegfkwsi\\\"tgyltaakytccb\"\r\n"
			+ "\"htxwbofchvmzbppycccliyik\\xe5a\"\r\n"
			+ "\"ggsslefamsklezqkrd\"\r\n"
			+ "\"rcep\\\"fnimwvvdx\\\"l\"\r\n"
			+ "\"zyrzlqmd\\x12egvqs\\\\llqyie\"\r\n"
			+ "\"\\x07gsqyrr\\\\rcyhyspsvn\"\r\n"
			+ "\"butg\\\"\"\r\n"
			+ "\"gb\"\r\n"
			+ "\"gywkoxf\\\"jsg\\\\wtopxvumirqxlwz\"\r\n"
			+ "\"rj\\\"ir\\\"wldwveair\\x2es\\\"dhjrdehbqnzl\"\r\n"
			+ "\"ru\\\"elktnsbxufk\\\\ejufjfjlevt\\\\lrzd\"\r\n"
			+ "\"\\\"widsvok\"\r\n"
			+ "\"oy\\\"\\x81nuesvw\"\r\n"
			+ "\"ay\"\r\n"
			+ "\"syticfac\\x1cfjsivwlmy\\\"pumsqlqqzx\"\r\n"
			+ "\"m\"\r\n"
			+ "\"rjjkfh\\x78cf\\x2brgceg\\\"jmdyas\\\"\\\\xlv\\xb6p\"\r\n"
			+ "\"tmuvo\\\"\\x3ffdqdovjmdmkgpstotojkv\\\"as\"\r\n"
			+ "\"jd\\\\ojvynhxllfzzxvbn\\\"wrpphcvx\"\r\n"
			+ "\"pz\"\r\n"
			+ "\"\\\"twr\"\r\n"
			+ "\"n\\\\hdzmxe\\\"mzjjeadlz\"\r\n"
			+ "\"fb\\\"rprxuagvahjnri\"\r\n"
			+ "\"rfmexmjjgh\\\\xrnmyvnatrvfruflaqjnd\"\r\n"
			+ "\"obbbde\\\"co\\\"qr\\\"qpiwjgqahqm\\\\jjp\\\"\"\r\n"
			+ "\"vpbq\\\"\\\"y\\\"czk\\\\b\\x52ed\\\"lnzepobp\"\r\n"
			+ "\"syzeajzfarplydipny\\\"y\\\"\\xe8ad\"\r\n"
			+ "\"mpyodwb\"\r\n"
			+ "\"\\x47rakphlqqptd\"\r\n"
			+ "\"wa\\\"oj\\\"aiy\"\r\n"
			+ "\"a\"\r\n"
			+ "\"ropozx\"\r\n"
			+ "\"q\\x51nbtlwa\"\r\n"
			+ "\"etukvgx\\\\jqxlkq\"\r\n"
			+ "\"\\\"tp\\\"rah\\\"pg\\\"s\\\"bpdtes\\\\tkasdhqd\"\r\n"
			+ "\"dn\\\"qqpkikadowssb\\xcah\\\"dzpsf\\\\ect\\\"jdh\"\r\n"
			+ "\"pxunovbbrrn\\\\vullyn\\\"bno\\\"\\\"\\\"myfxlp\\\"\"\r\n"
			+ "\"qaixyazuryvkmoulhcqaotegfj\\\\mpzm\"\r\n"
			+ "\"bvfrbicutzbjwn\\\\oml\\\"cf\\\"d\\\"ezcpv\\\"j\"\r\n"
			+ "\"rmbrdtneudemigdhelmb\"\r\n"
			+ "\"aq\\\\aurmbhy\"\r\n"
			+ "\"wujqvzw\"\r\n"
			+ "\"gf\\\"tssmvm\\\"gm\\\"hu\\x9a\\xb7yjawsa\"\r\n"
			+ "\"hrhqqxow\\xe2gsydtdspcfqy\\\"zw\\\\ou\"\r\n"
			+ "\"ianwwf\\\\yko\\\\tdujhhqdi\"\r\n"
			+ "\"xylz\\\"zpvpab\"\r\n"
			+ "\"lwuopbeeegp\"\r\n"
			+ "\"aoop\\x49jhhcexdmdtun\"\r\n"
			+ "\"\\\\\\\\mouqqcsgmz\"\r\n"
			+ "\"tltuvwhveau\\x43b\\\"ymxjlcgiymcynwt\"\r\n"
			+ "\"gsugerumpyuhtjljbhrdyoj\"\r\n"
			+ "\"lnjm\\xb8wg\\\"ajh\"\r\n"
			+ "\"zmspue\\\"nfttdon\\\\b\\\"eww\"\r\n"
			+ "\"\\\"w\\x67jwaq\\x7ernmyvs\\\\rmdsuwydsd\\\"th\"\r\n"
			+ "\"ogtgvtlmcvgllyv\"\r\n"
			+ "\"z\\\"fqi\\\"rvddoehrciyl\"\r\n"
			+ "\"yustxxtot\\\"muec\\\"xvfdbzunzvveq\"\r\n"
			+ "\"mqslw\"\r\n"
			+ "\"txqnyvzmibqgjs\\xb6xy\\x86nfalfyx\"\r\n"
			+ "\"kzhehlmkholov\"\r\n"
			+ "\"plpmywcnirrjutjguosh\\\\\"\r\n"
			+ "\"pydbnqofv\\\"dn\\\\m\"\r\n"
			+ "\"aegqof\"\r\n"
			+ "\"eambmxt\\\\dxagoogl\\\\zapfwwlmk\"\r\n"
			+ "\"afbmqitxxqhddlozuxcpjxgh\"\r\n"
			+ "\"vgts\"\r\n"
			+ "\"bfdpqtoxzzhmzcilehnflna\"\r\n"
			+ "\"s\\\"idpz\"\r\n"
			+ "\"\\xcfhgly\\\"nlmztwybx\\\"ecezmsxaqw\"\r\n"
			+ "\"aackfgndqcqiy\"\r\n"
			+ "\"\\x22unqdlsrvgzfaohoffgxzfpir\\\"s\"\r\n"
			+ "\"abh\\\"ydv\\\"kbpdhrerl\"\r\n"
			+ "\"bdzpg\"\r\n"
			+ "\"ekwgkywtmzp\"\r\n"
			+ "\"wtoodejqmrrgslhvnk\\\"pi\\\"ldnogpth\"\r\n"
			+ "\"njro\\x68qgbx\\xe4af\\\"\\\\suan\"";
	
	@Override
	public String part1() {
		int total = 0;
		//iterate over lines
		for(String s : input.split("\r\n")) {
			//calculate code length
			int codeLength = s.length();
			//initialize mem length to same value as code length
			int memLength = codeLength;
			//decrease mem length as characters that are parsed out appear
			for(int i = 0; i < s.length(); i++) {
				if(s.charAt(i) == '\\') {
					//decrease mem length by 4 for ascii characters
					if(s.charAt(i+1) == 'x') {
						memLength -= 3;
						i += 3;
					//decrease by 1 for single-escape characters
					} else {
						memLength--;
						i++;
					}
				//count unescaped quotes
				} else if(s.charAt(i) == '"') {
					memLength--;
				}
						
			}
			total += (codeLength - memLength);
		}
		return Integer.toString(total);
	}

	@Override
	public String part2() {
		int total = 0;
		//iterate over lines
		for(String s : input.split("\r\n")) {
			//calculate code length
			int codeLength = s.length();
			//initialize mem length to same value as code length
			int memLength = codeLength;
			//increase mem length as characters that requre escaping appear
			for(int i = 0; i < s.length(); i++) {
				if(s.charAt(i) == '\\' || s.charAt(i) == '"') {
					memLength++;
				}		
			}
			//account for opening and closing quotes
			memLength += 2;
			total += (memLength - codeLength);
		}
		return Integer.toString(total);
	}

	public static void main(String[] args) {
		DayRunner.run(new Day08());
	}

}
