package advent.aoc2017;

import java.util.ArrayList;
import java.util.Collections;

import advent.utilities.general.DayRunner;
import advent.utilities.general.IDay;
import advent.utilities.utils2017.TreeNode;

public class Day07 implements IDay {

	String input = "nzyiue (57)\r\n"
			+ "pdmkag (39)\r\n"
			+ "bogbg (13)\r\n"
			+ "nubay (45)\r\n"
			+ "dukzh (17)\r\n"
			+ "kpjxln (44) -> dzzbvkv, gzdxgvj, wsocb, jidxg\r\n"
			+ "cxjyxl (83)\r\n"
			+ "vusplt (151) -> mcfst, orrwx\r\n"
			+ "mxrfq (98)\r\n"
			+ "bdoez (62)\r\n"
			+ "vrajpg (78)\r\n"
			+ "qzsowpu (90)\r\n"
			+ "nrxoha (51)\r\n"
			+ "xtjrkv (351) -> jlbhafs, pyocxtt\r\n"
			+ "rlnii (18986) -> xjosf, ljvpv, wkumzkr\r\n"
			+ "ddrrgp (23)\r\n"
			+ "wladmn (42)\r\n"
			+ "ryskzh (209) -> wsyya, xbqpjo\r\n"
			+ "jbjkp (34)\r\n"
			+ "fnfiur (86)\r\n"
			+ "zxzkl (82)\r\n"
			+ "hbmxey (1869) -> khkuxc, mjuwde, tztycfl, miauii\r\n"
			+ "zjyqcfa (97)\r\n"
			+ "zbtck (48)\r\n"
			+ "mgsasl (39)\r\n"
			+ "cemygp (34)\r\n"
			+ "iolrkmv (139) -> rntjx, itxtmhb\r\n"
			+ "jzmqzl (1446) -> pptocz, mwfryd, utgkveb, sflwom\r\n"
			+ "wagpkyw (88)\r\n"
			+ "saiyjff (67)\r\n"
			+ "kwwhb (219) -> htvpmr, rojhup\r\n"
			+ "huspq (74)\r\n"
			+ "mzrafi (44)\r\n"
			+ "fchlc (89)\r\n"
			+ "ezkddph (62)\r\n"
			+ "zehnmg (5)\r\n"
			+ "tgirh (50)\r\n"
			+ "xantdh (73)\r\n"
			+ "zicvvl (10)\r\n"
			+ "kcimi (86) -> uwizfa, kmhyz, wagpkyw, iuovz\r\n"
			+ "wsocb (64)\r\n"
			+ "aemffo (284) -> dukzh, vczudlu, tpubu\r\n"
			+ "gfgoc (18)\r\n"
			+ "bmovg (80)\r\n"
			+ "trsnrjd (89) -> oujkd, fstzdn\r\n"
			+ "bmqiwai (12928) -> yqeaqcn, cgzyc, bwgkn, giftd, hdhvzi\r\n"
			+ "ktehtif (151) -> fvplhrm, jesphm\r\n"
			+ "jkfyg (76) -> ajeisgv, jfrooen, hvhtokr\r\n"
			+ "dkfepj (1970) -> tgirh, mnsqjxv\r\n"
			+ "jjseenh (99)\r\n"
			+ "jvpecm (7) -> dpyuayl, lyigbhi, bflxonp, tvcyh, tddik\r\n"
			+ "silklk (59)\r\n"
			+ "swscfel (68)\r\n"
			+ "dilefzx (89)\r\n"
			+ "spthyf (75)\r\n"
			+ "tiiwbg (17)\r\n"
			+ "ayqgp (58)\r\n"
			+ "qhygx (14)\r\n"
			+ "hqccsb (26) -> bdkfx, srrxb\r\n"
			+ "lbojqfo (34)\r\n"
			+ "arbebt (32)\r\n"
			+ "fsvkj (115) -> ftqtzxk, twzgms, otvvje\r\n"
			+ "sdigtox (39)\r\n"
			+ "awsphe (79)\r\n"
			+ "lftlc (35)\r\n"
			+ "apzabs (68)\r\n"
			+ "aboilvw (452)\r\n"
			+ "rntylx (44)\r\n"
			+ "xhhfsuw (280)\r\n"
			+ "yucwtc (41)\r\n"
			+ "qlgkqk (54) -> sqfrw, acdkw, ycinfxk, wcinck, hyfswg\r\n"
			+ "thneyz (57)\r\n"
			+ "pplkoa (79)\r\n"
			+ "vsxzpf (197) -> spyxh, yvcbk, fkmccg\r\n"
			+ "miymiit (1002) -> lmmeg, jxulvx, yqergs\r\n"
			+ "jaamgi (45)\r\n"
			+ "tvwosmc (1462) -> frvmu, qmfmfxh, jemmk\r\n"
			+ "ngemsu (85)\r\n"
			+ "ohiftl (143) -> loggp, xhwfcu\r\n"
			+ "bztor (157) -> gjfkx, grsdifs, spchmoq\r\n"
			+ "tifkr (52)\r\n"
			+ "kgctcau (82)\r\n"
			+ "yvcbk (32)\r\n"
			+ "srvwd (1234) -> dxerl, pzjsf, yqyyoj\r\n"
			+ "xrise (358)\r\n"
			+ "biwdu (70) -> kvpju, hlullj, bfpvsfz, fvfitqc\r\n"
			+ "utgkveb (76) -> fmhjs, pplkoa, mznkfco\r\n"
			+ "mvhqou (22) -> njgzn, okfcek, zjyqcfa, culvtcm\r\n"
			+ "gadyi (398) -> ndxim, efwhif\r\n"
			+ "ujzofuy (39)\r\n"
			+ "jjgem (852) -> hnvybq, gnffzh, fbuklc\r\n"
			+ "rbucosf (122) -> jvpgl, yuhioxl\r\n"
			+ "ffxnegs (222) -> zfcylzq, xjxjaq, cocau, vusplt, cjlxgf, yjonn, iazte\r\n"
			+ "wrtyhxg (403) -> zqckoxe, vindf, jbvugg, idivffq\r\n"
			+ "imbpvgl (52)\r\n"
			+ "frrvvai (193) -> gxcnp, zvjrwke\r\n"
			+ "ywlrls (31) -> gqdxrur, dfyqo, cxndroi, gbpcav\r\n"
			+ "olzdhtj (42)\r\n"
			+ "thvjlgo (76) -> cufudi, jdyspx\r\n"
			+ "jearhat (57)\r\n"
			+ "jxanwhq (27)\r\n"
			+ "wsyya (98)\r\n"
			+ "tahstqe (37)\r\n"
			+ "dyvooj (80)\r\n"
			+ "yuypmb (98)\r\n"
			+ "uehdbi (26)\r\n"
			+ "inspqeu (34)\r\n"
			+ "nxqqsza (119) -> guxwd, iyxkzat\r\n"
			+ "jgkmy (86)\r\n"
			+ "hllzej (154) -> sodrm, ekfpabq, utqxb\r\n"
			+ "gcbvf (68)\r\n"
			+ "ctoxz (98)\r\n"
			+ "advlxrg (22)\r\n"
			+ "eetxll (37)\r\n"
			+ "lmpauyz (72)\r\n"
			+ "lwxts (76)\r\n"
			+ "rkuyxrc (55)\r\n"
			+ "pitdti (55)\r\n"
			+ "ucjew (91)\r\n"
			+ "gynwftf (91)\r\n"
			+ "czojwyg (15)\r\n"
			+ "uigoxw (75)\r\n"
			+ "rcjqfuo (129) -> lgoak, zcomcn\r\n"
			+ "vvkbav (56)\r\n"
			+ "npcyutn (35)\r\n"
			+ "jfaoy (57)\r\n"
			+ "iqcgwzk (58) -> pdepl, zxeopkg, dukqd, gxdtiob, ylnvdoq\r\n"
			+ "rqnsxm (2056) -> jaxig, bolxwme, dgsse\r\n"
			+ "bsyiv (38)\r\n"
			+ "hhnpg (164) -> dmvajb, pvwdkm\r\n"
			+ "oydoajo (87)\r\n"
			+ "fowpeur (85)\r\n"
			+ "ycnih (17)\r\n"
			+ "zwpyj (12)\r\n"
			+ "wpprf (97) -> fdthu, sxslizl\r\n"
			+ "icqsww (55)\r\n"
			+ "ckedyqu (54)\r\n"
			+ "ageyuq (19)\r\n"
			+ "ebrgtq (112) -> bochc, wqdvql, ogafygg\r\n"
			+ "ygteuy (89)\r\n"
			+ "tuhxr (76)\r\n"
			+ "rvuvico (91)\r\n"
			+ "ecjujqu (92)\r\n"
			+ "tvhgbau (79)\r\n"
			+ "zvsnz (26)\r\n"
			+ "fquywyi (308)\r\n"
			+ "gqrgh (24)\r\n"
			+ "zcfswa (37)\r\n"
			+ "hkbxj (55)\r\n"
			+ "cnknlru (70) -> udfuty, sawqp\r\n"
			+ "jljnags (38)\r\n"
			+ "tztycfl (939) -> rrtqyew, gqzemw, hsfxq\r\n"
			+ "xzyri (187) -> yakzm, zkikhk\r\n"
			+ "sdzoy (51)\r\n"
			+ "ojtrl (130) -> hpgktb, pjkwlmk, phkvcix, zguqo\r\n"
			+ "lyhok (95) -> hdpemqh, nfvsrpa, bwthm, bilzbf, nrlvovz, iqcgwzk, sljgt\r\n"
			+ "hpanc (17)\r\n"
			+ "ykvtr (51)\r\n"
			+ "qbbmsf (97)\r\n"
			+ "ppfyonm (98) -> ylwniqh, ecjrblb\r\n"
			+ "jdsdqzd (32)\r\n"
			+ "oujkd (97)\r\n"
			+ "dpija (23)\r\n"
			+ "pdjnnzd (85)\r\n"
			+ "ghzqyv (37)\r\n"
			+ "yvlxoom (58) -> yxoqwg, wgwkss\r\n"
			+ "gjupqe (180) -> oszyw, zyqqzou\r\n"
			+ "qmfmfxh (7) -> rkgxu, unrhnl\r\n"
			+ "hxlefwp (268) -> yablonq, ouxjkf\r\n"
			+ "fdthu (86)\r\n"
			+ "voonmio (63)\r\n"
			+ "uxlcvt (143) -> scipnb, veutu\r\n"
			+ "xybcccw (7)\r\n"
			+ "inomnjg (91)\r\n"
			+ "gfuxooq (221) -> aceiy, axtzeb\r\n"
			+ "xirqz (71)\r\n"
			+ "tuqzsn (73) -> hueqfk, hcyohc, nerlvh\r\n"
			+ "jaxig (82) -> llofnny, snvqyqb\r\n"
			+ "czztmlk (61)\r\n"
			+ "ffrilz (148) -> qnvzqc, ckedyqu\r\n"
			+ "ejslpy (5616) -> wwcih, jzdmjdf, gnrqrsj, ayirpk, kvifa, bapvub\r\n"
			+ "bfwbkxq (493) -> hiqhe, ouqwmnj, wqxcn, jkfyg\r\n"
			+ "upftju (48)\r\n"
			+ "bqcizg (67)\r\n"
			+ "mkyqul (5)\r\n"
			+ "wjjar (296) -> ywutc, nsvrfae\r\n"
			+ "pabgfh (244) -> bogbg, hgcxyx, siisskc\r\n"
			+ "oltky (7)\r\n"
			+ "aeapmwq (76)\r\n"
			+ "btjxv (35) -> wpgyc, ripmztc\r\n"
			+ "onuxzz (247)\r\n"
			+ "ahayh (54732) -> byrvfhp, rokie, ejslpy\r\n"
			+ "idooz (192) -> owxuzp, uehdbi\r\n"
			+ "ghjpcv (162) -> xucdiz, ygrbgm, yxqesmi, ebktv\r\n"
			+ "zhffrzu (42)\r\n"
			+ "bpygf (26)\r\n"
			+ "tojpm (42)\r\n"
			+ "iihzs (67) -> hkbxj, enekg\r\n"
			+ "ydpihb (46)\r\n"
			+ "rgssc (27)\r\n"
			+ "dkgsvl (82)\r\n"
			+ "qrfhxne (65)\r\n"
			+ "sntuz (68)\r\n"
			+ "oznhe (98) -> tgvdjhh, cpvlq\r\n"
			+ "evfqyvl (304)\r\n"
			+ "qftqq (27)\r\n"
			+ "yxcbn (11)\r\n"
			+ "buifcn (15)\r\n"
			+ "xbpqmua (25)\r\n"
			+ "vjroix (85)\r\n"
			+ "evqrr (48)\r\n"
			+ "unrhnl (88)\r\n"
			+ "ihuzl (35)\r\n"
			+ "giftd (1250) -> zbedu, vyaoad, qcolnc\r\n"
			+ "uqjmbb (17)\r\n"
			+ "egulpbe (80)\r\n"
			+ "fpmwz (218)\r\n"
			+ "nihmyu (98)\r\n"
			+ "avaoo (176) -> xxshup, xsufhnb\r\n"
			+ "fmqon (61)\r\n"
			+ "mbokr (57)\r\n"
			+ "gprznw (41)\r\n"
			+ "bflxonp (105) -> pdmsm, jearhat\r\n"
			+ "oylgfzb (65) -> rugzyaj, hbgyu, rlnii, gwznzk, bmqiwai\r\n"
			+ "cepqh (19)\r\n"
			+ "hfjhadi (58)\r\n"
			+ "ajtkddh (60)\r\n"
			+ "vyadxnv (94) -> pyntdrr, mdpcfvu, cbvjwlo, ijleirw, sltrdk, adueu, qlkqplv\r\n"
			+ "anvvug (1847) -> tfuxhhz, kgctcau\r\n"
			+ "tjobe (129) -> hdspavt, mcduq\r\n"
			+ "qvgeei (273)\r\n"
			+ "dkxsqjt (1416) -> cuwqi, fcoxtp, yvlxoom\r\n"
			+ "urwgjd (39)\r\n"
			+ "vxqcf (105) -> gfnapwr, lmpauyz\r\n"
			+ "etnkepp (5)\r\n"
			+ "koyke (15)\r\n"
			+ "qqhjlu (78)\r\n"
			+ "glguoq (75)\r\n"
			+ "hdvfyp (7) -> eoaprcr, cksyln, hknzmvs\r\n"
			+ "pqvid (15)\r\n"
			+ "jesphm (6)\r\n"
			+ "bdkfx (81)\r\n"
			+ "gqdxrur (77)\r\n"
			+ "fmifd (94)\r\n"
			+ "ijiqjtf (63)\r\n"
			+ "dfyqo (77)\r\n"
			+ "spchmoq (31)\r\n"
			+ "tvcyh (149) -> lqbtnb, matcdld\r\n"
			+ "ilzwrk (64)\r\n"
			+ "tdtznh (64) -> phacwjs, offas\r\n"
			+ "tygst (91)\r\n"
			+ "uzjoys (198) -> bgcjrf, zdrfiw\r\n"
			+ "wfbuzbg (47) -> qpuyqq, ajrcal\r\n"
			+ "kwqcbe (19)\r\n"
			+ "qdovgra (303) -> zziyhz, gfgoc\r\n"
			+ "vfcbliu (19)\r\n"
			+ "fwtfkp (325)\r\n"
			+ "rmdqvgh (61)\r\n"
			+ "dtjzr (28)\r\n"
			+ "cocau (77) -> ficmghd, nkejtw, qowyx\r\n"
			+ "aftsom (70)\r\n"
			+ "fsmzljm (123) -> tatjry, hnfeims\r\n"
			+ "lwufmc (45)\r\n"
			+ "fzzcxvm (61)\r\n"
			+ "cxokosi (70) -> sszzop, gatdr\r\n"
			+ "mmlra (32) -> wdlwryo, wpprf, jexreg, lzowumq, rcjqfuo, lhnevgo, smuybnw\r\n"
			+ "tydlqpq (160) -> fsbojm, mjlmuca\r\n"
			+ "oevvote (68) -> silklk, polrzc, erysec, xoyjtol\r\n"
			+ "fxsatsm (83) -> sntuz, qgxcbt\r\n"
			+ "cvvtz (80) -> vpjhl, rgssc\r\n"
			+ "feonsg (74)\r\n"
			+ "htvpmr (7)\r\n"
			+ "gqzemw (43) -> pxdgkik, jtvntr\r\n"
			+ "pvpqoq (17)\r\n"
			+ "ldfmurk (88) -> fubtwbq, ycawl, sqsqge, aemffo, mszwp\r\n"
			+ "aufym (51)\r\n"
			+ "ldflo (188)\r\n"
			+ "izyjved (5)\r\n"
			+ "zgydn (72)\r\n"
			+ "cqfri (9)\r\n"
			+ "ytnti (150) -> lamtp, fugeht\r\n"
			+ "appkqpe (95)\r\n"
			+ "sjxbk (117) -> tinbqcj, amwtic\r\n"
			+ "fbvvrqt (81)\r\n"
			+ "vlwjehz (22)\r\n"
			+ "lwhev (44) -> zesvlul, wmwzhjg, hpjgrb, sxbusu\r\n"
			+ "hugfkt (42)\r\n"
			+ "tnobvt (18)\r\n"
			+ "zesvlul (73)\r\n"
			+ "gfnapwr (72)\r\n"
			+ "tabzzo (62) -> rvuvico, inomnjg\r\n"
			+ "ixdcgsa (177) -> gmhxee, cogovv\r\n"
			+ "fnvgp (85)\r\n"
			+ "awhwxdm (91)\r\n"
			+ "frgot (59)\r\n"
			+ "boete (78) -> ionnnfx, vytdgko, ouhfxyf\r\n"
			+ "ikxewmm (14)\r\n"
			+ "qfkka (49)\r\n"
			+ "xidye (11)\r\n"
			+ "krdlzf (115)\r\n"
			+ "hxjhcuc (694) -> miuvc, iolrkmv, trsnrjd\r\n"
			+ "ikbkb (136) -> uigoxw, spthyf\r\n"
			+ "yqeaqcn (53) -> qysdgq, mkjvhl, evfqyvl, bhzbv, usuujhq, hxlefwp\r\n"
			+ "dnrxyh (887) -> xthhlfy, fxsatsm, cqpns, xzyri\r\n"
			+ "siswh (41)\r\n"
			+ "pfxrf (51)\r\n"
			+ "dlzgufq (7462) -> ldfmurk, dnrxyh, dzetsz\r\n"
			+ "whlfwr (46)\r\n"
			+ "gbiluq (11)\r\n"
			+ "euaceg (42)\r\n"
			+ "iwdesog (152) -> cqyluwl, dbeskg\r\n"
			+ "afjmzb (15)\r\n"
			+ "sofxmjx (83)\r\n"
			+ "ortcrq (18)\r\n"
			+ "phacwjs (58)\r\n"
			+ "uiwgpi (995) -> hqvvrd, caihc, rvxed\r\n"
			+ "oiyxr (86) -> zibbm, sbklnq\r\n"
			+ "yukoxaw (27)\r\n"
			+ "orrwx (47)\r\n"
			+ "tlxbtng (44)\r\n"
			+ "ayirpk (1850) -> cdkcn, wbllfh, xounvb\r\n"
			+ "lqjznss (67)\r\n"
			+ "mldkiku (55)\r\n"
			+ "dyfhy (58)\r\n"
			+ "jxulvx (34) -> ujzjt, ykmej\r\n"
			+ "yuhioxl (20)\r\n"
			+ "uwiza (106) -> lddiw, hxaza, bnvjmae, oltky\r\n"
			+ "hpsxqdm (41) -> luzcpkn, azdklp, rupdbwl, vwqog\r\n"
			+ "fubtwbq (211) -> bdoez, ezkddph\r\n"
			+ "cwgbjaq (41)\r\n"
			+ "kmhyz (88)\r\n"
			+ "tpubu (17)\r\n"
			+ "bfrbwb (27)\r\n"
			+ "mgwauar (8)\r\n"
			+ "ixwyi (13)\r\n"
			+ "ljugvh (7) -> nxrkz, gnwjseo, ibjbozh, iaiywwa, pcdtne, nvtbk, vobfi\r\n"
			+ "rcongvf (20)\r\n"
			+ "csqyn (46)\r\n"
			+ "ygbyt (15)\r\n"
			+ "gwznzk (11) -> ehqavsc, yimottm, heuyaxx, yirkbjn, fqhag, ovqhdvy, zzxlo\r\n"
			+ "wwcih (1585) -> dyveac, pejho, cyfuwdb, tojnst\r\n"
			+ "alqog (157) -> dyvooj, wvkaie\r\n"
			+ "qecgvu (19)\r\n"
			+ "jexreg (209) -> bonnse, phgkg\r\n"
			+ "vbisx (49)\r\n"
			+ "bcukkvc (72)\r\n"
			+ "trcbs (90)\r\n"
			+ "xjxjaq (211) -> kfhwxyy, vnmxsi\r\n"
			+ "uptgby (16) -> eocoy, lqjznss, petluuh\r\n"
			+ "rjnht (63)\r\n"
			+ "urhwog (146) -> mxscf, fwqru\r\n"
			+ "caihc (158) -> kzjkjz, rjijdre\r\n"
			+ "mwjtydb (15)\r\n"
			+ "eqahcc (73)\r\n"
			+ "rntjx (72)\r\n"
			+ "ripmztc (96)\r\n"
			+ "cksyln (93)\r\n"
			+ "ktfeae (20) -> asoirn, jbxnffu, feonsg\r\n"
			+ "bdukt (71)\r\n"
			+ "jtxbfm (55)\r\n"
			+ "ebwtpod (66)\r\n"
			+ "fjerhwe (50)\r\n"
			+ "xxshup (66)\r\n"
			+ "jdyspx (97)\r\n"
			+ "nyxiai (73) -> pjmci, ejvaoj, fbiqxqk\r\n"
			+ "dxznun (49)\r\n"
			+ "umwial (183)\r\n"
			+ "mnsqjxv (50)\r\n"
			+ "wtoive (80) -> nfcru, goicjt\r\n"
			+ "zkzefwh (22)\r\n"
			+ "oszyw (78)\r\n"
			+ "ekxdjlp (60)\r\n"
			+ "tymor (6)\r\n"
			+ "jbydxyp (66)\r\n"
			+ "dzlqgrt (43)\r\n"
			+ "grsdifs (31)\r\n"
			+ "pdepl (238) -> ulezwmd, fhlul\r\n"
			+ "mbunh (8)\r\n"
			+ "iwajy (70)\r\n"
			+ "lknchr (68) -> nercz, skmvkj\r\n"
			+ "klpctiz (75)\r\n"
			+ "lazlx (8)\r\n"
			+ "fbuhz (159) -> aarioi, fbrvfk\r\n"
			+ "kvifa (69) -> fquywyi, ndmcgpn, vczcept, rjhfcl, jatvkwy, fodud, avaoo\r\n"
			+ "ilydn (74)\r\n"
			+ "nerlvh (85)\r\n"
			+ "qqduoo (735) -> wgglzpb, tcrkcu, boete\r\n"
			+ "gfxnuuk (34)\r\n"
			+ "amwtic (72)\r\n"
			+ "ltpban (87)\r\n"
			+ "klyso (67) -> qenjyl, egabi, hmdwqdq\r\n"
			+ "jotxc (57)\r\n"
			+ "cqyluwl (9)\r\n"
			+ "siyuvy (52)\r\n"
			+ "bbsomm (61) -> izonhi, jjseenh\r\n"
			+ "pzjsf (49) -> etnuzv, hrrampl\r\n"
			+ "vshekb (34)\r\n"
			+ "zvjrwke (27)\r\n"
			+ "xekggcw (89) -> tvwosmc, dpfov, anvvug, fneqe\r\n"
			+ "hsulvq (78)\r\n"
			+ "idivffq (292)\r\n"
			+ "bapvub (821) -> acnvtg, lvkpx, zeopgv, dcpnyer\r\n"
			+ "ziwkz (331) -> eqzuic, qrtwjv\r\n"
			+ "bvock (81)\r\n"
			+ "vsyuckp (54)\r\n"
			+ "bsoef (40)\r\n"
			+ "ncjhpa (247)\r\n"
			+ "axtzeb (13)\r\n"
			+ "yotlucw (134) -> jbydxyp, ebwtpod\r\n"
			+ "ceqfbbl (33)\r\n"
			+ "qhbotj (62)\r\n"
			+ "hrmpq (90)\r\n"
			+ "pgznzly (13)\r\n"
			+ "vgndgst (72)\r\n"
			+ "auvla (65)\r\n"
			+ "ylnvdoq (350)\r\n"
			+ "fgxst (8)\r\n"
			+ "pptocz (287) -> werriw, hglhjt\r\n"
			+ "lqbtnb (35)\r\n"
			+ "xvuri (293)\r\n"
			+ "dbeskg (9)\r\n"
			+ "crkapwa (87) -> ogpka, npdwg\r\n"
			+ "bilzbf (803) -> brkux, qcoyrha, cplvif\r\n"
			+ "byrvfhp (80) -> gqgewi, csear, vyadxnv, rqnsxm, cgjula, luuxtc, jzmqzl\r\n"
			+ "cqiipxn (84)\r\n"
			+ "oryrq (103) -> cabsaub, zfthi, palqky\r\n"
			+ "gkzeqaw (38) -> iyflfx, hntdp\r\n"
			+ "xqnrp (33)\r\n"
			+ "zcomcn (70)\r\n"
			+ "tjcpka (87)\r\n"
			+ "nfcru (41)\r\n"
			+ "vfpdqlb (43)\r\n"
			+ "msdff (82)\r\n"
			+ "tddik (43) -> vlthh, btbses\r\n"
			+ "qlmojkv (264) -> tymor, xkfuzi, ligpl\r\n"
			+ "sodrm (37)\r\n"
			+ "mvvgro (84)\r\n"
			+ "cbvjwlo (270) -> nsqzndf, synjm\r\n"
			+ "kowco (46) -> gqrgh, nhxmab\r\n"
			+ "xrapmvb (150)\r\n"
			+ "iifltp (95) -> fowpeur, vjroix\r\n"
			+ "tinbqcj (72)\r\n"
			+ "lbjuqcd (19)\r\n"
			+ "hlhomy (30) -> oylgfzb, ahayh, razvskj, hvtvcpz, teyrfjn, lqirhg, dxxty\r\n"
			+ "veutu (53)\r\n"
			+ "tfuxhhz (82)\r\n"
			+ "oenrkia (44)\r\n"
			+ "oipjwtz (40) -> tgqpp, mjbjv\r\n"
			+ "ndcjr (75)\r\n"
			+ "oermd (94)\r\n"
			+ "xsmgj (99)\r\n"
			+ "cfmhi (107) -> obrwb, hoelsa\r\n"
			+ "nwyftp (72)\r\n"
			+ "nmdhmy (39)\r\n"
			+ "qslgo (92)\r\n"
			+ "mjbjv (89)\r\n"
			+ "hhvqa (41)\r\n"
			+ "erysec (59)\r\n"
			+ "xdnuvji (20)\r\n"
			+ "bfxezgb (8)\r\n"
			+ "njmrq (192) -> uufrda, pdmkag\r\n"
			+ "gutukz (70)\r\n"
			+ "acjtwvt (98)\r\n"
			+ "kddchk (71)\r\n"
			+ "apzjw (149) -> jetfvjc, peomyg\r\n"
			+ "xzhvvy (431) -> ehxkgh, alcpfsx, kvjqli, tjdap\r\n"
			+ "sowzlz (19)\r\n"
			+ "ucvgxii (85)\r\n"
			+ "uzprmq (83) -> ygteuy, exhxs, pfzqe\r\n"
			+ "bvaor (35)\r\n"
			+ "gekcx (78)\r\n"
			+ "cxlip (44)\r\n"
			+ "psnkhtd (157)\r\n"
			+ "yimottm (2101) -> fsmzljm, uptgby, tvhfxfo, ickxyrm, nxqqsza\r\n"
			+ "ocbxx (66)\r\n"
			+ "acnvtg (277) -> wbbfe, nchjk\r\n"
			+ "vangx (51) -> xobyzo, jdhiflw\r\n"
			+ "sfoivjz (17)\r\n"
			+ "lunbob (66)\r\n"
			+ "ecabcm (190) -> vlwjehz, advlxrg\r\n"
			+ "qarjx (7)\r\n"
			+ "gyktq (98)\r\n"
			+ "imfog (52)\r\n"
			+ "zsdvfrk (1190) -> vxqcf, fvivhx, oxyxy\r\n"
			+ "zssgj (44)\r\n"
			+ "efbffd (20)\r\n"
			+ "etdofb (62)\r\n"
			+ "juakl (67)\r\n"
			+ "iltti (60)\r\n"
			+ "ffgoyk (74) -> jgdumgz, ltpban\r\n"
			+ "lamtp (89)\r\n"
			+ "loggp (75)\r\n"
			+ "pejho (106) -> mqaajk, tnobvt, gxhia\r\n"
			+ "enekg (55)\r\n"
			+ "cplvif (95) -> xfanpad, uhepxt, lebqr, hqipq\r\n"
			+ "dgsse (88) -> nwztmzp, akrgdse\r\n"
			+ "rwjzc (107) -> qrfhxne, lcufpmj, paqlttl\r\n"
			+ "drszzbe (132) -> ucjew, unfgdb, tokvgmd\r\n"
			+ "vtnpx (79)\r\n"
			+ "rrkhcl (26) -> seazs, koemv, qnxnatu\r\n"
			+ "ekfpabq (37)\r\n"
			+ "pwvmmda (278) -> rntylx, hrkswsk, zssgj\r\n"
			+ "vqekr (85)\r\n"
			+ "luccp (175) -> ebrgtq, rvuktmb, pslyfi\r\n"
			+ "xkfuzi (6)\r\n"
			+ "obaorae (45)\r\n"
			+ "dpfov (96) -> roqnodm, adasbyp, uorpbn, zyonam, zjcdwr\r\n"
			+ "lzowumq (41) -> sjthmr, mtboq, aeapmwq\r\n"
			+ "pynxen (152) -> omzpkv, rwuxn, dpija, xgogpx\r\n"
			+ "itxtmhb (72)\r\n"
			+ "hanbscg (21) -> npsza, jdjaem, lvuzab, fffxc\r\n"
			+ "teyrfjn (62414) -> ilfgats, qlgkqk, vyvcb, rnsxz\r\n"
			+ "pocxfrt (39)\r\n"
			+ "mqecf (76)\r\n"
			+ "cpacyeu (67)\r\n"
			+ "gycde (88)\r\n"
			+ "tlhgrte (2388) -> xijwk, mmlra, ejtoqaj\r\n"
			+ "jumdfk (64)\r\n"
			+ "swsffrv (13)\r\n"
			+ "fujvp (155) -> gwxkdy, hsftfol\r\n"
			+ "dyxcd (87)\r\n"
			+ "ljvpv (452) -> huutnfp, hoauxku, euvkg\r\n"
			+ "xydxl (88)\r\n"
			+ "ibdiplp (20)\r\n"
			+ "xvwqzt (70) -> ppdsem, pyhqixj, rjnht\r\n"
			+ "djmoed (90)\r\n"
			+ "raioiq (134) -> ipdbccy, inspqeu\r\n"
			+ "bwywt (67)\r\n"
			+ "jfvquxv (70)\r\n"
			+ "mtxzcd (282) -> ucvgxii, ngemsu\r\n"
			+ "lfgmv (87)\r\n"
			+ "lcufpmj (65)\r\n"
			+ "pvwdkm (50)\r\n"
			+ "dbnstqf (56)\r\n"
			+ "jwgjnuu (33)\r\n"
			+ "ndmcgpn (256) -> zvsnz, bpygf\r\n"
			+ "rktkzfw (35)\r\n"
			+ "zxeopkg (218) -> yjyipdp, drnyyes\r\n"
			+ "nutlr (116) -> ybuhf, fjerhwe, xmrcq\r\n"
			+ "cdkcn (39) -> dzlqgrt, vfpdqlb\r\n"
			+ "jfrooen (95)\r\n"
			+ "xmrcq (50)\r\n"
			+ "qpuyqq (83)\r\n"
			+ "hiqhe (361)\r\n"
			+ "xuxlspe (44)\r\n"
			+ "apvfi (59)\r\n"
			+ "wahwi (303) -> lnnii, boxvu\r\n"
			+ "affxphr (22)\r\n"
			+ "lhtzrh (213)\r\n"
			+ "yeewxiw (50)\r\n"
			+ "zyxjqs (65)\r\n"
			+ "kqgqdyg (69) -> yqctq, tcihaf\r\n"
			+ "sqnfwo (67)\r\n"
			+ "mbqkm (12)\r\n"
			+ "mqaajk (18)\r\n"
			+ "nxhetg (60)\r\n"
			+ "hrxfpx (65)\r\n"
			+ "wjfsiec (19) -> znpqzc, xvuri, vsxzpf, doazn, tjbyhjw, czxbmp, vqqrb\r\n"
			+ "hsfxq (99) -> jtxbfm, lzhdsyq\r\n"
			+ "lbiigt (26)\r\n"
			+ "bwgkn (1005) -> uzily, urxxlfo, yqnbqgc, cgnibii\r\n"
			+ "hpjgrb (73)\r\n"
			+ "ajpcyv (42)\r\n"
			+ "pirivl (144) -> bmovg, yexyj\r\n"
			+ "szuiho (73)\r\n"
			+ "lnhiiq (64)\r\n"
			+ "yacaqwf (82)\r\n"
			+ "nqcadtp (310) -> kzvwk, akatbi, gncvcwi\r\n"
			+ "bvgfpab (15)\r\n"
			+ "cxndroi (77)\r\n"
			+ "efwhif (6)\r\n"
			+ "njkxyjn (12)\r\n"
			+ "kvpju (39)\r\n"
			+ "gyyqk (5845) -> jeshqdv, xzhvvy, ynwpoz, jtlhia, gzykr, coyroy, tqjpfzx\r\n"
			+ "jwpqgy (168) -> jxanwhq, fsixon, lnsyuz\r\n"
			+ "jwxff (95) -> ihtomiz, xeprhhl\r\n"
			+ "yycux (15)\r\n"
			+ "fmhjs (79)\r\n"
			+ "wvieaw (67)\r\n"
			+ "iancjuu (39)\r\n"
			+ "vczcept (112) -> muavtro, ipeig\r\n"
			+ "mwtusu (81)\r\n"
			+ "moewgvz (89)\r\n"
			+ "gmfktbe (31)\r\n"
			+ "dcpnyer (67) -> fmjyudw, wuhyc, icccxzg, nufpcxh\r\n"
			+ "hnfeims (47)\r\n"
			+ "rouiui (30) -> tqlentr, zdkil, veqahi, txnzg, euiig, qlmojkv\r\n"
			+ "bppos (37)\r\n"
			+ "hoauxku (219)\r\n"
			+ "ficmghd (56)\r\n"
			+ "lxpshey (95)\r\n"
			+ "hglhjt (13)\r\n"
			+ "oqbet (58)\r\n"
			+ "bsmxm (88) -> trcbs, ewsrnsd, qzsowpu\r\n"
			+ "dxerl (79) -> kdujkg, njkxyjn\r\n"
			+ "gxhia (18)\r\n"
			+ "eqifs (3869) -> aqjkcss, uiwgpi, cmeqx, jwlaj\r\n"
			+ "hqipq (60)\r\n"
			+ "upbmqk (18)\r\n"
			+ "culvtcm (97)\r\n"
			+ "cgdbu (90)\r\n"
			+ "tnrpi (241) -> zjtid, xybcccw\r\n"
			+ "hlullj (39)\r\n"
			+ "ihcbt (44)\r\n"
			+ "wfjgqqm (55)\r\n"
			+ "dmzwm (86)\r\n"
			+ "hvtvcpz (81171) -> dxcpj, eqifs, mdfbhs\r\n"
			+ "uufrda (39)\r\n"
			+ "lsfdgam (77)\r\n"
			+ "huutnfp (57) -> blrzef, ihllda\r\n"
			+ "vnmxsi (17)\r\n"
			+ "tjbyhjw (161) -> ihcbt, tlxbtng, cxlip\r\n"
			+ "fshvy (84) -> indgw, gynwftf\r\n"
			+ "agsjzih (10)\r\n"
			+ "ppdsem (63)\r\n"
			+ "skmvkj (33)\r\n"
			+ "oxyxy (205) -> aawxzzs, tdnzc\r\n"
			+ "ywavdk (67)\r\n"
			+ "pkxhxdz (70) -> gklur, vqekr, fnvgp\r\n"
			+ "xsufhnb (66)\r\n"
			+ "ouhfxyf (97)\r\n"
			+ "dukqd (50) -> opyzwha, sfxsn, ndcjr, uystf\r\n"
			+ "zybvpry (20)\r\n"
			+ "wwobe (34)\r\n"
			+ "bolxwme (74) -> jfvquxv, rsqexkv\r\n"
			+ "adhilml (299) -> cqfri, mhassfj\r\n"
			+ "icrnru (160) -> gutukz, fuega\r\n"
			+ "oagluxi (40)\r\n"
			+ "ligpl (6)\r\n"
			+ "fttsg (255) -> gmfktbe, ebtbnei\r\n"
			+ "ihtomiz (99)\r\n"
			+ "gblxcsj (251) -> kuaeh, pmfpitp\r\n"
			+ "lrvxyg (91) -> lfgmv, ohtzuf\r\n"
			+ "wuhyc (71)\r\n"
			+ "qjuud (160) -> ckexdc, oencfz\r\n"
			+ "jbfzjha (305) -> vbmhjxo, txvuv, mkyqul, zehnmg\r\n"
			+ "xjosf (89) -> dfdgoj, xagwh, xkpulvc, tnrpi\r\n"
			+ "zkcwgx (22)\r\n"
			+ "ilbopwx (87)\r\n"
			+ "akatbi (222) -> qjazr, pizkx\r\n"
			+ "uxuscb (249) -> jpeprwv, mdrir\r\n"
			+ "hbgyu (19007) -> nqcadtp, tkeoe, jvpecm\r\n"
			+ "kjzsi (56)\r\n"
			+ "cduzde (13)\r\n"
			+ "edoftkj (84)\r\n"
			+ "lxisjl (86) -> euqvd, hugfkt\r\n"
			+ "owxuzp (26)\r\n"
			+ "nalhhj (4471) -> dkfepj, wjfsiec, egrga, dkxsqjt\r\n"
			+ "vcaekf (67)\r\n"
			+ "evwne (21) -> czztmlk, fmqon, fzzcxvm, rmdqvgh\r\n"
			+ "crojfnw (171)\r\n"
			+ "upiow (82) -> hukskkk, ilbopwx\r\n"
			+ "srgua (120) -> koyke, hvefi\r\n"
			+ "rcywun (81) -> moewgvz, fchlc\r\n"
			+ "qlkqplv (138) -> hsulvq, ghuoa, ozwaa\r\n"
			+ "czxbmp (197) -> ieeqmzl, yzivqv, arbebt\r\n"
			+ "jjmyu (80)\r\n"
			+ "cyfuwdb (40) -> mywmo, nppdvs, fwafvkf\r\n"
			+ "hmdwqdq (79)\r\n"
			+ "oencfz (10)\r\n"
			+ "pjkjcy (20)\r\n"
			+ "sxxhmpb (8)\r\n"
			+ "uwpwbgy (213) -> gbiluq, xidye\r\n"
			+ "mywmo (40)\r\n"
			+ "rbmmiy (833) -> rwbhl, vtono, shkfk, umwial\r\n"
			+ "dmvajb (50)\r\n"
			+ "smuybnw (89) -> uktqwa, vdistyb\r\n"
			+ "uagezb (984) -> hdvfyp, kwtukd, ikbkb\r\n"
			+ "nrlvovz (840) -> qoipc, oznhe, uvhmzj, kebff\r\n"
			+ "vbmhjxo (5)\r\n"
			+ "ckafg (86)\r\n"
			+ "ovqhdvy (2715) -> psnkhtd, zxqix, trnjhsl\r\n"
			+ "uktqwa (90)\r\n"
			+ "lzhdsyq (55)\r\n"
			+ "kofvzz (66)\r\n"
			+ "mcduq (60)\r\n"
			+ "qnsnc (62)\r\n"
			+ "kwtukd (232) -> nhzmidl, bfrbwb\r\n"
			+ "zzavd (13)\r\n"
			+ "fmjyudw (71)\r\n"
			+ "vcnph (161) -> wqgpm, nnvpkf\r\n"
			+ "lgamzp (64)\r\n"
			+ "ukqcayx (92)\r\n"
			+ "diduy (116) -> xwphya, msdff\r\n"
			+ "izonhi (99)\r\n"
			+ "jetfvjc (16)\r\n"
			+ "rjhfcl (308)\r\n"
			+ "vqqrb (179) -> jfaoy, jhgxtg\r\n"
			+ "tulxdf (308) -> bcukkvc, zgydn\r\n"
			+ "rxuqpgb (144) -> aqogxi, aicncxc\r\n"
			+ "spyxh (32)\r\n"
			+ "yqergs (100) -> kitsxb, woeoaa\r\n"
			+ "bthswyg (34)\r\n"
			+ "rfaxua (81) -> zugxr, dtyxosg\r\n"
			+ "fcoxtp (42) -> aqqdnpb, nkgmg\r\n"
			+ "jbxnffu (74)\r\n"
			+ "bwthm (929) -> jwxff, ohiftl, aqtml\r\n"
			+ "ionnnfx (97)\r\n"
			+ "urigx (141) -> xsmgj, eyozeel\r\n"
			+ "nsggol (249)\r\n"
			+ "mgeseyn (267) -> hvacjk, pvgay\r\n"
			+ "eqzuic (37)\r\n"
			+ "pxdgkik (83)\r\n"
			+ "zjqbfd (188) -> viklkmp, vfcbliu\r\n"
			+ "wivwqm (74)\r\n"
			+ "nowyhln (52)\r\n"
			+ "sqsqge (219) -> amaeuv, paqvyfa\r\n"
			+ "vynvu (87)\r\n"
			+ "ovysqnt (86)\r\n"
			+ "brfocu (230) -> zicvvl, zbhahq, agsjzih, ydhfmt\r\n"
			+ "dgumiir (40) -> olzdhtj, inezd, kqrjpgl\r\n"
			+ "vpjhl (27)\r\n"
			+ "aqqdnpb (88)\r\n"
			+ "qaszsa (94)\r\n"
			+ "ajeisgv (95)\r\n"
			+ "aoscme (73)\r\n"
			+ "owlyge (65)\r\n"
			+ "kdqslsn (73)\r\n"
			+ "hukskkk (87)\r\n"
			+ "vindf (73) -> szuiho, aoscme, fbdfh\r\n"
			+ "kosxb (140) -> tcpujhx, itlsv\r\n"
			+ "oeaqbvl (142) -> bsyiv, fiqzxhc\r\n"
			+ "lyigbhi (105) -> pqmye, nzyiue\r\n"
			+ "trnjhsl (73) -> iinql, yhzwdu, dtjzr\r\n"
			+ "mkucbvs (138) -> ikxewmm, qhygx\r\n"
			+ "fvplhrm (6)\r\n"
			+ "qnvzqc (54)\r\n"
			+ "jdbub (48)\r\n"
			+ "opyzwha (75)\r\n"
			+ "xeprhhl (99)\r\n"
			+ "xounvb (101) -> mbqkm, zwpyj\r\n"
			+ "aswpgvv (42)\r\n"
			+ "razvskj (60626) -> dlzgufq, xwifd, nalhhj, lyhok\r\n"
			+ "ygrbgm (172)\r\n"
			+ "tcrkcu (329) -> ibdiplp, efbffd\r\n"
			+ "mijxl (63)\r\n"
			+ "ajfkd (9)\r\n"
			+ "aaaak (6) -> mdopg, mzrafi\r\n"
			+ "qgnah (42)\r\n"
			+ "emppnct (78)\r\n"
			+ "qysdgq (154) -> uutlw, klpctiz\r\n"
			+ "hkewsbw (89)\r\n"
			+ "lcfundi (52)\r\n"
			+ "iccpjfn (92)\r\n"
			+ "modzqb (30)\r\n"
			+ "nsqzndf (51)\r\n"
			+ "dpyuayl (18) -> wvieaw, cpacyeu, hwkwp\r\n"
			+ "eocoy (67)\r\n"
			+ "fbuklc (82) -> lcyuk, klzfl\r\n"
			+ "ieeqmzl (32)\r\n"
			+ "qcoyrha (255) -> kjqiop, oagluxi\r\n"
			+ "lbfgh (123) -> obaorae, yktqkyl\r\n"
			+ "payoa (194) -> khbvu, nrxoha\r\n"
			+ "ywutc (71)\r\n"
			+ "fodud (178) -> axmjgih, auvla\r\n"
			+ "actggv (65)\r\n"
			+ "jngcap (845) -> tydlqpq, ebdxuo, ktfeae\r\n"
			+ "hcgbmwl (60)\r\n"
			+ "lqirhg (70965) -> hbmxey, tlhgrte, xekggcw, lxffhxk, knhst\r\n"
			+ "ifntl (26) -> emfbheo, heicvby, vcnph, qvgeei, gcylwr, uxuscb, ubrrbmk\r\n"
			+ "uiasar (15)\r\n"
			+ "sfkzoax (46)\r\n"
			+ "bqtppn (236) -> xqnrp, fsguvid\r\n"
			+ "peomyg (16)\r\n"
			+ "sqincn (80)\r\n"
			+ "zjtid (7)\r\n"
			+ "cpvlq (72)\r\n"
			+ "nwbmwa (17)\r\n"
			+ "yjonn (185) -> rbhdx, cbnef, bvgfpab, czojwyg\r\n"
			+ "jafdtcn (79)\r\n"
			+ "uqofam (245) -> lxpshey, qwdppks\r\n"
			+ "nkejtw (56)\r\n"
			+ "tcihaf (28)\r\n"
			+ "jwkgg (17)\r\n"
			+ "hsftfol (46)\r\n"
			+ "ehqavsc (22) -> aboilvw, diavsdh, nuybvi, ziyyvk, wyule, mtxzcd, tulxdf\r\n"
			+ "dyveac (96) -> jdsdqzd, lhmjc\r\n"
			+ "yfztc (74)\r\n"
			+ "nuybvi (452)\r\n"
			+ "ymfosm (38) -> hdkpuyx, ckafg, dmzwm\r\n"
			+ "vrjea (1809) -> stcaf, hemnmbr, zuxvjpc\r\n"
			+ "qteruty (8) -> mwtusu, pvpyhb\r\n"
			+ "cpmcrx (13)\r\n"
			+ "ouxjkf (18)\r\n"
			+ "rvuktmb (147) -> yhlbg, cwgbjaq\r\n"
			+ "blrzef (81)\r\n"
			+ "guxwd (49)\r\n"
			+ "yyyqzje (225) -> fnfiur, jfngjl\r\n"
			+ "qbkipp (92)\r\n"
			+ "wdlwryo (149) -> nxhetg, iltti\r\n"
			+ "tjdap (240)\r\n"
			+ "udxegjf (44) -> lzbbin, atfpsi, tuqzsn, ytnti, zdade, skotajh\r\n"
			+ "aeliqqs (26)\r\n"
			+ "shkfk (183)\r\n"
			+ "adueu (372)\r\n"
			+ "zbhahq (10)\r\n"
			+ "jbtzoy (80)\r\n"
			+ "pkcakwk (300)\r\n"
			+ "hwkwp (67)\r\n"
			+ "gatxz (45)\r\n"
			+ "qizvid (38)\r\n"
			+ "cbqebx (152) -> ornybn, zcfswa\r\n"
			+ "ppmjzx (267) -> whlfwr, sfkzoax, csqyn\r\n"
			+ "rwuxn (23)\r\n"
			+ "pcdtne (6) -> fbuhz, alqog, hanbscg, fttsg, gblxcsj, cujhtj, adhilml\r\n"
			+ "fvfitqc (39)\r\n"
			+ "rgfur (104) -> aswpgvv, qgnah\r\n"
			+ "jhgxtg (57)\r\n"
			+ "pkotpki (86)\r\n"
			+ "ujzjt (92)\r\n"
			+ "zkikhk (16)\r\n"
			+ "skotajh (328)\r\n"
			+ "ycinfxk (1450) -> kosxb, cwvkon, nyxiai, bztor\r\n"
			+ "gnffzh (234) -> tiiwbg, sfoivjz\r\n"
			+ "juvwj (79)\r\n"
			+ "ckcaugr (62) -> zebdkqz, xuxlspe\r\n"
			+ "gjfkx (31)\r\n"
			+ "blome (73) -> jjmyu, bljfcim\r\n"
			+ "yqctq (28)\r\n"
			+ "gpzaa (68) -> sqfopc, lxxfgli, yyyqzje, cjkoxak\r\n"
			+ "qoipc (68) -> tjcpka, oydoajo\r\n"
			+ "olhuxt (7)\r\n"
			+ "zdade (166) -> oyfob, bvock\r\n"
			+ "ihllda (81)\r\n"
			+ "sbklnq (85)\r\n"
			+ "yyblsz (54) -> nrmvc, dszjyr, bppos, tahstqe\r\n"
			+ "qenjyl (79)\r\n"
			+ "zukgdrx (79)\r\n"
			+ "fszrgv (34)\r\n"
			+ "ulezwmd (56)\r\n"
			+ "xgogpx (23)\r\n"
			+ "gwxkdy (46)\r\n"
			+ "knhst (5583) -> ghjpcv, szvrql, ojtrl\r\n"
			+ "mblvffb (79)\r\n"
			+ "qowyx (56)\r\n"
			+ "yablonq (18)\r\n"
			+ "mwfryd (93) -> mldkiku, sveuu, kzjfme, kzwbhrg\r\n"
			+ "xjafd (17)\r\n"
			+ "njgzn (97)\r\n"
			+ "jpeprwv (12)\r\n"
			+ "lnnii (18)\r\n"
			+ "tsetywu (22)\r\n"
			+ "gdutjjl (73)\r\n"
			+ "lnsyuz (27)\r\n"
			+ "qyypm (417) -> uqofam, xtvyh, ajpujs\r\n"
			+ "uutlw (75)\r\n"
			+ "cbnef (15)\r\n"
			+ "gikqie (90) -> qpwfl, pxhbe, yxcbn, lftlpr\r\n"
			+ "nkuesm (60)\r\n"
			+ "znpqzc (53) -> ekxdjlp, skvytv, nkuesm, ajtkddh\r\n"
			+ "mszwp (53) -> qaszsa, tupro, otljqmh\r\n"
			+ "stcaf (54) -> cufaveh, foblbqu\r\n"
			+ "nmlykny (112) -> uitef, lsfdgam\r\n"
			+ "frlmoih (92)\r\n"
			+ "hqvvrd (34) -> juvwj, ayafxml\r\n"
			+ "unzzng (22)\r\n"
			+ "xucelzn (49) -> jumdfk, ilzwrk\r\n"
			+ "nyjmiyq (91)\r\n"
			+ "zfjpii (181) -> btjxv, rfhjgxy, digfyo\r\n"
			+ "vyvcb (4479) -> jsniger, rbmmiy, zvildgh, kvtvmi, ogiie\r\n"
			+ "fwqru (62)\r\n"
			+ "skvytv (60)\r\n"
			+ "ujogppt (95)\r\n"
			+ "mgzotal (125) -> frgot, sjcbxp\r\n"
			+ "ytpiey (83)\r\n"
			+ "bfqba (872) -> vopeoj, gfknji, iwdesog, qteruty, lxisjl\r\n"
			+ "foblbqu (20)\r\n"
			+ "bzlgar (37)\r\n"
			+ "dszjyr (37)\r\n"
			+ "nrpyfqd (39) -> nihmyu, acjtwvt\r\n"
			+ "vgvvr (66)\r\n"
			+ "hzsgvc (8)\r\n"
			+ "lddiw (7)\r\n"
			+ "ydhfmt (10)\r\n"
			+ "uspvnv (94)\r\n"
			+ "seazs (92)\r\n"
			+ "zrydf (108) -> zzavd, ppbevc\r\n"
			+ "pkglsge (93)\r\n"
			+ "oamrbi (33)\r\n"
			+ "bendlfs (92)\r\n"
			+ "rkgxu (88)\r\n"
			+ "fqhag (2673) -> vangx, crojfnw, njrzjdt\r\n"
			+ "wesyh (26)\r\n"
			+ "jbaazop (19)\r\n"
			+ "tgvdjhh (72)\r\n"
			+ "ebdxuo (242)\r\n"
			+ "xthhlfy (61) -> jafdtcn, kbout\r\n"
			+ "vlthh (88)\r\n"
			+ "sqfrw (830) -> ppmjzx, vixlf, ryskzh, ynkkomw\r\n"
			+ "kzjfme (55)\r\n"
			+ "heicvby (145) -> akrsjfc, lnhiiq\r\n"
			+ "cuaect (114) -> ftdkas, jwgjnuu\r\n"
			+ "oyjtku (93)\r\n"
			+ "eyozeel (99)\r\n"
			+ "rfhjgxy (227)\r\n"
			+ "eoasnfq (94) -> idszh, vshekb\r\n"
			+ "phgkg (30)\r\n"
			+ "dxgnqsj (34)\r\n"
			+ "egrga (1130) -> nrpyfqd, cfmhi, uwpwbgy, zqtok\r\n"
			+ "sljgt (1013) -> iifltp, igfjvkm, rxefab\r\n"
			+ "bszcup (56)\r\n"
			+ "kkyfjh (83)\r\n"
			+ "frvmu (143) -> xdnuvji, vwhynu\r\n"
			+ "fsbojm (41)\r\n"
			+ "mavbgo (91)\r\n"
			+ "digfyo (188) -> tkejpfe, ynirne, swsffrv\r\n"
			+ "xoyjtol (59)\r\n"
			+ "qvbuj (1045) -> dgumiir, ofnmnyy, mkucbvs\r\n"
			+ "dzetsz (1418) -> nsbli, ulxsa, krdlzf\r\n"
			+ "zguqo (92) -> ripgc, oenrkia\r\n"
			+ "klgsk (6)\r\n"
			+ "yktqkyl (45)\r\n"
			+ "jhcurc (50)\r\n"
			+ "teuzi (57)\r\n"
			+ "gfknji (26) -> nwyftp, vgndgst\r\n"
			+ "gcylwr (221) -> wesyh, lsycscb\r\n"
			+ "hxaza (7)\r\n"
			+ "asoirn (74)\r\n"
			+ "ofnmnyy (36) -> sziwpzi, zyxjqs\r\n"
			+ "xobyzo (60)\r\n"
			+ "azdklp (43)\r\n"
			+ "mcfst (47)\r\n"
			+ "vwqog (43)\r\n"
			+ "tupro (94)\r\n"
			+ "lytukj (25)\r\n"
			+ "roqnodm (92) -> qbbmsf, oxewutr, pdcaqbr\r\n"
			+ "axmjgih (65)\r\n"
			+ "ezztp (87)\r\n"
			+ "luuxtc (2600) -> qfkka, dxznun\r\n"
			+ "pvzyops (94) -> oiyxr, ffrilz, upiow\r\n"
			+ "adasbyp (237) -> kdqslsn, xantdh\r\n"
			+ "iaiywwa (1850) -> nhxfu, boiic, kqgqdyg\r\n"
			+ "zdkil (214) -> cemygp, bgctgn\r\n"
			+ "pslyfi (7) -> ilydn, birahww, yfztc\r\n"
			+ "wbllfh (43) -> xwmnaj, gprznw\r\n"
			+ "drnyyes (66)\r\n"
			+ "coyroy (175) -> oevvote, zzwtuu, klyso, pirivl\r\n"
			+ "ddkgzi (19)\r\n"
			+ "btbses (88)\r\n"
			+ "mhassfj (9)\r\n"
			+ "rbhdx (15)\r\n"
			+ "kfhwxyy (17)\r\n"
			+ "ozwaa (78)\r\n"
			+ "lhmjc (32)\r\n"
			+ "lftlpr (11)\r\n"
			+ "ncaoc (58)\r\n"
			+ "zacywmu (12)\r\n"
			+ "vixlf (45) -> cgdbu, djmoed, npfkpts, eisrj\r\n"
			+ "vwtmps (142) -> jljnags, qizvid\r\n"
			+ "fsguvid (33)\r\n"
			+ "gxdtiob (203) -> vbisx, gzter, bzkwsro\r\n"
			+ "xwphya (82)\r\n"
			+ "jtujnwo (37)\r\n"
			+ "wyule (401) -> nwbmwa, pvpqoq, jwkgg\r\n"
			+ "wpgyc (96)\r\n"
			+ "jbvugg (224) -> dxgnqsj, fsfuluo\r\n"
			+ "tojnst (160)\r\n"
			+ "jeshqdv (1303) -> affxphr, lyhxuh, zkcwgx, cqdtav\r\n"
			+ "icncbl (48)\r\n"
			+ "kqiraxg (54)\r\n"
			+ "aicncxc (29)\r\n"
			+ "zbedu (209)\r\n"
			+ "pdmsm (57)\r\n"
			+ "kictlpo (37)\r\n"
			+ "brkux (335)\r\n"
			+ "zrbkrdx (41)\r\n"
			+ "otljqmh (94)\r\n"
			+ "kcreb (48) -> ihuzl, bvaor, popymuq\r\n"
			+ "muavtro (98)\r\n"
			+ "ayypg (56)\r\n"
			+ "vdistyb (90)\r\n"
			+ "euvkg (203) -> mgwauar, lazlx\r\n"
			+ "ayafxml (79)\r\n"
			+ "bnvjmae (7)\r\n"
			+ "ogpka (80)\r\n"
			+ "gnrqrsj (2189) -> ortcrq, upbmqk\r\n"
			+ "rxefab (131) -> vcaekf, sqnfwo\r\n"
			+ "pgpnvo (931) -> eahos, kcreb, lwefm, bbdimns\r\n"
			+ "bphrvm (64)\r\n"
			+ "doazn (211) -> siswh, hhvqa\r\n"
			+ "sawqp (32)\r\n"
			+ "mwdvbr (68)\r\n"
			+ "mtboq (76)\r\n"
			+ "dxcpj (93) -> afcgdxg, kzwgln, wkydaz, spkeqv, udxegjf\r\n"
			+ "lyhxuh (22)\r\n"
			+ "iuovz (88)\r\n"
			+ "csear (1969) -> fnijmph, mgzotal, evmblgk\r\n"
			+ "rojhup (7)\r\n"
			+ "ebtbnei (31)\r\n"
			+ "lhnevgo (269)\r\n"
			+ "zibbm (85)\r\n"
			+ "nrmvc (37)\r\n"
			+ "txxpej (280) -> actggv, krqxe\r\n"
			+ "lhvtmoo (130) -> icncbl, zbtck\r\n"
			+ "wgwkss (80)\r\n"
			+ "aawxzzs (22)\r\n"
			+ "aarioi (79)\r\n"
			+ "cabsaub (60)\r\n"
			+ "otymybu (223) -> ddkgzi, viafs\r\n"
			+ "cbgfg (58)\r\n"
			+ "wcinck (20) -> ziwkz, wfeupmd, drszzbe, mgeseyn, xasioks, xtjrkv\r\n"
			+ "orkcq (65) -> iujqo, ehdax\r\n"
			+ "okfcek (97)\r\n"
			+ "ybbrr (247)\r\n"
			+ "iatmtm (55) -> lwxts, mqecf, tuhxr\r\n"
			+ "yyxmp (80)\r\n"
			+ "ysvjxvz (78)\r\n"
			+ "birahww (74)\r\n"
			+ "mxxfu (57) -> qdovgra, ywlrls, wahwi, mzjwcds, axrojbs, urigx\r\n"
			+ "xbqpjo (98)\r\n"
			+ "kqmhotc (94) -> rkuyxrc, wfjgqqm, xdylc\r\n"
			+ "qwtodu (71)\r\n"
			+ "qdxteam (61) -> ybbrr, frrvvai, ncjhpa, onuxzz, jvepbal, qznpwb\r\n"
			+ "fbiqxqk (59)\r\n"
			+ "rokie (9708) -> vmgqltz, qdxteam, srvwd, qvbuj, pgpnvo, hxjhcuc\r\n"
			+ "ovmvvkl (24) -> tvhgbau, exgsmmj, uwvbon\r\n"
			+ "qnxnatu (92)\r\n"
			+ "hrkswsk (44)\r\n"
			+ "ndodv (296)\r\n"
			+ "koemv (92)\r\n"
			+ "hfqjj (37)\r\n"
			+ "yexyj (80)\r\n"
			+ "fhlul (56)\r\n"
			+ "dzzbvkv (64)\r\n"
			+ "gmhxee (74)\r\n"
			+ "jbgqlat (65)\r\n"
			+ "qclpa (84)\r\n"
			+ "indgw (91)\r\n"
			+ "krqxe (65)\r\n"
			+ "lmmeg (26) -> ummcw, zqhdiwz\r\n"
			+ "bgmwpam (68)\r\n"
			+ "wpfbdof (151) -> sbutyr, klgsk\r\n"
			+ "qznpwb (153) -> vfmwzb, haicg\r\n"
			+ "hdpemqh (168) -> txxpej, pwvmmda, gadyi, mvhqou\r\n"
			+ "gpfaupm (13)\r\n"
			+ "iqfmvz (67)\r\n"
			+ "pdcaqbr (97)\r\n"
			+ "qfkow (64)\r\n"
			+ "exhxs (89)\r\n"
			+ "zebdkqz (44)\r\n"
			+ "rrtqyew (191) -> zbxakfn, ajfkd\r\n"
			+ "ukrki (39)\r\n"
			+ "hvacjk (69)\r\n"
			+ "udfuty (32)\r\n"
			+ "mrgccl (85)\r\n"
			+ "uzily (82) -> swscfel, apzabs\r\n"
			+ "lxffhxk (1245) -> bfqba, cpxgct, rouiui, qyypm\r\n"
			+ "jfngjl (86)\r\n"
			+ "ceevpgx (47)\r\n"
			+ "sziwpzi (65)\r\n"
			+ "pqmye (57)\r\n"
			+ "phkvcix (90) -> nubay, jaamgi\r\n"
			+ "gxcnp (27)\r\n"
			+ "wmwzhjg (73)\r\n"
			+ "miuvc (283)\r\n"
			+ "nvtbk (1775) -> srgua, ckcaugr, xrapmvb\r\n"
			+ "zfthi (60)\r\n"
			+ "inezd (42)\r\n"
			+ "irzuowk (90) -> ayqgp, zruqij, oqbet, fdckzry\r\n"
			+ "zuxvjpc (62) -> mbunh, mgvoh, bfxezgb, sxxhmpb\r\n"
			+ "wmyvz (59)\r\n"
			+ "tqjpfzx (47) -> gjupqe, lwhev, bxhjjd, fmquyhw\r\n"
			+ "xhwfcu (75)\r\n"
			+ "tnltvzk (90) -> cevkjvr, hrmpq\r\n"
			+ "uhepxt (60)\r\n"
			+ "sjixg (25)\r\n"
			+ "kuaeh (33)\r\n"
			+ "uwvbon (79)\r\n"
			+ "jzoue (94)\r\n"
			+ "hdspavt (60)\r\n"
			+ "kosgqpu (50)\r\n"
			+ "mznkfco (79)\r\n"
			+ "xfanpad (60)\r\n"
			+ "zcpyr (81)\r\n"
			+ "gutifk (228)\r\n"
			+ "scipnb (53)\r\n"
			+ "ejvaoj (59)\r\n"
			+ "ybuhf (50)\r\n"
			+ "bpmkexj (166) -> mbokr, ytbtswy\r\n"
			+ "ogafygg (39)\r\n"
			+ "fooowuf (42)\r\n"
			+ "yiwdaj (86) -> iwajy, aftsom\r\n"
			+ "hoelsa (64)\r\n"
			+ "cjvdngb (91) -> qedkzuz, vtamjj\r\n"
			+ "rsqexkv (70)\r\n"
			+ "ftqtzxk (43)\r\n"
			+ "azgjimy (92)\r\n"
			+ "bochc (39)\r\n"
			+ "qfsue (35)\r\n"
			+ "objqgkm (146) -> tsiuz, glguoq\r\n"
			+ "tatjry (47)\r\n"
			+ "tcpujhx (55)\r\n"
			+ "nnvpkf (56)\r\n"
			+ "gatdr (89)\r\n"
			+ "jcmviuv (37)\r\n"
			+ "pzhyoh (3960) -> bkset, bfwbkxq, zsdvfrk, wrobpcw, ffxnegs, ifntl\r\n"
			+ "svyojyu (60) -> qslgo, ukqcayx\r\n"
			+ "sxbusu (73)\r\n"
			+ "jtikaai (194) -> yukoxaw, qftqq\r\n"
			+ "nkgmg (88)\r\n"
			+ "zolmsue (66)\r\n"
			+ "ziyyvk (60) -> yuypmb, ctoxz, dcwpsvy, mxrfq\r\n"
			+ "bgcjrf (80)\r\n"
			+ "qlqqlq (350)\r\n"
			+ "npsza (74)\r\n"
			+ "eahos (19) -> ywavdk, iqfmvz\r\n"
			+ "cpxgct (14) -> tabzzo, svyojyu, pynxen, idooz, nzorg, zudqkt, fsvkj\r\n"
			+ "nxrkz (1541) -> gutifk, avqjqdf, mgyfdm\r\n"
			+ "twzgms (43)\r\n"
			+ "uwizfa (88)\r\n"
			+ "tiush (60)\r\n"
			+ "cqpns (123) -> tfnem, kqguihx\r\n"
			+ "necmih (10) -> dppzdx, zvelptp, tpsgt\r\n"
			+ "ehxkgh (172) -> bthswyg, lbojqfo\r\n"
			+ "yxoqwg (80)\r\n"
			+ "emfbheo (85) -> uspvnv, oermd\r\n"
			+ "siisskc (13)\r\n"
			+ "icccxzg (71)\r\n"
			+ "pjvpqmg (64)\r\n"
			+ "dxxty (64884) -> ljugvh, gyyqk, pzhyoh\r\n"
			+ "neladb (11)\r\n"
			+ "polrzc (59)\r\n"
			+ "snvqyqb (66)\r\n"
			+ "lebqr (60)\r\n"
			+ "shfjyzk (68)\r\n"
			+ "acdkw (1907) -> apzjw, ialtabg, cjvdngb\r\n"
			+ "xdylc (55)\r\n"
			+ "hknzmvs (93)\r\n"
			+ "obrwb (64)\r\n"
			+ "werriw (13)\r\n"
			+ "jjjfkf (19)\r\n"
			+ "zqckoxe (118) -> vynvu, zgnwz\r\n"
			+ "mgvoh (8)\r\n"
			+ "oxewutr (97)\r\n"
			+ "qqydcts (62)\r\n"
			+ "pjkwlmk (56) -> etdofb, qqydcts\r\n"
			+ "kzwbhrg (55)\r\n"
			+ "cgzyc (669) -> bqtppn, rwjzc, bwylliz, rrkhcl\r\n"
			+ "sltrdk (88) -> qwtodu, rpkpa, kddchk, xirqz\r\n"
			+ "aqjkcss (77) -> rfaxua, nsggol, uxlcvt, jwpqgy, tjobe, ovrkpd\r\n"
			+ "xagwh (99) -> sdigtox, pocxfrt, iancjuu, iefyz\r\n"
			+ "apjxafk (1513) -> rznyr, oamrbi\r\n"
			+ "uturjs (85)\r\n"
			+ "qwxrsa (261)\r\n"
			+ "cgjula (2020) -> lhvtmoo, yiwdaj, biwdu\r\n"
			+ "yakzm (16)\r\n"
			+ "ejtoqaj (1426) -> whggku, ktehtif, wpfbdof\r\n"
			+ "eoaprcr (93)\r\n"
			+ "otaty (141) -> ydpihb, ouabc\r\n"
			+ "rjijdre (17)\r\n"
			+ "atfpsi (196) -> qoqydb, vgvvr\r\n"
			+ "qjazr (21)\r\n"
			+ "petluuh (67)\r\n"
			+ "xdupyte (19)\r\n"
			+ "rpkpa (71)\r\n"
			+ "aytjryx (25)\r\n"
			+ "pfmor (80)\r\n"
			+ "rfbdpc (66) -> payoa, ymfosm, ndodv, thutxib, objqgkm, gjjfju\r\n"
			+ "kkciirc (71)\r\n"
			+ "hfnijbd (234) -> qarjx, olhuxt\r\n"
			+ "mrvdvga (54)\r\n"
			+ "vwhynu (20)\r\n"
			+ "nnsyc (59)\r\n"
			+ "rlwvuj (280)\r\n"
			+ "vtono (37) -> gdutjjl, eqahcc\r\n"
			+ "jdjaem (74)\r\n"
			+ "hgcxyx (13)\r\n"
			+ "mkjvhl (282) -> neladb, tsrrzuc\r\n"
			+ "cmeqx (521) -> uzprmq, xjmrcc, qlqqlq\r\n"
			+ "fffxc (74)\r\n"
			+ "sbutyr (6)\r\n"
			+ "jikzxd (50)\r\n"
			+ "zvildgh (1079) -> wtoive, rbucosf, eoasnfq\r\n"
			+ "unfgdb (91)\r\n"
			+ "npdwg (80)\r\n"
			+ "ftdkas (33)\r\n"
			+ "ewdpntl (66)\r\n"
			+ "akrgdse (63)\r\n"
			+ "vczudlu (17)\r\n"
			+ "ablvgzq (58)\r\n"
			+ "kbout (79)\r\n"
			+ "aqogxi (29)\r\n"
			+ "igfjvkm (265)\r\n"
			+ "rkbtnzd (40)\r\n"
			+ "jatvkwy (92) -> kqiraxg, vsyuckp, zwjds, mrvdvga\r\n"
			+ "mjuwde (888) -> cbqebx, kihxgg, zjqbfd\r\n"
			+ "ytbtswy (57)\r\n"
			+ "rugzyaj (16029) -> apjxafk, jngcap, wrtyhxg, hblcbb\r\n"
			+ "fuega (70)\r\n"
			+ "lejoaru (64)\r\n"
			+ "zvelptp (28)\r\n"
			+ "mdfbhs (5185) -> miymiit, jjgem, gpzaa\r\n"
			+ "xwifd (7225) -> rfbdpc, qqduoo, uagezb\r\n"
			+ "bxhjjd (172) -> yacaqwf, ngksxux\r\n"
			+ "xduga (88)\r\n"
			+ "rwbhl (183)\r\n"
			+ "cpazla (101) -> ayypg, kjzsi\r\n"
			+ "ttmei (19)\r\n"
			+ "hblcbb (5) -> qwxrsa, ovmvvkl, orkcq, otymybu, sjxbk, frqtkkr\r\n"
			+ "lzbbin (250) -> ujzofuy, urwgjd\r\n"
			+ "bgctgn (34)\r\n"
			+ "uaqik (15)\r\n"
			+ "kvpztt (93)\r\n"
			+ "zeopgv (312) -> pgznzly, ixwyi, tefcd\r\n"
			+ "oyfob (81)\r\n"
			+ "yhzwdu (28)\r\n"
			+ "xwmnaj (41)\r\n"
			+ "ngksxux (82)\r\n"
			+ "brmtxo (300)\r\n"
			+ "kdujkg (12)\r\n"
			+ "cjlxgf (165) -> bsoef, rkbtnzd\r\n"
			+ "tefcd (13)\r\n"
			+ "jsniger (680) -> lycpdcu, iihzs, aubhuwo, xucelzn, qykoae\r\n"
			+ "thutxib (138) -> mblvffb, zukgdrx\r\n"
			+ "npfkpts (90)\r\n"
			+ "yqbkjg (51)\r\n"
			+ "tsiuz (75)\r\n"
			+ "otvvje (43)\r\n"
			+ "boxvu (18)\r\n"
			+ "etnuzv (27)\r\n"
			+ "fkmccg (32)\r\n"
			+ "zzxlo (2220) -> zhiai, oqhwa, irzuowk\r\n"
			+ "haicg (47)\r\n"
			+ "veqahi (50) -> yugjkuz, ncaoc, hfjhadi, cmzoogc\r\n"
			+ "uystf (75)\r\n"
			+ "wqxcn (292) -> ddrrgp, sxvlfn, ipmbqts\r\n"
			+ "jlbhafs (27)\r\n"
			+ "lvuzab (74)\r\n"
			+ "hrfyodg (84)\r\n"
			+ "apctfnv (246) -> baygmx, zacywmu\r\n"
			+ "wafjawl (56)\r\n"
			+ "dlsss (88) -> mijxl, voonmio\r\n"
			+ "nlrobhq (87)\r\n"
			+ "jzdmjdf (1849) -> aaaak, necmih, fmifd, kowco\r\n"
			+ "yzivqv (32)\r\n"
			+ "cufudi (97)\r\n"
			+ "zwjds (54)\r\n"
			+ "pizkx (21)\r\n"
			+ "fbdfh (73)\r\n"
			+ "cwvkon (193) -> cepqh, jjjfkf, xdupyte\r\n"
			+ "wqgpm (56)\r\n"
			+ "vopeoj (14) -> sgqaiyz, ysvjxvz\r\n"
			+ "zqtok (151) -> fhgnht, fooowuf\r\n"
			+ "fugeht (89)\r\n"
			+ "mgyfdm (60) -> mvvgro, hrfyodg\r\n"
			+ "wqdvql (39)\r\n"
			+ "ogiie (573) -> hfnijbd, cxokosi, jtikaai, ffgoyk\r\n"
			+ "tgqpp (89)\r\n"
			+ "fdaddso (15)\r\n"
			+ "cmzoogc (58)\r\n"
			+ "gjjfju (270) -> kndcyxb, cpmcrx\r\n"
			+ "wowkfnh (64)\r\n"
			+ "lwefm (115) -> ageyuq, jbaazop\r\n"
			+ "qykoae (61) -> cbgfg, dyfhy\r\n"
			+ "ipeig (98)\r\n"
			+ "iyjcoy (63)\r\n"
			+ "omzpkv (23)\r\n"
			+ "kqguihx (48)\r\n"
			+ "qrtwjv (37)\r\n"
			+ "sgqaiyz (78)\r\n"
			+ "gzdxgvj (64)\r\n"
			+ "wfeupmd (65) -> pdjnnzd, mrgccl, uturjs, yfszfef\r\n"
			+ "vmgqltz (841) -> ecabcm, vigvho, ppfyonm\r\n"
			+ "txvuv (5)\r\n"
			+ "zfcylzq (113) -> ocbxx, kofvzz\r\n"
			+ "vigvho (76) -> vtnpx, hjdms\r\n"
			+ "njrzjdt (171)\r\n"
			+ "iyflfx (90)\r\n"
			+ "spkeqv (1828) -> qbkipp, bendlfs\r\n"
			+ "dqiyfw (21) -> mliwyi, kvpztt, oyjtku\r\n"
			+ "nufpcxh (71)\r\n"
			+ "ppbevc (13)\r\n"
			+ "bljfcim (80)\r\n"
			+ "hjdms (79)\r\n"
			+ "mcfrv (19)\r\n"
			+ "zruqij (58)\r\n"
			+ "gmurq (89)\r\n"
			+ "zyqqzou (78)\r\n"
			+ "pyocxtt (27)\r\n"
			+ "akrsjfc (64)\r\n"
			+ "nzorg (102) -> bdukt, kkciirc\r\n"
			+ "vobfi (734) -> lbfgh, wfbuzbg, kklix, hpsxqdm, lhtzrh, cpazla, skhmac\r\n"
			+ "zugxr (84)\r\n"
			+ "ldwhpl (324) -> takkbk, thneyz\r\n"
			+ "kzwgln (1217) -> evwne, lrvxyg, hllzej\r\n"
			+ "heuyaxx (2337) -> iatmtm, pabgfh, oryrq\r\n"
			+ "kzjkjz (17)\r\n"
			+ "ykmej (92)\r\n"
			+ "sqfopc (33) -> mavbgo, uucyyr, nyjmiyq, tygst\r\n"
			+ "qcpuch (270)\r\n"
			+ "qcolnc (11) -> ewdpntl, zolmsue, lunbob\r\n"
			+ "tfxyjz (87)\r\n"
			+ "fiqzxhc (38)\r\n"
			+ "hvhtokr (95)\r\n"
			+ "ledgpb (132) -> kqltx, wivwqm\r\n"
			+ "bonnse (30)\r\n"
			+ "dcwpsvy (98)\r\n"
			+ "xjmrcc (268) -> yucwtc, ilueo\r\n"
			+ "bzkwsro (49)\r\n"
			+ "zziyhz (18)\r\n"
			+ "qoqydb (66)\r\n"
			+ "ubrrbmk (87) -> pkglsge, gjorp\r\n"
			+ "cgnibii (188) -> pqvid, uiasar\r\n"
			+ "sxvlfn (23)\r\n"
			+ "gqgewi (2538) -> ndxuv, egulpbe\r\n"
			+ "qosqq (47)\r\n"
			+ "jkczp (37)\r\n"
			+ "pxhbe (11)\r\n"
			+ "vpjmvzd (37)\r\n"
			+ "rvjzxtg (86)\r\n"
			+ "pfzqe (89)\r\n"
			+ "uvhmzj (114) -> bphrvm, lgamzp\r\n"
			+ "gklur (85)\r\n"
			+ "wbbfe (37)\r\n"
			+ "wkumzkr (1049) -> nxtyiha, modzqb\r\n"
			+ "pyhqixj (63)\r\n"
			+ "ohtzuf (87)\r\n"
			+ "lsycscb (26)\r\n"
			+ "bdsibf (87)\r\n"
			+ "gzter (49)\r\n"
			+ "ogelzdv (87)\r\n"
			+ "fstzdn (97)\r\n"
			+ "ebktv (146) -> gpfaupm, cduzde\r\n"
			+ "iinql (28)\r\n"
			+ "tdurwbh (58)\r\n"
			+ "hnvybq (268)\r\n"
			+ "sfxsn (75)\r\n"
			+ "jgdumgz (87)\r\n"
			+ "zqhdiwz (96)\r\n"
			+ "rznyr (33)\r\n"
			+ "ouqwmnj (265) -> jdbub, evqrr\r\n"
			+ "tiuag (62) -> xhbjag, bmehz\r\n"
			+ "fdckzry (58)\r\n"
			+ "hdkpuyx (86)\r\n"
			+ "hemnmbr (16) -> ukrki, mgsasl\r\n"
			+ "rupdbwl (43)\r\n"
			+ "bbdimns (57) -> upftju, iracqt\r\n"
			+ "ipdbccy (34)\r\n"
			+ "fbrvfk (79)\r\n"
			+ "hueqfk (85)\r\n"
			+ "bxrkfwo (67)\r\n"
			+ "fwafvkf (40)\r\n"
			+ "nsbli (47) -> hpanc, xjafd, uqjmbb, ycnih\r\n"
			+ "ifhpy (79)\r\n"
			+ "fneqe (1219) -> vmatvgx, bofjde, hhnpg\r\n"
			+ "mliwyi (93)\r\n"
			+ "utqxb (37)\r\n"
			+ "fvivhx (75) -> nwlyt, dyxcd\r\n"
			+ "whggku (97) -> vomrnc, ceqfbbl\r\n"
			+ "kndcyxb (13)\r\n"
			+ "ynwpoz (785) -> raioiq, yyblsz, rxuqpgb\r\n"
			+ "hrrampl (27)\r\n"
			+ "kkftjia (87)\r\n"
			+ "rvxed (122) -> rktkzfw, qfsue\r\n"
			+ "miauii (66) -> kpjxln, icrnru, dqiyfw, brmtxo, pkcakwk\r\n"
			+ "bkset (857) -> brfocu, thvjlgo, urhwog, apctfnv\r\n"
			+ "nhxfu (35) -> lwufmc, gatxz\r\n"
			+ "skhmac (101) -> dbnstqf, wafjawl\r\n"
			+ "bdwswow (65)\r\n"
			+ "lgoak (70)\r\n"
			+ "mdrob (51)\r\n"
			+ "fsixon (27)\r\n"
			+ "hcyohc (85)\r\n"
			+ "kihxgg (44) -> awhwxdm, sbgtiqe\r\n"
			+ "hdhvzi (1759) -> kzhpyr, apvfi\r\n"
			+ "bwylliz (110) -> kwvybk, ftexc\r\n"
			+ "xijwk (841) -> bsmxm, xrise, uzjoys\r\n"
			+ "xkpulvc (93) -> fbvvrqt, zcpyr\r\n"
			+ "xhbjag (76)\r\n"
			+ "azrpi (92)\r\n"
			+ "lxxfgli (49) -> nlrobhq, ogelzdv, tfxyjz, bdsibf\r\n"
			+ "qedkzuz (45)\r\n"
			+ "bmehz (76)\r\n"
			+ "exgsmmj (79)\r\n"
			+ "ijcxfx (136) -> jbgqlat, bdwswow\r\n"
			+ "nsvrfae (71)\r\n"
			+ "offas (58)\r\n"
			+ "ipofw (15)\r\n"
			+ "matcdld (35)\r\n"
			+ "gjorp (93)\r\n"
			+ "bofjde (152) -> jcuiffa, vvkbav\r\n"
			+ "yxqesmi (172)\r\n"
			+ "eisrj (90)\r\n"
			+ "pjmci (59)\r\n"
			+ "palqky (60)\r\n"
			+ "aipmq (41)\r\n"
			+ "ripgc (44)\r\n"
			+ "ehdax (98)\r\n"
			+ "jtlhia (749) -> tiuag, bdbxp, dlsss\r\n"
			+ "uucyyr (91)\r\n"
			+ "dtqbtvx (223) -> izyjved, etnkepp\r\n"
			+ "yhlbg (41)\r\n"
			+ "kwvybk (96)\r\n"
			+ "fhgnht (42)\r\n"
			+ "ummcw (96)\r\n"
			+ "khkuxc (1254) -> qqhjlu, gekcx, vrajpg, emppnct\r\n"
			+ "nwlyt (87)\r\n"
			+ "txnzg (74) -> lcfundi, tifkr, imfog, imbpvgl\r\n"
			+ "dkzitf (20)\r\n"
			+ "bdbxp (80) -> fcvpdiz, bxrkfwo\r\n"
			+ "degnsd (177) -> eetxll, jkczp, ghzqyv, kictlpo\r\n"
			+ "zudqkt (142) -> fszrgv, wwobe, jbjkp\r\n"
			+ "zjcdwr (249) -> bqcizg, saiyjff\r\n"
			+ "sjthmr (76)\r\n"
			+ "kryoh (144) -> jcmviuv, hfqjj\r\n"
			+ "ghuoa (78)\r\n"
			+ "uitef (77)\r\n"
			+ "cjkoxak (340) -> sowzlz, ttmei, lajyaur\r\n"
			+ "pczkz (88)\r\n"
			+ "itlsv (55)\r\n"
			+ "nwztmzp (63)\r\n"
			+ "tsrrzuc (11)\r\n"
			+ "rxrzt (65) -> krembdy, zrbkrdx, aipmq\r\n"
			+ "frqtkkr (185) -> qecgvu, lbjuqcd, mcfrv, kwqcbe\r\n"
			+ "mdrir (12)\r\n"
			+ "vytdgko (97)\r\n"
			+ "tkeoe (865) -> wzcgi, awsphe, ifhpy\r\n"
			+ "orwbp (96) -> ecjujqu, iccpjfn\r\n"
			+ "ckexdc (10)\r\n"
			+ "popymuq (35)\r\n"
			+ "euiig (166) -> ablvgzq, tdurwbh\r\n"
			+ "ibjbozh (895) -> ijcxfx, nmlykny, fshvy, nutlr, yotlucw\r\n"
			+ "idszh (34)\r\n"
			+ "tfnem (48)\r\n"
			+ "kqrjpgl (42)\r\n"
			+ "ewsrnsd (90)\r\n"
			+ "rnsxz (9718) -> pvzyops, zfjpii, luccp\r\n"
			+ "avqjqdf (50) -> dilefzx, dulpw\r\n"
			+ "euqvd (42)\r\n"
			+ "dulpw (89)\r\n"
			+ "nppdvs (40)\r\n"
			+ "gncvcwi (104) -> pfmor, yyxmp\r\n"
			+ "fmquyhw (188) -> hwqvzw, huspq\r\n"
			+ "hpgktb (60) -> hcgbmwl, tiush\r\n"
			+ "iyxkzat (49)\r\n"
			+ "seyed (86)\r\n"
			+ "zzwtuu (260) -> unzzng, ebsxx\r\n"
			+ "nfvsrpa (876) -> kwwhb, blome, otaty, dtqbtvx\r\n"
			+ "mnwhky (1339) -> hqccsb, ldflo, rgfur, rxrzt\r\n"
			+ "kebff (242)\r\n"
			+ "cogovv (74)\r\n"
			+ "takkbk (57)\r\n"
			+ "yyswun (98)\r\n"
			+ "ecjrblb (68)\r\n"
			+ "ycawl (224) -> vpjmvzd, bzlgar, jtujnwo\r\n"
			+ "dppzdx (28)\r\n"
			+ "alcpfsx (136) -> siyuvy, nowyhln\r\n"
			+ "dfdgoj (153) -> aufym, pfxrf\r\n"
			+ "jcuiffa (56)\r\n"
			+ "yjyipdp (66)\r\n"
			+ "ilueo (41)\r\n"
			+ "iazte (201) -> tsetywu, zkzefwh\r\n"
			+ "diavsdh (326) -> wladmn, zudqxa, ajpcyv\r\n"
			+ "llofnny (66)\r\n"
			+ "kitsxb (59)\r\n"
			+ "kqltx (74)\r\n"
			+ "klzfl (93)\r\n"
			+ "tpdcb (84)\r\n"
			+ "afcgdxg (1202) -> qcpuch, njmrq, tnltvzk\r\n"
			+ "gnwjseo (600) -> pkxhxdz, jbfzjha, ixdcgsa, degnsd, fwtfkp\r\n"
			+ "yqnbqgc (178) -> dkzitf, zybvpry\r\n"
			+ "ialtabg (21) -> jbtzoy, sqincn\r\n"
			+ "uorpbn (353) -> ygbyt, afjmzb\r\n"
			+ "jdhiflw (60)\r\n"
			+ "qpwfl (11)\r\n"
			+ "xasioks (405)\r\n"
			+ "lajyaur (19)\r\n"
			+ "ajpujs (271) -> zxzkl, dkgsvl\r\n"
			+ "ovrkpd (147) -> sdzoy, mdrob\r\n"
			+ "sveuu (55)\r\n"
			+ "jtvntr (83)\r\n"
			+ "pvgay (69)\r\n"
			+ "boiic (80) -> ipofw, ggjmhab, mwjtydb\r\n"
			+ "sjcbxp (59)\r\n"
			+ "uvzwdly (20)\r\n"
			+ "sbgtiqe (91)\r\n"
			+ "luzcpkn (43)\r\n"
			+ "ndxuv (80)\r\n"
			+ "tkejpfe (13)\r\n"
			+ "ggjmhab (15)\r\n"
			+ "szvrql (46) -> cnknlru, zrydf, cvvtz, uwiza, gikqie, lknchr\r\n"
			+ "lvkpx (233) -> wmyvz, nnsyc\r\n"
			+ "bhzbv (28) -> azgjimy, frlmoih, azrpi\r\n"
			+ "cujhtj (193) -> qhbotj, qnsnc\r\n"
			+ "vmatvgx (90) -> uaavvo, ezztp\r\n"
			+ "pvpyhb (81)\r\n"
			+ "mdpcfvu (176) -> gyktq, yyswun\r\n"
			+ "aubhuwo (99) -> yyqleqa, nmdhmy\r\n"
			+ "wgglzpb (191) -> gmurq, hkewsbw\r\n"
			+ "amaeuv (58)\r\n"
			+ "ijleirw (172) -> jikzxd, yeewxiw, jhcurc, kosgqpu\r\n"
			+ "tvhfxfo (105) -> wnzdcc, bszcup\r\n"
			+ "kzvwk (74) -> ujogppt, appkqpe\r\n"
			+ "qgxcbt (68)\r\n"
			+ "ipmbqts (23)\r\n"
			+ "woeoaa (59)\r\n"
			+ "yfszfef (85)\r\n"
			+ "ickxyrm (87) -> hrxfpx, owlyge\r\n"
			+ "mjlmuca (41)\r\n"
			+ "iracqt (48)\r\n"
			+ "dtyxosg (84)\r\n"
			+ "vyaoad (83) -> tojpm, euaceg, zhffrzu\r\n"
			+ "jemmk (47) -> mwdvbr, shfjyzk\r\n"
			+ "viafs (19)\r\n"
			+ "iefyz (39)\r\n"
			+ "wkydaz (332) -> orwbp, xhhfsuw, ledgpb, rlwvuj, bpmkexj, diduy\r\n"
			+ "zhiai (228) -> qosqq, ceevpgx\r\n"
			+ "aydmhhv (87)\r\n"
			+ "vtamjj (45)\r\n"
			+ "egabi (79)\r\n"
			+ "zgnwz (87)\r\n"
			+ "kvtvmi (39) -> fpmwz, oeaqbvl, oipjwtz, usevgds, vwtmps, kryoh, gkzeqaw\r\n"
			+ "sszzop (89)\r\n"
			+ "uaavvo (87)\r\n"
			+ "xtvyh (83) -> pczkz, xydxl, xduga, gycde\r\n"
			+ "fpgciql (51)\r\n"
			+ "ynkkomw (279) -> iyjcoy, ijiqjtf\r\n"
			+ "yirkbjn (1872) -> wjjar, ldwhpl, kcimi\r\n"
			+ "paqvyfa (58)\r\n"
			+ "khbvu (51)\r\n"
			+ "jvpgl (20)\r\n"
			+ "sxslizl (86)\r\n"
			+ "gbpcav (77)\r\n"
			+ "kjqiop (40)\r\n"
			+ "ulxsa (115)\r\n"
			+ "nhzmidl (27)\r\n"
			+ "nchjk (37)\r\n"
			+ "yokqfgn (94)\r\n"
			+ "qwdppks (95)\r\n"
			+ "fnijmph (90) -> yqbkjg, ykvtr, fpgciql\r\n"
			+ "xucdiz (6) -> kkyfjh, cxjyxl\r\n"
			+ "ftexc (96)\r\n"
			+ "krembdy (41)\r\n"
			+ "gzykr (1135) -> lejoaru, qfkow, wowkfnh, pjvpqmg\r\n"
			+ "srrxb (81)\r\n"
			+ "ylwniqh (68)\r\n"
			+ "usuujhq (46) -> pkotpki, seyed, jgkmy\r\n"
			+ "ilfgats (6031) -> mxxfu, vrjea, mnwhky\r\n"
			+ "urxxlfo (84) -> juakl, bwywt\r\n"
			+ "fsfuluo (34)\r\n"
			+ "staqwo (8)\r\n"
			+ "ynirne (13)\r\n"
			+ "zyonam (217) -> sofxmjx, ytpiey\r\n"
			+ "ornybn (37)\r\n"
			+ "jvepbal (79) -> cqiipxn, qclpa\r\n"
			+ "goicjt (41)\r\n"
			+ "bfpvsfz (39)\r\n"
			+ "zbxakfn (9)\r\n"
			+ "cqdtav (22)\r\n"
			+ "cufaveh (20)\r\n"
			+ "zxqix (157)\r\n"
			+ "zudqxa (42)\r\n"
			+ "fcvpdiz (67)\r\n"
			+ "kzhpyr (59)\r\n"
			+ "cuwqi (104) -> jotxc, teuzi\r\n"
			+ "mdopg (44)\r\n"
			+ "pyntdrr (320) -> lbiigt, aeliqqs\r\n"
			+ "ouabc (46)\r\n"
			+ "wnzdcc (56)\r\n"
			+ "wvkaie (80)\r\n"
			+ "axrojbs (239) -> aytjryx, xbpqmua, sjixg, lytukj\r\n"
			+ "lcyuk (93)\r\n"
			+ "tdnzc (22)\r\n"
			+ "wrobpcw (1196) -> fujvp, gfuxooq, crkapwa\r\n"
			+ "hyfswg (1414) -> rcywun, kqmhotc, xvwqzt, bbsomm\r\n"
			+ "yugjkuz (58)\r\n"
			+ "tokvgmd (91)\r\n"
			+ "yyqleqa (39)\r\n"
			+ "pmfpitp (33)\r\n"
			+ "nhxmab (24)\r\n"
			+ "hwqvzw (74)\r\n"
			+ "hntdp (90)\r\n"
			+ "nercz (33)\r\n"
			+ "kvjqli (72) -> tpdcb, edoftkj\r\n"
			+ "zdrfiw (80)\r\n"
			+ "viklkmp (19)\r\n"
			+ "evmblgk (183) -> yycux, buifcn, uaqik, fdaddso\r\n"
			+ "wzcgi (55) -> hzsgvc, staqwo, fgxst\r\n"
			+ "baygmx (12)\r\n"
			+ "mxscf (62)\r\n"
			+ "oqhwa (186) -> gcbvf, bgmwpam\r\n"
			+ "sflwom (253) -> uvzwdly, pjkjcy, rcongvf\r\n"
			+ "ajrcal (83)\r\n"
			+ "yqyyoj (33) -> lftlc, npcyutn\r\n"
			+ "tpsgt (28)\r\n"
			+ "ebsxx (22)\r\n"
			+ "aceiy (13)\r\n"
			+ "jwlaj (1031) -> qjuud, tdtznh, cuaect\r\n"
			+ "hvefi (15)\r\n"
			+ "nxtyiha (30)\r\n"
			+ "mzjwcds (229) -> icqsww, pitdti\r\n"
			+ "ndxim (6)\r\n"
			+ "vomrnc (33)\r\n"
			+ "vfmwzb (47)\r\n"
			+ "jidxg (64)\r\n"
			+ "aqtml (293)\r\n"
			+ "cevkjvr (90)\r\n"
			+ "lycpdcu (5) -> rvjzxtg, ovysqnt\r\n"
			+ "thmlk (34)\r\n"
			+ "iujqo (98)\r\n"
			+ "synjm (51)\r\n"
			+ "paqlttl (65)\r\n"
			+ "kklix (25) -> jzoue, yokqfgn\r\n"
			+ "usevgds (44) -> aydmhhv, kkftjia\r\n"
			+ "tqlentr (214) -> gfxnuuk, thmlk";
	
	@Override
	public String part1() {
		ArrayList<TreeNode> nodes = new ArrayList<TreeNode>();
		
		for(String s : input.split("\r\n")) {
			String[] parts = s.split(" ");
			TreeNode node = new TreeNode(parts[0]);
			int weight = Integer.parseInt(parts[1].substring(1,parts[1].length() - 1));
			node.setNodeWeight(weight);
			//add placeholders for children
			if(parts.length > 2) {
				for(int i = 3; i < parts.length; i++) {
					node.addChild(new TreeNode(parts[i].replace(",", "")));
				}
			}
			nodes.add(node);
		}
		//for each node, connect it to its children in list
		for(TreeNode node : nodes) {
			for(int i = 0; i < node.children.size(); i++) {
				node.children.set(i, find(nodes,node.children.get(i).name));
				node.children.get(i).parent = node;
			}
		}
		
		//from any node (first will do), go up till root
		TreeNode root = nodes.get(0);
		while(root.parent != null)
			root = root.parent;
		
		return root.name;
	}

	@Override
	public String part2() {
		//store temporary nodes in list
		ArrayList<TreeNode> nodes = new ArrayList<TreeNode>();
		
		for(String s : input.split("\r\n")) {
			String[] parts = s.split(" ");
			TreeNode node = new TreeNode(parts[0]);
			int weight = Integer.parseInt(parts[1].substring(1,parts[1].length() - 1));
			node.setNodeWeight(weight);
			//add placeholders for children
			if(parts.length > 2) {
				for(int i = 3; i < parts.length; i++) {
					node.addChild(new TreeNode(parts[i].replace(",", "")));
				}
			}
			nodes.add(node);
		}
		//for each node, connect it to its children in list
		for(TreeNode node : nodes) {
			for(int i = 0; i < node.children.size(); i++) {
				node.children.set(i, find(nodes,node.children.get(i).name));
				node.children.get(i).parent = node;
			}
		}
		
		//from any node (first will do), go up till root
		TreeNode root = nodes.get(0);
		while(root.parent != null)
			root = root.parent;		
		
		TreeNode unbalanced = root;
		
		//iterate downwards until we find the first balanced node above an unbalanced one
		while(!isBalanced(unbalanced)) {
			int weight = (unbalanced.children.get(0).getTotalWeight() - unbalanced.children.get(0).nodeWeight) / unbalanced.children.size();
			for(TreeNode c : unbalanced.children) {
				if(c.getTotalWeight() != weight) {
					unbalanced = c;
					break;
				}
			}
		}
		
		
		//move up a level (to deepest unbalanced node), compare children
		unbalanced = unbalanced.parent;
		
		ArrayList<Integer> weights = new ArrayList<Integer>();
		for(TreeNode c : unbalanced.children)
			weights.add(c.totalNodeWeight);
		
		Collections.sort(weights);
		
		//if index of 1 is equal to index of 0, differing weight is at end. otherwise, is at start
		//imagine sorting the array [1,3,1,1,1] - you end up with [1,1,1,1,3], and because indexes 0 and 1 are equal, the differing value must be at the end
		//alternatively, imagine [3,3,1,3,3] - result is [1,3,3,3,3], indexes 0 and 1 are unequal, so 0 is differing value
		int necessaryOffset = (weights.get(1) == Collections.min(weights) ? (Collections.max(weights) - Collections.min(weights)) : (Collections.min(weights) - Collections.max(weights)));
		
		int weight = (unbalanced.children.get(0).getTotalWeight() - unbalanced.children.get(0).nodeWeight) / unbalanced.children.size();
		
		//find weight that needs to be adjusted, return value it needs to be
		for(TreeNode c : unbalanced.children) {
			if(c.getTotalWeight() != weight) {
				return Integer.toString(c.nodeWeight + necessaryOffset);
			}
		}
		return null;
	}
	
	public boolean isBalanced(TreeNode n) {
		if(n.children.size() == 0)
			return true;
		int weight = n.children.get(0).getTotalWeight();
		for(TreeNode c : n.children)
			if(c.getTotalWeight() != weight)
				return false;
		return true;
	}
	
	public static void main(String[] args) {
		DayRunner.run(new Day07());
	}

	public TreeNode find(ArrayList<TreeNode> nodes, String name) {
		for(TreeNode n : nodes)
			if(n.name.equals(name))
				return n;
		return null;
	}
}
